#!/bin/sh
#
# Copy this file to /etc/pm/sleep.d/
#
# Thanks to https://askubuntu.com/questions/521620/prevent-machine-from-sleeping-when-ssh-connections-are-on
#

ips=$(w -h | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' | tr '\n' ' ')
ips=${ips% }

if [ -n "${ips}" ]; then
	echo "User is still logged in from: ${ips}"
	exit 1
fi

exit 0
