#!/bin/bash -eu
#
# Wrapper around common adb operations
#

# -----------------------------------------------------------------------------
# Helper functions

function adb_send_keyevent()
{
	local key=${1}
	local event

	case "${key}" in
		power)  event=26 ;;
		enter)  event=66 ;;
		unlock) event=82 ;;
		*)
			echo "-- Invalid key name: ${key}" >&2
			return
			;;
	esac

	echo "-- Send keyevent: ${event} (${key})"
	adb -s "${SERIAL}" shell input keyevent "${event}"
}

function adb_send_text()
{
	local text=${1}

	adb -s "${SERIAL}" shell input text "${text}"
}

function adb_start_app()
{
	local app=${1}

	echo "-- Start app: ${app}"
	adb -s "${SERIAL}" shell monkey -p "${app}" 1
}

function adb_pull_storage()
{
	local rmt_dir=${1} dst_dir=${2}
	local rmt_dirs rmt_base_dir rmt_full_dir rmt_file

	echo "-- Pull files from ${SERIAL} to ${dst_dir}"

	rmt_dirs=("/storage/self/primary/${rmt_dir}")
	while IFS= read -r rmt_base_dir ; do
		rmt_full_dir="${rmt_base_dir}/${rmt_dir}"
		if adb shell test -d "${rmt_full_dir}" ; then
			rmt_dirs+=("${rmt_full_dir}")
		fi
	done < <(adb shell ls -d /storage/*)

	mkdir -p "${dst_dir}"
	while IFS= read -r rmt_file ; do
		if [ "${rmt_file/\/.trashed-/}" != "${rmt_file}" ] ; then
			continue
		fi
		if ! [ -e "${dst_dir}/${rmt_file##*/}" ] ; then
			adb -s "${SERIAL}" pull "${rmt_file}" "${dst_dir}"
		fi
	done < <(adb shell find "${rmt_dirs[@]}" -type f)
}

# -----------------------------------------------------------------------------
# Plumbing commands

function do_display_off()
{
	if [ "$(do_display_state)" = "ON" ] ; then
		adb_send_keyevent power
	fi
}

function do_display_on()
{
	if [ "$(do_display_state)" = "OFF" ] ; then
		adb_send_keyevent power
	fi
}

function do_display_state()
{
	local state

	state=$(adb -s "${SERIAL}" shell dumpsys power | \
				grep -P '^Display Power: state=' | sed 's/.*=//')
	if [ -n "${state}" ] ; then
		echo "${state}"
		return
	fi

	# Old Android
	state=$(adb -s "${SERIAL}" shell dumpsys power | \
				grep -P '^\s+mPowerState=')
	if [ -n "${state}" ] ; then
		if [ "${state/SCREEN_ON_BIT/}" != "${state}" ] ; then
			echo "ON"
		else
			echo "OFF"
		fi
		return
	fi

	echo "UNKNOWN"
}

function do_serials()
{
	adb devices | awk '$2 == "device" { print $1 }'
}

# -----------------------------------------------------------------------------
# Porcelain Commands

function do_pull_all()
{
	do_pull_backup
	do_pull_camera
	do_pull_download
}

function do_pull_backup()
{
	adb_pull_storage Backup "${HOME}"/Backup/"${SERIAL}"
}

function do_pull_camera()
{
	adb_pull_storage DCIM "${HOME}"/Pictures/"${SERIAL}"
}

function do_pull_download()
{
	adb_pull_storage Download "${HOME}"/Downloads/"${SERIAL}"
}

function do_scrcpy()
{
	# Unlock the device
#	do_unlock

	# Run scrcpy
	echo "-- Run scrcpy"
	scrcpy --serial "${SERIAL}" --turn-screen-off --stay-awake
}

function do_unlock()
{
	local pin

	# Get the pin from the password store
	echo "-- Get pin from password store"
	pin=$(pass show local/android/"${SERIAL}" | head -1)

	# Unlock the device
	echo "-- Unlock device (${SERIAL})"
	adb_send_keyevent unlock
	sleep 1
	# FIXME: Check display/lockscreen state
	adb_send_keyevent unlock
	sleep 1
	adb_send_text "${pin}"
	adb_send_keyevent enter
}


# -----------------------------------------------------------------------------
# App commands

function do_start()
{
	local app=${1}
	local pkg

	case "${app}" in
		klapp) pkg=mobi.klapp.parent ;;
		*)
			echo "-- Unsupported app: ${app}" >&2
			exit 1
			;;
	esac

	adb_start_app "${pkg}"
	sleep 1
	do_scrcpy
}

# -----------------------------------------------------------------------------
# Usage and main entry point

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-h] [-s SERIAL] COMMAND [OPTS]

Wrapper around common adb operations.

App commands:
  start APP            Start an app.

Porcelain commands:
  pull-all             Pull all backup/camera/downloaded files.
  pull-backup          Pull backup files.
  pull-camera          Pull camera files.
  pull-download        Pull downloaded files.
  scrcpy               Run scrcpy.
  unlock               Unlock device.

Plumbing commands:
  display-off          Turn display off.
  display-on           Turn display on.
  display-state        Show display state (ON|OFF|UNKNOWN)
  serials              List serial numbers of connected devices.

Optional arguments:
  -h, --help           Show this help text and exit.
  -s, --serial SERIAL  Serial number of target device. If not provided, targets
                       the first device from the list of connected devices.
EOF
}

SERIAL=
command=

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		-s|--serial)
			SERIAL=${1}
			;;
		pull-all|pull-backup|pull-camera|pull-download|scrcpy|unlock)
			command=${1}
			;;
		display-off|display-on|display-state|serials)
			command=${1}
			;;
		start)
			command=${1}
			shift
			break
			;;
		*)
			echo "Invalid argument: ${1}" >&2
			exit 2
			;;
	esac
	shift
done

if [ -z "${command}" ] ; then
	usage
	exit 2
fi

if [ "${command}" != "serials" ] && [ -z "${SERIAL}" ] ; then
	# Get the serial number of the first device
	SERIAL=$(do_serials | head -1)
fi

do_"${command//-/_}" "${@}"
