#!/bin/bash -eu
#
# Pull all downloaded files via adb
#

mkdir -p ~/Downloads/adb

remotes=(/storage/self/primary/Download)

while IFS= read -r d ; do
	if adb shell test -d "${d}"/Download ; then
		remotes+=("${d}"/Download)
	fi
done < <(adb shell ls -d /storage/*)

echo "adb pull ${remotes[*]} ~/Downloads/adb"
adb pull "${remotes[@]}" ~/Downloads/adb
