#!/usr/bin/env python3
#
# Intel AMT wsman command line interface
#

import argparse
import os
import sys

from lib.amt.power import AMTPower

# -----------------------------------------------------------------------------
# Main entry point

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("action", choices=["power-state", "power-on",
                                           "power-off", "power-cycle",
                                           "reset", "nmi"])
    parser.add_argument("-s", "--host", default=os.getenv("AMT_HOST", None))
    parser.add_argument("-u", "--user", default=os.getenv("AMT_USER", "admin"))
    parser.add_argument("-p", "--password", default=os.getenv("AMT_PASSWORD",
                                                              None))

    args = parser.parse_args()

    if not args.host or not args.password:
        parser.print_help()
        sys.exit(2)

    power = AMTPower(args.host, args.user, args.password)

    if args.action == "power-state":
        print(power.get_power_state())

    else:
        state = args.action
        if state.startswith("power-"):
            state = state[6:]
        print(power.set_power_state(state, wait=False))
