#!/bin/bash
#
# Print ANSI colors
#

echo "Escape sequence:"
echo "\e[<CODE>m<TEXT>\e[0m"
echo

props=(
	"0 reset"
	"1 bold"
	"2 faint"
	"3 italic"
	"4 underline"
	"5 slow blink"
	"6 rapid blink"
	"7 reverse"
)

for prop in "${props[@]}" ; do
	code=${prop%% *}
	text=${prop#* }
	printf "%-3d : " "${code}"
	echo -e "\e[${code}m${text}\e[0m"
done
echo

for code in $(seq 30 37) "" $(seq 40 47) "" $(seq 90 97) "" $(seq 100 107); do
	if [ -z "${code}" ] ; then
		echo
		continue
	fi
	printf "%-3d : " "${code}"
	echo -e "\e[${code}m▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 01234567abcdefgh\e[0m"
done
