#!/bin/bash -eu
#
# This is an autopkgtest-virt-ssh setup script that sets up a libvirt instance
# to use as an autopkg testbed.
# See man autopkgtest-virt-ssh for details.
#

# Add testbed capabilities here (possibly dynamically), see
# doc/README.virtualisation-server.rst
CAPABILITIES="isolation-machine,reboot,revert,revert-full-system"

# The SSH username and password
SSH_USER=ubuntu
SSH_PASS=ubuntu

SSH_OPTS=(
	-o UserKnownHostsFile=/dev/null
	-o StrictHostKeyChecking=no
	-o User="${SSH_USER}"
)

function domain_exists()
{
	virsh dominfo "${NAME}" &>/dev/null
}

function domain_running()
{
	virsh dominfo "${NAME}" | grep -qi '^state:\s*running'
}

function now()
{
	date +%s
}

function wait_for_ip_addr()
{
	local timeout

	timeout=$(($(now) + 300))
	while true ; do
		if [ "$(now)" -gt ${timeout} ] ; then
			echo "-- Error: Timed out waiting for an IP address"
			cleanup
			exit 1
		fi
		IP_ADDR=$(virsh domifaddr "${NAME}" 2>/dev/null | \
		          grep -oP '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' || true)
		if [ -n "${IP_ADDR}" ] && ping -c 1 -W 1 "${IP_ADDR}" >/dev/null 2>&1 ; then
			return
		fi
		sleep 2
	done
}

function wait_for_ssh_access()
{
	local timeout

	timeout=$(($(now) + 300))
	while ! SSHPASS=${SSH_PASS} sshpass -e ssh "${SSH_OPTS[@]}" "${IP_ADDR}" true ; do
		if [ "$(now)" -gt ${timeout} ] ; then
			echo "-- Error: Timed out waiting for SSH access"
			cleanup
			exit 1
		fi
		sleep 5
	done
}

function wait_for_cloud_init()
{
	if ! timeout 10m ssh "${SSH_OPTS[@]}" "${IP_ADDR}" \
		 "while [ ! -e /var/lib/cloud/instance/boot-finished ] ; do sleep 1 ; done" ; then
		echo "-- Error: Timed out waiting for cloud-init to finish"
		cleanup
		exit 1
	fi
}

# Create a testbed (if necessary), configure ssh, copy ssh key into it,
# configure sudo, etc.; print a list of "key=value" parameters to stdout on
# success
# Required: login, hostname, and one of identity or password
# Optional: port, options, capabilities
function open()
{
	echo "-- Cloning domain ${DOMAIN}"
	virt-clone --auto-clone --original "${DOMAIN}" --name "${NAME}"

	# Set the number of CPUs and memory size
	virsh setvcpus "${NAME}" "${CPUS}" --config --maximum
	virsh setmaxmem "${NAME}" "$((RAM_SIZE * 1024))" --config
	virsh setmem "${NAME}" "$((RAM_SIZE * 1024))" --config

	# Fix the console log filename
	EDITOR="sed -i 's/${DOMAIN}.console_log/${NAME}.console_log/'" virsh edit "${NAME}"

	echo "-- OK"

	echo "-- Starting domain ${NAME}"
	virsh start "${NAME}"
	echo "-- OK"

	echo "-- Waiting for an IP address"
	wait_for_ip_addr
	echo "-- OK (${IP_ADDR})"

	echo "-- Waiting for SSH access"
	wait_for_ssh_access
	echo "-- OK"

	echo "-- Copying SSH ID"
	SSHPASS=${SSH_PASS} sshpass -e ssh-copy-id "${SSH_OPTS[@]}" "${IP_ADDR}"
	echo "-- OK"

	# Wait for cloud-init to finish
	echo "-- Waiting for cloud-init to finish"
	wait_for_cloud_init
	echo "-- OK"
}

function open_info()
{
    cat <<EOF
login=${SSH_USER}
hostname=${IP_ADDR}
capabilities=${CAPABILITIES}
EOF
}

function cleanup()
{
	if domain_exists ; then
		if domain_running ; then
			echo "-- Destroying domain ${NAME}"
			virsh destroy "${NAME}"
		fi
		echo "-- Undefining domain ${NAME}"
		virsh undefine "${NAME}" --remove-all-storage
	fi
}

function wait_reboot()
{
	echo "-- Shutting down ${NAME}"
	virsh shutdown "${NAME}"
	while domain_running ; do
		sleep 2
	done
	echo "-- OK"

	echo "-- Starting ${NAME}"
	virsh start "${NAME}"
	wait_for_ip_addr
	wait_for_ssh_access
	wait_for_cloud_init
	echo "--OK"
}

function debug_failure()
{
	echo "-- debug_failure not implemented"
}

function usage()
{
	cat <<EOF
Usage: autopkgtest-virt-virsh [-c CPUS] [-h] [-r RAMSIZE ] -d DOMAIN -n NAME COMMAND

Set up a libvirt instance to use as an autopkg testbed.

Positional arguments:
  COMMAND                  The autopkgtest command:
                           open, cleanup, revert, wait-reboot or debug-failure.

Optional arguments:
  -c, --cpus CPUS          Number of CPUS (defaults to 2).
  -d, --domain DOMAIN      The name of the domain to be cloned.
  -h, --help               Show this help text and exit.
  -n, --name NAME          The name of test domain.
  -r, --ram-size RAMSIZE   Memory size in KiB (defaults to 2048).
EOF
}

# -----------------------------------------------------------------------------
# Main entry point

CPUS=2
DOMAIN=
NAME=
RAM_SIZE=2048
cmd=

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-c|--cpus)
			shift
			CPUS=${1}
			;;
		-d|--domain)
			shift
			DOMAIN=${1}
			;;
		-h|--help)
			usage
			exit
			;;
		-n|--name)
			shift
			NAME=${1}
			;;
		-r|--ram-size)
			shift
			RAM_SIZE=${1}
			;;
		*)
			if [ -z "${cmd}" ] ; then
				cmd=${1,,}
			else
				echo "-- Error: Invalid argument: ${1}" >&2
				exit 2
			fi
	esac
	shift
done

if [ -z "${DOMAIN}" ] || [ -z "${NAME}" ] || [ -z "${cmd}" ] ; then
	usage >&2
	exit 2
fi

case "${cmd}" in

	open)
		open >&2
		open_info
		;;

	cleanup)
		cleanup >&2
		;;

	revert)
		cleanup >&2
		open >&2
		open_info
		;;

	wait-reboot)
		wait_reboot >&2
		;;

	debug-failure)
		debug_failure >&2
		;;

	*)
		echo "-- Error: Invalid command: ${cmd}" >&2
		exit 1
		;;
esac
