#!/bin/bash -eu
#
# Create an autopkgtest libvirt instance from an autopkgtest image
#

function domain_xml_amd64()
{
	cat <<EOF
<domain type="kvm">
  <name>${DOMAIN}</name>
  <uuid>${UUID}</uuid>
  <memory unit="KiB">${RAM}</memory>
  <currentMemory unit="KiB">${RAM}</currentMemory>
  <vcpu placement="static">${CPUS}</vcpu>
  <clock offset="utc"/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>

  <os>
    <type arch="x86_64" machine="pc">hvm</type>
    <boot dev="hd"/>
  </os>

  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>

  <devices>

    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <controller type="pci" index="0" model="pci-root"/>

    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="${IMAGE}"/>
      <target dev="vda" bus="virtio"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x04" function="0x0"/>
    </disk>

    <interface type="network">
      <mac address="${MAC}"/>
      <source network="default"/>
      <model type="virtio"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x0"/>
    </interface>

    <console type="pty">
      <log file="/tmp/${DOMAIN}.console_log" append="off"/>
      <target type="virtio" port="0"/>
    </console>

    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x06" function="0x0"/>
    </controller>

    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x05" function="0x0"/>
    </rng>

  </devices>
</domain>
EOF
}

function domain_xml_arm64()
{
	cat <<EOF
<domain type="qemu">
  <name>${DOMAIN}</name>
  <uuid>${UUID}</uuid>
  <memory unit="KiB">${RAM}</memory>
  <currentMemory unit="KiB">${RAM}</currentMemory>
  <vcpu placement="static">${CPUS}</vcpu>
  <cpu mode="custom" match="exact" check="none">
    <model fallback="allow">cortex-a72</model>
  </cpu>
  <clock offset="utc"/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>

  <os firmware="efi">
    <type arch="aarch64" machine="virt">hvm</type>
    <loader readonly="yes" type="pflash" format="raw">/usr/share/AAVMF/AAVMF_CODE.ms.fd</loader>
    <boot dev="hd"/>
  </os>

  <features>
    <acpi/>
  </features>

  <devices>

    <emulator>/usr/bin/qemu-system-aarch64</emulator>
    <controller type="pci" index="0" model="pcie-root"/>

    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="${IMAGE}"/>
      <target dev="vda" bus="virtio"/>
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
    </disk>

    <interface type="network">
      <mac address="${MAC}"/>
      <source network="default"/>
      <model type="virtio"/>
      <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0"/>
    </interface>

    <serial type="pty">
      <log file="/tmp/${DOMAIN}.console_log" append="off"/>
      <target type="system-serial" port="0">
        <model name="pl011"/>
      </target>
    </serial>

    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
    </controller>

    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
    </rng>

  </devices>
</domain>
EOF
}

function domain_xml_s390x()
{
	cat <<EOF
<domain type="qemu">
  <name>${DOMAIN}</name>
  <uuid>${UUID}</uuid>
  <memory unit="KiB">${RAM}</memory>
  <currentMemory unit="KiB">${RAM}</currentMemory>
  <vcpu placement="static">${CPUS}</vcpu>
  <clock offset="utc"/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>

  <os>
    <type arch="s390x" machine="s390-ccw-virtio">hvm</type>
    <boot dev="hd"/>
  </os>

  <devices>

    <emulator>/usr/bin/qemu-system-s390x</emulator>
    <controller type="pci" index="0" model="pci-root"/>

    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2"/>
      <source file="${IMAGE}"/>
      <target dev="vda" bus="virtio"/>
      <address type="ccw" cssid="0xfe" ssid="0x0" devno="0x0000"/>
    </disk>

    <interface type="network">
      <mac address="${MAC}"/>
      <source network="default"/>
      <model type="virtio"/>
      <address type="ccw" cssid="0xfe" ssid="0x0" devno="0x0001"/>
    </interface>

    <console type="pty">
      <log file="/tmp/${DOMAIN}.console_log" append="off"/>
      <target type="virtio" port="0"/>
    </console>

    <controller type="virtio-serial" index="0">
      <address type="ccw" cssid="0xfe" ssid="0x0" devno="0x0002"/>
    </controller>

    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
      <address type="ccw" cssid="0xfe" ssid="0x0" devno="0x0004"/>
    </rng>

    <panic model="s390"/>

  </devices>
</domain>
EOF
}

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-a ARCH] [-f] [-h] SERIES

Create an autopkgtest libvirt domain from an autopkgtest image.

Optional arguments:
  -a, --arch ARCH
  -f, --force
  -h, --help   Show this help text and exit.
EOF
}

arch=$(dpkg-architecture -qDEB_HOST_ARCH)
force=0
series=

while [ $# -gt 0 ] ; do
	case "${1}" in
		-a|--arch)
			shift
			arch=${1}
			;;
		-f|--force)
			force=1
			;;
		-h|--help)
			usage
			exit
			;;
		*)
			if [ -n "${series}" ] ; then
				usage
				exit 2
			fi
			series=${1}
			;;
	esac
	shift
done

if [ -z "${series}" ] ; then
	usage
	exit 2
fi

DOMAIN=autopkgtest-${series}-${arch}
IMAGE=${HOME}/.cache/autopkgtest/libvirt/${DOMAIN}.img

if ! [ -e "${IMAGE}" ] ; then
	echo "Error: No such image file: ${IMAGE}" >&2
	exit 1
fi

if virsh dominfo "${DOMAIN}" &>/dev/null ; then
	if [ ${force} -eq 0 ] ; then
		echo "Error: Domain exits already. Use --force to replace it." >&2
		exit 1
	fi
	virsh destroy "${DOMAIN}" &>/dev/null || true
	virsh undefine "${DOMAIN}" --nvram || true
fi

UUID=$(uuidgen)
MAC=52:54:00:${UUID:30:2}:${UUID:32:2}:${UUID:34:2}

RAM=$((1024 * 1024))
CPUS=1

tmp_xml=/tmp/vm.$$.xml
# shellcheck disable=SC2064
trap "rm -f ${tmp_xml}" EXIT

domain_xml_"${arch}" > "${tmp_xml}"

virsh define "${tmp_xml}"

#cat "${tmp_xml}"
