#!/bin/bash -eu
#
# Build a Debian source package in a schroot
#

function usage()
{
	cat <<EOF
Usage: build-source-deb [-h] [-m] [-o] [-r RELEASE] [-v VERSION]

Build a Debian source package in a schroot.

Optional arguments:
  -h, --help             Show this help text and exit.
  -m, --maintainer       Ignore maintainer email address (DEBEMAIL).
  -o, --orig             Include the original source tarball.
  -r, --release RELEASE  Use RELEASE rather than querying the changelog.
  -v, --version VERSION  Previous source package version.
EOF
}

orig=0
release=
opts=()

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		-m|--maintainer)
			export DEBEMAIL=
			;;
		-o|--orig)
			orig=1
			;;
		-r|--release)
			shift
			release=${1}
			;;
		-v|--version)
			shift
			opts+=("-v${1}")
			;;
		*)
			echo "Invalid argument: ${1}" 2>/dev/null
			exit 2
			;;
	esac
	shift
done

if [ -d .git ] && [ -n "$(git status --porcelain)" ] ; then
	echo "Repo is unclean"
	exit 1
fi

if [ -z "${release}" ] ; then
	release=$(dpkg-parsechangelog -SDistribution)
	if [ "${release}" = "UNRELEASED" ] ; then
		echo "Release is UNRELEASED"
		exit 1
	fi
fi

set -x
run-chroot "${release}" -- fakeroot ./debian/rules clean
set +x

opts+=(
	"-S"   # Build sources
	"-i"   # Exclude revision control files and directories (diff)
	"-I"   # Exclude revision control files and directories (tarball)
	"-uc"  # Don't sign .buildinfo and .changes files
	"-us"  # Don't sign the source package
	"-d"   # Don't check build dependencies
)

if [ ${orig} -eq 1 ] ; then
	opts+=("-sa")  # Include the original source tarball
fi

set -x
run-chroot "${release}" -- dpkg-buildpackage "${opts[@]}" "${@}"
set +x
