#!/bin/bash -eu
#
# Build kernel Debian packages
#

function pr_error() { echo -e "\033[31mE: ${*}\033[0m" >&2 ; }
function pr_info()  { echo -e "\033[33mI: ${*}\033[0m" ; }

function run_chroot()
{
	pr_info "Run in chroot (${CHROOT}):"
	pr_info "+ ${*}"
	run-chroot "${CHROOT}" -- "${@}"
}

function modules_laptop()
{
	cat <<EOF
8250_dw
ac97_bus
acpi_thermal_rel
aesni_intel
af_alg
algif_hash
algif_skcipher
asus_nb_wmi
asus_wireless
asus_wmi
autofs4
binfmt_misc
bluetooth
bnep
btbcm
btintel
btmtk
btrtl
btusb
ccm
cec
cfg80211
cmac
coretemp
cqhci
crc32_pclmul
crct10dif_pclmul
cryptd
crypto_simd
dm_crypt
drm
drm_buddy
drm_display_helper
drm_kms_helper
ecc
ecdh_generic
efi_pstore
ghash_clmulni_intel
hid
hid_generic
hid_multitouch
i2c_algo_bit
i2c_hid
i2c_hid_acpi
i2c_i801
i2c_smbus
i915
idma64
input_leds
int3400_thermal
int3403_thermal
int340x_thermal_zone
intel_cstate
intel_lpss
intel_lpss_pci
intel_pmc_bxt
intel_powerclamp
intel_punit_ipc
intel_rapl_common
intel_rapl_msr
intel_soc_dts_iosf
intel_telemetry_core
intel_telemetry_pltdrv
ip_tables
irqbypass
iwlmvm
iwlwifi
joydev
kvm
kvm_intel
ledtrig_audio
libarc4
lp
mac80211
mac_hid
mc
mei
mei_hdcp
mei_me
mei_pxp
mfd_aaeon
mmc_block
nls_iso8859_1
parport
parport_pc
pinctrl_geminilake
platform_profile
polyval_generic
ppdev
processor_thermal_device
processor_thermal_device_pci_legacy
processor_thermal_mbox
processor_thermal_rapl
processor_thermal_rfim
rapl
rc_core
rfcomm
sch_fq_codel
sdhci
sdhci_pci
serio_raw
sha1_ssse3
sha256_ssse3
snd
snd_compress
snd_hda_codec
snd_hda_codec_generic
snd_hda_codec_hdmi
snd_hda_codec_realtek
snd_hda_core
snd_hda_ext_core
snd_hda_intel
snd_hwdep
snd_intel_dspcfg
snd_intel_sdw_acpi
snd_pcm
snd_pcm_dmaengine
snd_rawmidi
snd_seq
snd_seq_device
snd_seq_midi
snd_seq_midi_event
snd_soc_acpi
snd_soc_acpi_intel_match
snd_soc_avs
snd_soc_core
snd_soc_hda_codec
snd_soc_hdac_hda
snd_soc_skl
snd_soc_sst_dsp
snd_soc_sst_ipc
snd_sof
snd_sof_intel_hda
snd_sof_intel_hda_common
snd_sof_intel_hda_mlink
snd_sof_pci
snd_sof_pci_intel_apl
snd_sof_utils
snd_sof_xtensa_dsp
snd_timer
soundcore
soundwire_bus
soundwire_cadence
soundwire_generic_allocation
soundwire_intel
sparse_keymap
ttm
uvc
uvcvideo
video
videobuf2_common
videobuf2_memops
videobuf2_v4l2
videobuf2_vmalloc
videodev
wmi
wmi_bmof
x86_pkg_temp_thermal
x_tables
xhci_pci
xhci_pci_renesas
EOF
}

function modules_libvirt()
{
	# Stamdard modules
	cat <<EOF
aes_x86_64
aesni_intel
async_memcpy
async_pq
async_raid6_recov
async_tx
async_xor
autofs4
binfmt_misc
btrfs
cirrus
crc32_pclmul
crct10dif_pclmul
cryptd
crypto_simd
drm
drm_kms_helper
fb_sys_fops
floppy
ghash_clmulni_intel
glue_helper
i2c_piix4
ib_cm
ib_core
ib_iser
input_leds
ip_tables
irqbypass
iscsi_tcp
isofs
iw_cm
joydev
kvm
kvm_amd
kvm_intel
libcrc32c
libiscsi
libiscsi_tcp
linear
mac_hid
multipath
nls_iso8859_1
pata_acpi
pcbc
psmouse
qemu_fw_cfg
raid0
raid1
raid10
raid456
raid6_pq
rdma_cm
sch_fq_codel
scsi_transport_iscsi
serio_raw
syscopyarea
sysfillrect
sysimgblt
ttm
virtio_blk
virtio_net
x_tables
xor
zstd_compress
EOF

	# Manually loaded by kernel selftests
	cat <<EOF
act_bpf
act_connmark
act_csum
act_ct
act_ctinfo
act_gact
act_gate
act_mirred
act_mpls
act_nat
act_pedit
act_police
act_sample
act_simple
act_skbedit
act_skbmod
act_tunnel_key
act_vlan
adi
amd-pstate-ut
br_netfilter
cls_basic
cls_bpf
cls_cgroup
cls_flow
cls_flower
cls_fw
cls_matchall
cls_route
cls_u32
configs
dummy
em_canid
em_cmp
em_ipset
em_ipt
em_meta
em_nbyte
em_text
em_u32
fou
fou6
ftrace-direct
ftrace-direct-too
geneve
gpio-sim
i915
ifb
intel_sdsi
ip6_tunnel
ip6table_filter
ip_vs
ipip
lkdtm
memory-notifier-error-inject
mpls_gso
mpls_iptunnel
netdevsim
nf_conntrack
nf_conntrack_ipv6
nf_defrag_ipv6
ntb_msi_test
ntb_perf
ntb_pingpong
ntb_tool
ntb_transport
rc-loopback
sch_cake
sch_cbs
sch_choke
sch_codel
sch_drr
sch_etf
sch_ets
sch_fq
sch_fq_codel
sch_fq_pie
sch_gred
sch_hfsc
sch_hhf
sch_htb
sch_teql
sctp
sctp_diag
test-drm_mm
test-ww_mutex
test_blackhole_dev
test_bpf
test_firmware
test_fpu
test_module
test_static_key_base
test_static_keys
test_user_copy
trace-printk
tun
udp_tunnel
usbip_host
vhci_hcd
vrf
vxlan
zram
EOF
}

function modules_raspi()
{
	cat <<EOF
8021q
8250_bcm7271
ac97_bus
aes_ce_blk
aes_ce_cipher
af_alg
algif_hash
algif_skcipher
async_memcpy
async_pq
async_raid6_recov
async_tx
async_xor
autofs4
bcm2835_codec
bcm2835_isp
bcm2835_mmal_vchiq
bcm2835_mmc
bcm2835_v4l2
binfmt_misc
blake2b_generic
bluetooth
bnep
brcmfmac
brcmfmac_wcc
brcmutil
btbcm
btintel
btqca
btrfs
btrtl
btsdio
cec
cfg80211
cqhci
crct10dif_ce
dax
dm_mod
dm_multipath
drm_display_helper
drm_dma_helper
drm_shmem_helper
dw_axi_dmac_platform
dwc2
dwc3
ecc
ecdh_generic
fuse
garp
gf128mul
ghash_ce
gpio_brcmstb
gpio_generic
gpio_keys
gpu_sched
hci_uart
hid_generic
i2c_bcm2835
i2c_brcmstb
i2c_designware_core
i2c_designware_platform
ip_tables
libcrc32c
llc
macb
mc
md_mod
mrp
nfnetlink
nvmem_rmem
phy_generic
phylink
pisp_be
polyval_ce
polyval_generic
pwm_brcmstb
pwm_fan
pwm_rp1
pwrseq_core
qrtr
raid0
raid1
raid10
raid456
raid6_pq
raspberrypi_gpiomem
raspberrypi_hwmon
reset_brcmstb
reset_brcmstb_rescal
rfcomm
rfkill
roles
rp1_adc
rpivid_hevc
rtc_rpi
sch_fq_codel
sdhci_brcmstb
sha1_ce
sha256_arm64
sha2_ce
sm4
snd
snd_bcm2835
snd_compress
snd_hrtimer
snd_pcm
snd_pcm_dmaengine
snd_rawmidi
snd_seq
snd_seq_device
snd_seq_dummy
snd_seq_midi
snd_seq_midi_event
snd_soc_core
snd_soc_hdmi_codec
snd_timer
spi_bcm2835
spi_dw
spi_dw_mmio
spidev
stp
tls
uas
udc_core
uio
uio_pdrv_genirq
ulpi
usb_storage
usbhid
v3d
v4l2_mem2mem
vc4
vc_sm_cma
videobuf2_common
videobuf2_dma_contig
videobuf2_memops
videobuf2_v4l2
videobuf2_vmalloc
videodev
x_tables
xhci_pci
xhci_pci_renesas
xhci_plat_hcd
xor
xor_neon
z3fold
zstd
EOF
}

function syz_configs()
{
	# Configs required for syzcaller
	cat <<EOF
# Coverage collection.
CONFIG_KCOV=y

# Debug info for symbolization.
CONFIG_DEBUG_INFO_DWARF4=y

# Memory bug detector
CONFIG_KASAN=y
CONFIG_KASAN_INLINE=y

# Required for Debian Stretch and later
CONFIG_CONFIGFS_FS=y
CONFIG_SECURITYFS=y
EOF
}

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-h] CMD [ARGS...]

Build kernel Debian packages.

To build an Ubuntu raspi kernel:
  $ build-kernel-deb config raspi
  $ build-kernel-deb make

To build a generic Ubuntu kernel:
  $ build-kernel-deb config generic
  $ build-kernel-deb make

Available commands:
  config [CONFIG]    Create kernel config. Supported <CONFIG> values:
                       menu:    Run config menu.
                       generic: Use generic Ubuntu configs.
                       raspi:   Use raspi Ubuntu configs.
                       *config: Use upstream arch/<arch>/configs/*config configs.
  make               Build kernel Debian packages.

Optional common arguments:
  --arch ARCH        Debian package architecture.
  --buildd BUILDD    Use buildd/<BUILDD> as the build output directory.
                     If not provided, defaults to buildd/<SERIES>.
  --chroot CHROOT    Use chroot <CHROOT>.
  -h, --help         Show this help text and exit.
  -jX                Number of jobs, default one per CPU.

Optional arguments for 'config' command:
  --debug-info       Enable DEBUG_INFO config option.
  --lsmod LSMOD      Enable modules listed in <LSMOD>.
  --mod-laptop       Enable a minimal set of modules for laptops.
  --mod-libvirt      Enable a minimal set of modules for libvirt.
  --mod-raspi        Enable a minimal set of modules for raspi.
  --syz              Enable config options for syzcaller.
EOF
}

arch=
buildd=
chroot=
debug_info=0
jobs=$(getconf _NPROCESSORS_ONLN)
lsmod=
cmd=
flavor=
mod_laptop=0
mod_libvirt=0
mod_raspi=0
syz=0

module_subset=0

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		--arch)
			shift
			arch=${1}
			;;
		--buildd)
			shift
			buildd=${1}
			;;
		--chroot)
			shift
			chroot=${1}
			;;
		--debug-info)
			debug_info=1
			;;
		-h|--help)
			usage
			exit
			;;
		-j[1-9]*)
			jobs=${1#-j}
			if [ -z "${jobs}" ] ; then
				shift
				jobs=${1}
			fi
			;;
		--lsmod)
			shift
			lsmod=${1}
			module_subset=1
			;;
		--mod-laptop)
			mod_laptop=1
			module_subset=1
			;;
		--mod-libvirt)
			mod_libvirt=1
			module_subset=1
			;;
		--mod-raspi)
			mod_raspi=1
			module_subset=1
			;;
		--syz)
			syz=1
			;;
		config)
			cmd=${1}
			shift
			flavor=${1}
			;;
		make)
			cmd=${1}
			;;
		*)
			break
			;;
	esac
	shift
done

if [ -z "${cmd}" ] ; then
	usage
	exit 2
fi

#
# Determine the chroot and series
#

if [ -n "${chroot}" ] ; then
	series=$(run-chroot "${chroot}" -- lsb_release -c -s 2>/dev/null)
	CHROOT=${chroot}
else
	# shellcheck disable=SC1091
	if [ -e debian/debian.env ] ; then
		. debian/debian.env
		series=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog -S Distribution)
	else
		series=$(lsb_release -c -s 2>/dev/null)
	fi
	CHROOT=cranky--${series}
fi

#
# Determine architecture and cross-compilation
#

if [ -z "${arch}" ] ; then
	arch=$(dpkg-architecture -q DEB_BUILD_ARCH)
fi

if [ "${arch}" != "$(dpkg-architecture -q DEB_BUILD_ARCH)" ] ; then
	ARCH=$(dpkg-architecture -a "${arch}" -q DEB_HOST_ARCH_CPU 2>/dev/null)
	CROSS_COMPILE=$(dpkg-architecture -a "${arch}" -q DEB_HOST_GNU_TYPE 2>/dev/null)-

	pr_info "Cross-compilation for: ${ARCH}"
	export ARCH CROSS_COMPILE
fi

#
# Set exports
#

if [ -n "${buildd}" ] ; then
	KBUILD_OUTPUT=buildd/${buildd}
else
	KBUILD_OUTPUT=buildd/${series}
fi
mkdir -p "${KBUILD_OUTPUT}"

pr_info "Use kernel build output directory: ${KBUILD_OUTPUT}"
export KBUILD_OUTPUT

#
# Process the command
#

case "${cmd}" in
	config)
		case "${flavor}" in
			menu)
				run_chroot make menuconfig
				;;

			generic|raspi|*config)
				case "${flavor}" in
					generic|raspi)
						pr_info "Generate Ubuntu config (${arch}, ${flavor})"
						rm -rf CONFIGS
						run_chroot fakeroot debian/rules clean
						run_chroot debian/rules genconfigs || true

						cp CONFIGS/"${arch}"-config.flavour."${flavor}" "${KBUILD_OUTPUT}"/.config
						;;
					*)
						pr_info "Generate kernel config (${arch}, ${flavor})"
						run_chroot make "${flavor}"
						;;
				esac

				if [ ${module_subset} -eq 1 ] ; then
					pr_info "Enable only a subset of modules"

					if [ -z "${lsmod}" ] ; then
						lsmod=${KBUILD_OUTPUT}/bkd.modules
						echo "Module" > "${lsmod}"
					fi

					if [ ${mod_laptop} -eq 1 ] ; then
						modules_laptop >> "${lsmod}"
					fi

					if [ ${mod_libvirt} -eq 1 ] ; then
						modules_libvirt >> "${lsmod}"
					fi

					if [ ${mod_raspi} -eq 1 ] ; then
						modules_raspi >> "${lsmod}"
					fi

					run_chroot make LSMOD="$(realpath -e "${lsmod}")" localmodconfig
				fi

				if [ ${syz} -eq 1 ] ; then
					pr_info "Set syzcaller configs"
					syz_configs >> "${KBUILD_OUTPUT}"/.config
				fi

				if [ ${debug_info} -eq 1 ] ; then
					pr_info "Not disable debug info"
				else
					pr_info "Disable CONFIG_DEBUG_INFO"
					sed -i '/CONFIG_DEBUG_INFO/d' "${KBUILD_OUTPUT}"/.config
					echo "# CONFIG_DEBUG_INFO is not set" >> "${KBUILD_OUTPUT}"/.config
				fi

				if true ; then
					pr_info "Disable CONFIG_RUST"
					echo "# CONFIG_RUST is not set" >> "${KBUILD_OUTPUT}"/.config
				fi

				run_chroot make olddefconfig
				;;

			*)
				pr_error "Invalid config option: ${flavor}"
				exit 1
				;;
		esac
		;;

	make)
		# FIXME: Disable the build of the dbg package
		#sed -i -e 's/ CONFIG_DEBUG_INFO/ __BOGUS_CONFIG__/' scripts/package/mkdebian

		run_chroot make -j"${jobs}" "${@:-bindeb-pkg}"
		;;

	*)
		pr_error "Invalid command: ${1}"
		exit 1
		;;
esac
