#!/bin/bash -eu
#
# Build and download debs using CBD
#

function usage()
{
	cat <<EOF
Usage: cbd-build [-h] [-d DIR] [-- OPTS]

Build and download Debian packages using CBD.

Positional arguments:
  OPTS                 Additional options for 'git push cbd'.

Optional arguments:
  -h, --help           Show this help text and exit.
  -d, --directory DIR  Directory to download the Debian packages to. If not
                       provided, defaults to '../cbdd/<git_hash>'.
EOF
}

output_dir=

while [ $# -gt 0 ] ; do
	case "${1}" in
		-d|--directory)
			shift
			output_dir=${1}
			;;
		-h|--help)
			usage
			exit
			;;
		--)
			shift
			break
			;;
		-*)
			echo "Invalid argument: ${1}" >&2
			exit 2
			;;
	esac
	shift
done

# Add cbd remote if necessary
if ! git remote | grep -q '^cbd$' ; then
	# shellcheck disable=SC1091
	. debian/debian.env
	series=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog -S Distribution)
	git remote add cbd cbd:"${series}".git
fi

# Build
git push cbd -o vars "${@}" 2>&1 | tee cbd-build.log

while IFS= read -r var ; do
	export "${var?}"
done < <(grep "^remote: CBD_" cbd-build.log | \
			 sed -e "s/^remote: //" -e "s/\s*$//")

if [ -z "${CBD_JOB}" ] ; then
	echo "Job ID not found" >&2
	exit 1
fi

if [ -z "${output_dir}" ] ; then
	git_hash=${CBD_JOB%-*}
	git_hash=${git_hash##*-}
	output_dir=../cbdd/${git_hash}
	rm -rf "${output_dir}"
fi

# Download
echo "-- Downloading build artifacts to ${output_dir}"
cbd-download -o "${output_dir}" "${CBD_JOB}"
