#!/bin/bash -u

job_id=${1}

tmpd=/tmp/${job_id%%/*}

mkdir -p "${tmpd}"
trap "rm -rf ${tmpd}" EXIT

ssh cbd tarball "${job_id}" | ( cd "${tmpd}" && tar -xzvf - )
find "${tmpd}" -name '*.deb' | xargs -I{} mv '{}' .
