#!/bin/bash -eu
#
# Build and download debs using CBD
#

function usage()
{
	cat <<EOF
Usage: cbd-build [-h] [-o DIR] [-- OPTS]

Build and download Debian packages using CBD.

Positional arguments:
  OPTS              Additional options for 'git push cbd'.

Optional arguments:
  -h, --help        Show this help text and exit.
  -o, --output DIR  Directory to download the Debian packages to. If not
                    provided, defaults to 'cbdd'.
EOF
}

output_dir=cbdd

while [ $# -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		-o|--output)
			shift
			output_dir=${1}
			;;
		--)
			shift
			break
			;;
		-*)
			echo "Invalid argument: ${1}" >&2
			exit 2
			;;
	esac
	shift
done

# Add cbd remote if necessary
if ! git remote | grep -q '^cbd$' ; then
	# shellcheck disable=SC1091
	. debian/debian.env
	series=$(dpkg-parsechangelog "${DEBIAN}"/changelog -S Distribution)
	git remote add cbd cbd:"${series}".git
fi

# Build
git push cbd -o wait=quiet "${@}" 2>&1 | tee cbd-build.log

job_id=$(grep -m1 '/BUILD-OK' cbd-build.log)
job_id=${job_id%%/*}
job_id=${job_id##* }

if [ -z "${job_id}" ] ; then
	echo "No build artifacts to download" >&2
	exit 1
fi

# Download
echo "-- Downloading build artifacts to cbdd/"
cbd-download -o "${output_dir}" "${job_id}"
