#!/bin/bash -eu
#
# Enqueue a mainline rebuild
#


function usage()
{
	cat <<EOF
Usage: $(basename "$0") [-f] [-h] TAG

Enqueue a mainline rebuild.

Postional arguments:
  TAG           Upstream tag to rebuild, e.g., v6.1.

Optional arguments:
  -f, --force   Do it.
  -h, --help    Show this help text and exit.
EOF
}

force=0
tag=

while [ ${#} -ne 0 ] ; do
	case "${1}" in
		-f|--force)
			force=1
			;;
		-h|--help)
			usage
			exit
			;;
		*)
			if [ -n "${tag}" ] ; then
				echo "Invalid argument: ${1}" >&2
				exit 2
			fi
			tag=${1}
			;;
	esac
	shift
done

if [ -z "${tag}" ] ; then
	usage
	exit 2
fi

if [ -z "${KTEAM_TOOLS}" ] ; then
	KTEAM_TOOLS=${HOME}/kteam-tools
fi

url="https://kernel.ubuntu.com/~kernel-ppa/mainline/${tag}/REBUILD"
rebuild=$(curl -s -f "${url}" || true)
if [ -z "${rebuild}" ] ; then
	echo "Failed to parse: ${url}" >&2
	exit 1
fi

echo "${KTEAM_TOOLS}/mainline-build/cod-enqueue ${rebuild}"

if [ ${force} -eq 0 ] ; then
	echo "Use -f, --force to enqueue."
	exit
fi

"${KTEAM_TOOLS}"/mainline-build/cod-enqueue ${rebuild}
