#!/bin/bash

model=$(cat /proc/device-tree/model | tr '\0' '\n')
echo "${model}"

krelease=$(uname -r)
echo "${krelease}"

kversion=$(uname -v)
kversion=${kversion%% *}
echo "${kversion}"

machine=$(uname -m)
echo "${machine}"

ksuffix=${krelease}_${kversion}_${machine}

bname=${model#Raspberry Pi }
bname=${bname%% Rev *}
bname=${bname/Compute Module/cm}
bname=${bname/Model /}
bname=${bname// /-}
bname=rpi-${bname,,}

test -d "${bname}" || mkdir "${bname}"

cat /proc/device-tree/model > "${bname}/model"

uname -a > "${bname}/uname_${ksuffix}"
sudo modprobe configs
zcat /proc/config.gz > "${bname}/config_${ksuffix}"
dmesg > "${bname}/dmesg_${ksuffix}"
lsmod > "${bname}/lsmod_${ksuffix}"
cat /proc/meminfo > "${bname}/meminfo_${ksuffix}"

tmpf=$(mktemp)
find /proc/device-tree/ > "${tmpf}"
find /proc/device-tree/ | grep '/name$' | xargs grep -a '' >> "${tmpf}"
sort "${tmpf}" > "${bname}/dt_${ksuffix}"
rm -f "${tmpf}"
