#!/bin/bash
#
# Destroy all cranky chroot sessions (and base chroots) and rebuild them
#

CRANKY=${CRANKY:-cranky}

arch=$(dpkg --print-architecture)

while IFS= read -r session ; do
	schroot -e -c "${session}"
done < <(schroot -l --all-sessions | grep "^session:cranky-.*-${arch}-sources")

for series in trusty xenial bionic focal jammy kinetic lunar mantic ; do
	if ! [ -e /etc/schroot/chroot.d/sbuild-"${series}"-"${arch}" ] ; then
		"${CRANKY}" chroot create-base "${series}":linux
	fi
	"${CRANKY}" chroot create-session sources "${series}":linux
done
