#!/bin/bash -eu

function usage()
{
	cat <<EOF
Usage: cranky-scp-sources [-h] HOST

Optional arguments:
  -h, --help  Show this help message and exit.
EOF
}

host=

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		*)
			if [ -n "${host}" ] ; then
				echo "Invalid argument: ${1}" >&2
				exit 2
			fi
			host=${1}
			;;
	esac
	shift
done

if [ -z "${host}" ] ; then
	usage
	exit 2
fi

readarray -t paths < <(cranky shell-helper source-packages-path)

first=1
for path in "${paths[@]}" ; do
	cd "${path}"

	DEBIAN=debian
	if [ -e debian/debian.env ] ; then
		# shellcheck disable=SC1091
		. debian/debian.env
	fi

	name=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog -S Source)
	version=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog -S Version)

	files=(
		../"${name}"_"${version}"_source.buildinfo
		../"${name}"_"${version}"_source.changes
		../"${name}"_"${version}".dsc
	)

	if ! gpg --verify-files "${files[@]}" 2>/dev/null ; then
		echo "Invalid signature(s) on ${files[*]}" >&2
		exit 1
	fi

	if [ ${first} -eq 1 ] ; then
		first=0
		ae=$(git log --format=%ae -1)
		user=$(grep "<${ae}>" ~/.kteam.rc | awk '{print $1}' | tr -d '"' |
				   tr -d "'")
		if [ -z "${user}" ] ; then
			echo "Failed to determine username for ${ae}" >&2
			exit 1
		fi
		echo "Create ${host}:~${USER}/review/${user}"
		# shellcheck disable=SC2029
		ssh "${host}" "mkdir -p review/${user}"
	fi
	scp "${files[@]}" "${host}":review/"${user}"
done
