#!/bin/bash -eu

CRANKY=${CRANKY:-cranky}

readarray -t paths < <("${CRANKY}" shell-helper source-packages-path)

for path in "${paths[@]}" ; do
	cd "${path}"
	echo

	DEBIAN=debian
	if [ -e debian/debian.env ] ; then
		# shellcheck disable=SC1091
		. debian/debian.env
	fi

	name=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog -S Source)
	version=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog -S Version)

	changes=../${name}_${version}_source.changes
	echo "Sign ${changes}"
	debsign --re-sign -e "${DEBEMAIL}" "${changes}"
done
