#!/bin/bash -eu

branch=$(git rev-parse --abbrev-ref HEAD)

case "${branch}" in
	master-next|cranky/master-next) ;;
	*)
		echo "Invalid branch: ${branch}" >&2
		exit 1
		;;
esac

if [ -n "$(git status --porcelain)" ] ; then
	echo "Repo is not clean" >&2
	exit 1
fi

cranky fix
cranky rebase
cranky fix
cranky open
