#!/bin/bash -eu
#
# Create an 'Update to upstream raspberrypi ...' commit
#

function usage()
{
	cat <<EOF
Usage: rpi-update-commit [-h]

Create an 'Update to upstream raspberrypi ...' commit.

Optional arguments:
  -h, --help  Show this help text and exit.
EOF
}

while [ $# -gt 0 ] ; do
	case "$1" in
		-h|--help)
			usage
			exit
			;;
		*)
			usage
			exit 2
			;;
	esac
	shift
done

trap "echo Failure" INT TERM EXIT HUP

# Walk back in history to find the latest raspberrypi commit
found=0
while IFS= read -r commit ; do
	commit=$(git log "${commit}" -1 | \
				 grep -P 'cherry picked from|backported from' | tail -1 | \
				 grep -oP '[0-9a-f]{40}' || true)
	if [ -n "${commit}" ] ; then
		oneline=$(git log --format='%h ("%s")' "${commit}" -1)
		tag=$(git tag --points-at "${oneline%% *}" | grep '^rpi-' | tail -1)
		if [ -n "${tag}" ] ; then
			found=1
			break
		fi
	fi
done < <(git log --format=%h HEAD~20..)

if [ "${found}" -ne 1 ] ; then
	echo "Failed to find the latest raspberrypi commit" >&2
	exit 1
fi

branch=${tag%.y-*}.y
date=${tag#*.y-}

cat <<EOF > debian.raspi/upstream-raspberrypi
# The following upstream raspberrypi releases have been ported:
[upstream-raspberrypi]:
    ${branch} = ${oneline} [${date}]
EOF

git commit -s \
	-m "UBUNTU: raspi: Update to upstream raspberrypi ${commit::12} (${date})" \
	-m "Ignore: yes" \
	-- debian.raspi/upstream-raspberrypi

trap - INT TERM EXIT HUP
