#!/bin/bash -eu
#
# Create a Debian package release commit
#

function usage()
{
	cat <<EOF
Usage: create-release [-h] [-s SUFFIX] [-u] [PREV_REL_COMMIT]

Create a Debian package release commit.

Postional arguments:
  PREV_REL_COMMIT      Previous release commit.

Optional arguments:
  -h, --help           Show this help text and exit.
  -s, --suffix SUFFIX  Append SUFFIX to the current package version to generate
                       the new version rather than bumping the upload number.
  -u, --ubuntu         Force Ubuntu'ness.
EOF
}

suffix=
ubuntu=0
prev_release=

while [ "${#}" -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		-s|--suffix)
			shift
			suffix=${1}
			;;
		-u|--ubuntu)
			ubuntu=1
			;;
		*)
			if [ -n "${prev_release}" ] ; then
				echo "Invalid argument: ${1}" >&2
				exit 2
			fi
			prev_release=${1}
			;;
	esac
	shift
done

DEBIAN=debian
if [ -e debian/debian.env ] ; then
	ubuntu=1
	# shellcheck disable=SC1091
	. debian/debian.env
fi
changelog=${DEBIAN}/changelog

src=$(dpkg-parsechangelog -l"${changelog}" -S Source)
version=$(dpkg-parsechangelog -l"${changelog}" -S Version)
dist=$(dpkg-parsechangelog -l "${changelog}" -S Distribution)
urgency=$(dpkg-parsechangelog -l"${changelog}" -S Urgency)

case "${src}" in
	linux-firmware*)
		ubuntu=1
		ubuntu_prefix=
		;;
esac

if [ "${dist}" != UNRELEASED ] ; then
	# Add a new changelog entry

	ubuntu_prefix=
	if [ -z "${prev_release}" ] ; then
		prev_release=$(git log --oneline -1000 | \
		               grep -m1 -P "^[0-9a-f]{12,} UBUNTU: Ubuntu(-.*)?-${version}$" || \
		               true)
		ubuntu_prefix=${prev_release%-"${version}"}
		ubuntu_prefix=${ubuntu_prefix#* Ubuntu}
		prev_release=${prev_release%% *}
	fi
	if [ -z "${prev_release}" ] ; then
		echo "Unable to find previous release commit" >&2
		exit 1
	fi

	if [ -n "${suffix}" ] ; then
		new_version=${version}${suffix}
	else
		upload=$(echo "${version}" | grep -oP '[0-9]+$')
		new_version=${version%"${upload}"}$((upload + 1))
	fi

	{
		echo "${src} (${new_version}) UNRELEASED; urgency=${urgency}"
		echo
		if [ ${ubuntu} -eq 1 ] ; then
			git log "${prev_release}".. | git-ubuntu-log
		else
			git log --format='  * %s' --reverse "${prev_release}"..
		fi
		echo
		echo " -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)"
		echo
		cat "${changelog}"
	} > "${changelog}".new
	mv "${changelog}".new "${changelog}"
fi

# Close the release
dist=$(dpkg-parsechangelog -l "${changelog}" -S Distribution -o 1 -c 1)
dch --changelog "${changelog}" --release --distribution "${dist}" ""

# Commit the release
version=$(dpkg-parsechangelog -l"${changelog}" -S Version)
if [ ${ubuntu} -eq 1 ] ; then
	git commit -s -m "UBUNTU: Ubuntu${ubuntu_prefix}-${version}" -- "${changelog}"
else
	git commit -s -m "Release ${src} (${version})" -- "${changelog}"
fi
