#!/bin/bash -eu
#
# Create a config drive for configuring cloud images
#

name=${1:-}

if [ -z "${name}" ] ; then
    echo "Usage: create-config-drive <VM hostname>"
    exit 2
fi

public_key=$(cat ~/.ssh/id_rsa.pub)

tmpd=$(mktemp -d)
# shellcheck disable=SC2064
trap "rm -rf ${tmpd}" EXIT

# meta data
cat <<EOF >"${tmpd}/meta-data"
{ instance-id: $(uuidgen) }
EOF

# user data
cat <<EOF >"${tmpd}/user-data"
#cloud-config
chpasswd: { expire: false }
hostname: ${name}
manage_etc_hosts: localhost
password: ${name%%-*}
ssh_authorized_keys: [ ${public_key} ]
ssh_pwauth: true
max_wait: 15
EOF

echo "meta-data:"
cat "${tmpd}/meta-data"
echo

echo "user-data:"
cat "${tmpd}/user-data"
echo

genisoimage -ldots -allow-lowercase -allow-multidot -l -J -r -o "${name}.iso" \
    -V cidata "${tmpd}"
