#!/bin/bash -eu
#
# Create an 'Update to upstream raspberrypi ...' commit
#

function usage()
{
	cat <<EOF
Usage: rpi-update-commit [-h]

Create an 'Update to upstream raspberrypi ...' commit.

Optional arguments:
  -h, --help  Show this help text and exit.
EOF
}

while [ $# -gt 0 ] ; do
	case "$1" in
		-h|--help)
			usage
			exit
			;;
		*)
			usage
			exit 2
			;;
	esac
	shift
done

trap "echo Failure" INT TERM EXIT HUP

buglink=$(git log --format=%b -20 | grep -m1 '^BugLink:')
bug=${buglink##*/}

title=$(curl -s -S --get "https://api.launchpad.net/devel/bugs/${bug}" | \
    python3 -c "import json,sys; print(json.load(sys.stdin)['title'])")

title=${title#* }
date=${title##* (}
date=${date%)*}
branch=rpi-${title##* rpi-}
branch=${branch%% *}

oneline=$(git log --format='%h ("%s")' "${branch}-${date}" -1)

cat <<EOF > debian.raspi/upstream-raspberrypi
# The following upstream raspberrypi releases have been ported:
[upstream-raspberrypi]:
    ${branch} = ${oneline} [${date}]
EOF

git commit -s \
	-m "UBUNTU: raspi: ${title}" \
	-m "${buglink}" \
	-m "Ignore: yes" \
	-- debian.raspi/upstream-raspberrypi

trap - INT TERM EXIT HUP
