#!/bin/bash

FIRST=1
function header()
{
	[ ${FIRST} -eq 1 ] && FIRST=0 || echo
	echo "-- $(date -R)"
	echo "-- ${*}"
}

function footer()
{
	echo "-- Done"
	echo "-- $(date -R)"
}

if [ "$(id -u)" -eq 0 ] ; then
    exec sudo -u juergh "$0"
fi

d=/home/juergh/git/cron

log=${d}/cron-hourly.log
mv "${log}" "${log}".1

{
	# shellcheck disable=SC2155
	export SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh

	header "Run git-update hourly"
	"${d}"/tools/git-update hourly "${d}"

	footer

} > "${log}" 2>&1
