#!/bin/bash

if [ "$(id -u)" -eq 0 ] ; then
    exec sudo -u juergh "$0"
fi

d=/home/juergh/git/cron

log=${d}/cron-hourly.log
mv "${log}" "${log}".1

{
	"${d}"/tools/git-update hourly "${d}"
} > "${log}" 2>&1
