#!/bin/bash

FIRST=1
function header()
{
	[ ${FIRST} -eq 1 ] && FIRST=0 || echo
	echo "-- $(date -R)"
	echo "-- ${*}"
}

function footer()
{
	echo "-- Done"
	echo "-- $(date -R)"
}

if [ "$(id -u)" -eq 0 ] ; then
	exec sudo -u juergh "$0"
fi

d=/home/juergh/git/cron

log=${d}/cron-daily.log
mv "${log}".2 "${log}".3
mv "${log}".1 "${log}".2
mv "${log}" "${log}".1

{
	# shellcheck disable=SC2155
	export SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh

	header "Run git-update daily"
	"${d}"/tools/git-update daily "${d}"

	header "Run find-fixes"
	"${d}"/tools/find-fixes --branch master "${d}"/linux.git "${d}"/linux.fixes

	header "Run linux-fixes"
	"${d}"/tools/linux-fixes "${d}"/linux-fixes.json.gz add "${d}"/linux.git master

	header "Run cranky-update-sessions"
	"${d}"/tools/cranky-update-sessions

	header "Run git-fetch-linux-ubuntu"
	( cd "${d}"/linux-ubuntu.git && "${d}"/tools/git-fetch-linux-ubuntu )

	footer

} > "${log}" 2>&1
