#!/bin/bash

if [ "$(id -u)" -eq 0 ] ; then
    exec sudo -u juergh "$0"
fi

d=/home/juergh/git/cron

log=${d}/cron-hourly.log
mv "${log}" "${log}".1

{
	# shellcheck disable=SC2155
	export SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh

	echo "-- Run git-update hourly"
	"${d}"/tools/git-update hourly "${d}"
	echo "-- Done"

} > "${log}" 2>&1
