#!/bin/bash -eu

function usage() {
	cat <<EOF
Usage: dd-rpi-image [-b HOST] [-h] IMAGE DEVICE

Copy the Raspberry Pi image IMAGE to device DEVICE.

Positional arguments:
  IMAGE                 Image name. If IMAGE is not an existing file, assume
                        it's the name of an image that can be downloaded from
                        a bottle-pi host.
  DEVICE                Target device.

Optional arguments:
  -b, --bottle-pi HOST  Bottle-pi hostname. If not provided, defaults to
                        'ozzy:5000'.
  -h, --help            Show this help text and exit.
EOF
}

bottle_pi=ozzy:5000
img=
dev=

while [ "$#" -gt 0 ] ; do
	case "${1}" in
		-b|--bottle-pi)
			shift
			bottle_pi=${1}
			;;
		-h|--help)
			usage
			exit
			;;
		*) if [ -z "${img}" ] ; then
			   img=${1}
		   elif [ -z "${dev}" ] ; then
			   dev=${1}
		   else
			   echo "Invalid argument: ${1}" >&2
			   exit 2
		   fi
	esac
	shift
done

if [ -z "${img}" ] || [ -z "${dev}" ] ; then
	usage >&2
	exit
fi

if ! [ -b "${dev}" ] ; then
	echo "No such device file: ${dev}" >&2
	exit 1
fi

readarray -t mnts < <(mount | grep -P "^${dev}[0-9]* " | awk '{ print $1 }')
for mnt in "${mnts[@]}" ; do
	umount "${mnt}"
done

if [ -e "${img}" ] ; then
	case "${img}" in
		*.gz) cmd="zcat" ;;
		*.xz) cmd="xzcat" ;;
		*)    cmd="cat" ;;
	esac
	echo "Copy ${img} to ${dev}"
	"${cmd}" "${img}" | dd of="${dev}" bs=4K conv=fsync status=progress
else
	url=http://${bottle_pi}/redfish/v1/Images/${img}
	echo "Download ${url} to ${dev}"
	wget -nv -O - "${url}" | zcat | \
		dd of="${dev}" bs=4K conv=fsync status=progress
fi
