#!/bin/bash -eu

function usage() {
	cat <<EOF
Usage: dd-rpi-image [-h] IMAGE DEVICE

Copy the Raspberry Pi image IMAGE to device DEVICE.

Positional arguments:
  IMAGE       The image to copy.
  DEVICE      The device to copy the image to.

Optional arguments:
  -h, --help  Show this help text and exit.
EOF
}

img=
dev=

while [ "$#" -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		*) if [ -z "${img}" ] ; then
			   img=${1}
		   elif [ -z "${dev}" ] ; then
			   dev=${1}
		   else
			   echo "Invalid argument: ${1}" >&2
			   exit 2
		   fi
	esac
	shift
done

if [ -z "${img}" ] || [ -z "${dev}" ] ; then
	usage >&2
	exit
fi

if ! [ -e "${img}" ] ; then
	echo "No such image file: ${img}" >&2
	exit 1
fi

if ! [ -b "${dev}" ] ; then
	echo "No such device file: ${dev}" >&2
	exit 1
fi

readarray -t mnts < <(mount | grep -P "^${dev}[0-9]* " | awk '{ print $1 }')
for mnt in "${mnts[@]}" ; do
	umount "${mnt}"
done

case "${img}" in
	*.gz)
		cmd="zcat"
		;;
	*.xz)
		cmd="xzcat"
		;;
	*)
		cmd="cat"
		;;
esac

"${cmd}" "${img}" | dd of="${dev}" bs=4K conv=fsync status=progress
