#!/bin/bash -eu

function usage() {
	cat <<EOF
Usage: $(basename "${0}") [-h] [-o HOST] IMAGE|URL DEVICE

Copy a Raspberry Pi image to a device.

Positional arguments:
  IMAGE            Image name. If IMAGE is not an existing file, assume it is
                   the name of a gzip-compressed image that can be downloaded
                   from a remote host, i.e., HOST/IMAGE.
  URL              Fully qualified URL of a gzip-compressed image.
  DEVICE           Target device.

Optional arguments:
  -h, --help       Show this help text and exit.
  -o, --host HOST  Hostname to download the image from. If not provided,
                   defaults to 'http://192.168.99.11/images'.
EOF
}

host="http://192.168.99.11/images"
img=
dev=

while [ "$#" -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		-o|--host)
			shift
			host=${1}
			;;
		*) if [ -z "${img}" ] ; then
			   img=${1}
		   elif [ -z "${dev}" ] ; then
			   dev=${1}
		   else
			   echo "Invalid argument: ${1}" >&2
			   exit 2
		   fi
	esac
	shift
done

if [ -z "${img}" ] || [ -z "${dev}" ] ; then
	usage
	exit 2
fi

if ! [ -b "${dev}" ] ; then
	echo "No such device file: ${dev}" >&2
	exit 1
fi

readarray -t mnts < <(mount | grep -P "^${dev}[0-9]* " | awk '{ print $1 }')
for mnt in "${mnts[@]}" ; do
	umount "${mnt}"
done

if [ -e "${img}" ] ; then
	case "${img}" in
		*.gz) cmd="zcat" ;;
		*.xz) cmd="xzcat" ;;
		*)    cmd="cat" ;;
	esac
	echo "Copy ${img} to ${dev}"
	"${cmd}" "${img}" | sudo dd of="${dev}" bs=4K conv=fsync status=progress
else
	if [ "${img#http}" = "${img}" ] ; then
		img=${host}/${img}
	fi
	echo "Download ${img} to ${dev}"
	wget -nv -O - "${img}" | zcat | \
		sudo dd of="${dev}" bs=4K conv=fsync status=progress
fi
