#!/bin/bash -eu
#
# Commit debian/changelog and tag it
#


source=$(dpkg-parsechangelog -S Source)
version=$(dpkg-parsechangelog -S Version)
series=$(dpkg-parsechangelog -S Distribution)

if [ "${series}" = "UNRELEASED" ] ; then
	echo "Series is UNRELEASED" >&2
	exit 1
fi

git add debian/changelog
git commit -s -m "${source} ${version}"
git tag -s -m "${source} ${version}" "${version}"
