#!/usr/bin/env python3
#
# Sort Debian package versions
#

import argparse
import sys
from functools import cmp_to_key

import apt_pkg

aparser = argparse.ArgumentParser()
aparser.add_argument("-r", "--reverse", action="store_true",
                     help="Reverse the results of comparisons.")
args = aparser.parse_args()

apt_pkg.init()

lines = sys.stdin.read().splitlines()
print("\n".join(sorted(lines, key=cmp_to_key(apt_pkg.version_compare), reverse=args.reverse)))
