#!/bin/bash -eu
#
# Enable remote desktop
#

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-h]

Enable GNOME remote desktop.

Environment variables:
  PASSWORD    Password for the current user. If not set, prompt for it.

Optional arguments:
  -h, --help  Show this help text and exit.
EOF
}

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		*)
			echo "Invalid argument: ${1}" >&2
			exit 2
			;;
	esac
	shift
done

password=${PASSWORD:-}
if [ -z "${password}" ] ; then
	read -r -s -p "Password for user ${USER}: " password
	echo
fi

# Unlock the GNOME keyring
killall -u "${USER}" gnome-keyring-daemon
echo -n "${password}" | $(which gnome-keyring-daemon) --daemonize --login
$(which gnome-keyring-daemon) --start

# Disable screen blank
gsettings set org.gnome.desktop.session idle-delay "uint32 0"

# Enable RDP
gsettings set org.gnome.desktop.remote-desktop.rdp enable true
gsettings set org.gnome.desktop.remote-desktop.rdp view-only false

# Set the RDP password
echo -n "{'username': <'${USER}'>, 'password': <'${password}'>}" |
	secret-tool store --label="GNOME Remote Desktop RDP credentials" \
	            "xdg:schema" "org.gnome.RemoteDesktop.RdpCredentials"

# (Re-)start the service
systemctl --user restart gnome-remote-desktop
