#!/bin/bash -u
#
# Update local git repos and mirrors
#

update_repo()
{
	local repo=${1}

	(
		cd "${repo}" || exit 1

		echo
		echo "-- $(date -R)"
		echo "-- Update repo $(pwd)"

		git fetch
		remote_branch=$(git rev-parse --abbrev-ref '@{u}')
		git reset --hard "${remote_branch}"
	)
}

update_mirror()
{
	local repo=${1}

	(
		cd "${repo}" || exit 1

		echo
		echo "-- $(date -R)"
		echo "-- Update mirror $(pwd)"

		git fetch --all --tags
	)
}

do_hourly()
{
	# Update repos
	for repo in * ; do
		if [ -d "${repo}"/.git ] ; then
			update_repo "${repo}"
		fi
	done
}

do_daily()
{
	if [ -d linux.git ] ; then
		# Update the main linux mirror first (since all the others use it as a
		# reference)
		update_mirror linux.git

		# Update the fixes file
		echo "-- Update linux.fixes"
		tools/find-fixes linux.git linux.fixes
	fi

	# Update the remaining mirrors
	for repo in *.git ; do
		if [ -d "${repo}" ] && [ "${repo}" != "linux.git" ] ; then
			update_mirror "${repo}"
		fi
	done
}

if [ ${#} -ne 2 ] ; then
	cat <<EOF
Usage: $(basename "${0}") hourly|daily GIT_DIR
EOF
	exit 2
fi

freq=${1}
dir=${2}

if ! cd "${dir}" ; then
	echo "-- Failed to cd to ${dir}" >&2
	exit 1
fi

log=git-update-${freq}.log
mv "${log}" "${log}".1

do_"${freq}" 2>&1 | tee "${log}"
