#!/bin/sh
#
# Update git repo clones
#

fetch_repo()
{
	date -R
	echo "Fetching ${1}"

	git -C "${1}" fetch --prune
	git -C "${1}" reset --hard FETCH_HEAD
	date -R > "${1}"/.fetched
}

fetch_all()
{
	# Current working directory
	cwd=$(dirname "$(readlink -e "${0}")")
	cd "${cwd}"

	for git_dir in * ; do
		if [ -d "${git_dir}/.git" ] ; then
			fetch_repo "${git_dir}"
		fi
	done
}

fetch_all 2>&1 | tee git-fetch-hourly.log
