#!/bin/bash -eu
#
# Helper script for managing Debian/Ubuntu package git repos
#

function out()
{
	local rc=$?

	trap - INT TERM EXIT HUP

	if [ ${rc} -ne 0 ] ; then
		pr_error "Script failed"
	fi

	exit "${rc}"
}

function pr_error()
{
	echo -e "\033[31m${*}\033[0m" 1>&2
}

function set_globals()
{
	local remote

	remote=$(git remote get-url origin)
	repo=${remote##*/}

	if [ "${repo}" = kteam-tools ] ; then
		SUBJECT_PREFIX="kteam-tools][PATCH"
	else
		if [ -z "${RELEASE}" ] ; then
			# shellcheck disable=SC1091
			. debian/debian.env
			RELEASE=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog \
										  -S Distribution)
		fi
		SUBJECT_PREFIX="SRU][${RELEASE^}][PATCH"
	fi
}

function send_patch()
{
	local opts=()

	# Additional options
	if [ "${DRY_RUN}" -eq 1 ] ; then
		opts+=("--dry-run")
	fi

	git send-email .outgoing/*.patch --suppress-cc=all "${opts[@]}"
}

function do_format_patch()
{
	local opts=()

	# Additional options
	if [ "${COVER_LETTER}" -eq 1 ] ; then
		opts+=("--cover-letter")
	fi
	if [ -n "${SUBJECT_PREFIX}" ] ; then
		opts+=("--subject-prefix=${SUBJECT_PREFIX}")
	fi
	if [ -n "${IN_REPLY_TO}" ] ; then
		opts+=("--in-reply-to=${IN_REPLY_TO}")
	fi

	rm -rf .outgoing/
	git format-patch -o .outgoing/ "${opts[@]}" "${@}"

	if [ "${DRY_RUN}" -eq 1 ] ; then
		echo "git format-patch -o .outgoing/ ${opts[*]} ${*}"
		for p in .outgoing/*.patch ; do
			echo
			echo -e "\e[33m*** ${p#*/} ***\e[0m"
			echo
			colordiff < "${p}"
		done
	fi
}

function do_send_patch()
{
	do_format_patch -1
	send_patch
}

function usage()
{
	cat <<EOF
Usage: git-deb [-d] [-h] COMMAND [ARGS]

Helper script for managing Ubuntu package git repos.

Supported commands:
  format-patch  Create patch (series).
  send-patch    Send a single commit as a patch email.

Optional arguments:
  -c, --cover-letter        Add a cover letter.
  -d, --dry-run             Don't send the email.
  -h, --help                Show this help text.
  -i, --in-reply-to MSG_ID  Reply to the given MSG_ID.
  -r, --release RELEASE     The release to include in the subject prefix.
EOF
}

# -----------------------------------------------------------------------------
# Main entry point

COVER_LETTER=0
DRY_RUN=0
IN_REPLY_TO=
RELEASE=
SUBJECT_PREFIX=

cmd=
args=()

while [ ${#} -gt 0 ] ; do
	case ${1} in
		-c|--cover-letter)
			COVER_LETTER=1
			;;
		-d|--dry-run)
			DRY_RUN=1
			;;
		-h|--help)
			usage
			exit
			;;
		-i|--in-reply-to)
			shift
			IN_REPLY_TO=${1}
			;;
		-r|--release)
			shift
			RELEASE=${1}
			;;
		format-patch|send-patch)
			cmd=${1//-/_}
			;;
		*)
			if [ -z "${cmd}" ] ; then
				pr_error "Unexpected argument: ${1}" >&2
				exit 1
			fi
			args=("${@}")
			break
			;;
	esac
	shift
done

if [ -z "${cmd}" ] ; then
	usage
	exit 2
fi

set_globals
do_"${cmd}" "${args[@]}"
