#!/bin/sh -u
#
# Update git repo clones
#

fetch_repo()
{
	date -R
	echo "-- Fetching $(pwd)/${1}"

	git -C "${1}" fetch --prune
	git -C "${1}" reset --hard FETCH_HEAD
	date -R > "${1}"/.fetched
}

if ! cd "${1}" ; then
	echo "-- Failed to cd to ${1}" >&2
	exit 1
fi

for git_dir in * ; do
	if [ -d "${git_dir}/.git" ] ; then
		fetch_repo "${git_dir}"
	fi
done
