#!/bin/sh
#
# Update git repo mirrors
#

fetch_repo()
{
	date -R
	echo "Fetching ${1}"

	git -C "${1}" fetch --prune
	date -R > "${1}"/.fetched
}

fetch_all()
{
	# Fetch the main linux repo first (since all the others use it as a
	# reference)
	fetch_repo linux.git

	# Update the fixes file
	echo "Finding fixes commits"
	./find-fixes linux.git linux.fixes

	# Fetch the remaining repos
	for git_dir in *.git ; do
		if [ -d "${git_dir}" ] && [ "${git_dir}" != "linux.git" ] ; then
			fetch_repo "${git_dir}"
		fi
	done
}

# Current working directory
cwd=$(dirname "$(readlink -e "${0}")")
cd "${cwd}"

fetch_all 2>&1 | tee git-fetch-daily.log
