#!/bin/bash -eu
#
# To initialize the repo:
#   git clone --bare --origin upstream --reference linux.git linux.git linux-ubuntu.git
#

function out()
{
	local rc=${?}

	trap - EXIT INT TERM HUP

	if [ ${rc} -ne 0 ] ; then
		echo "Script failed" >&2
	fi

	exit "${rc}"
}

function ubuntu_kernel_info()
{
	ubuntu-kernel-info \
		--field series.name,package.name,package.repo.url,package.repo.branch \
		--pkg-type main \
		"${@}"
}

function usage()
{
	cat <<EOF
Usage: git-fetch-linux-ubuntu [-h]

Fetch Ubuntu (and upstream) kernels.

Optional arguments:
  -h, --help  Show this help text and exit.
EOF
}

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		*)
			echo "Invalid argument: ${1}" >&2
			exit 2
			;;
	esac
	# shellcheck disable=SC2317
	shift
done

if ! [ -e config ] ; then
	echo "No such file: config" >&2
	exit 1
fi

trap out EXIT INT TERM HUP

# Just in case
git config remote.upstream.pushurl "(no push)"
git config remote.upstream.tagopt "--no-tags"
git config --unset-all remote.upstream.fetch || true
git config --add remote.upstream.fetch "+refs/heads/linux*:refs/heads/upstream/linux*"
git config --add remote.upstream.fetch "+refs/tags/v*:refs/tags/v*"

# Remove all remotes (except upstream)
while IFS= read -r remote ; do
	if [ "${remote}" != "upstream" ] ; then
		git remote remove "${remote}"
	fi
done < <(git remote)

# Add remotes
while IFS=" " read -r ktype series package url branch ; do
	if [ "${package}" = "linux-unstable" ] ; then
		series=unstable
	fi

	remote=${ktype}/${series}/${package}
	tag_prefix=Ubuntu${package#linux}

	git remote add "${remote}" "${url}"
	git config remote."${remote}".pushurl "(no push)"
	git config remote."${remote}".tagopt "--no-tags"
	git config --unset-all remote."${remote}".fetch || true
	git config --add remote."${remote}".fetch "+refs/heads/${branch}:refs/heads/${remote}"
	for v in $(seq 1 9) ; do
		git config --add remote."${remote}".fetch "+refs/tags/${tag_prefix}-${v}*:refs/tags/${tag_prefix}-${v}*"
	done

done < <(
#	ubuntu_kernel_info --pkg-name linux supported      | sed 's/^/ubuntu /'
	ubuntu_kernel_info supported                       | sed 's/^/ubuntu /'
	ubuntu_kernel_info --src-name linux-unstable devel | sed 's/^/ubuntu /'
	ubuntu_kernel_info --src-name linux supported-esm  | sed 's/^/esm /'
)

# Fetch everything
git fetch --all
