#!/bin/bash -u

fetch()
{
	cd "${1}" || { echo "$(date -R) Failed to cd to ${1}" >&2 ; exit 1 ; }

	echo "$(date -R ) Fetch ${1}"
	git fetch

	while IFS= read -r branch ; do
		f=.tag_${branch}
		sha=$(git rev-parse "${branch}")
		if [ "${sha}" != "$(cat "${f}")" ] ; then
			tag=${branch}-$(date +'%Y-%m-%d')
			echo "Create tag ${tag}"
			git tag "${tag}" "${branch}"
			echo "${sha}" > "${f}"
		fi
	done < <(git branch | cut -b 3- | grep -P '^rpi-[0-9]+\.[0-9]+\.y$')

	echo "$(date -R) Push to Launchpad"
	git push git+ssh://juergh@git.launchpad.net/~juergh/+git/linux-rpi --all --force
}

cwd=$(dirname "${0}")
fetch "${cwd}"/linux-rpi.git 2>&1 | tee "${cwd}"/git-fetch-rpi.log
