#!/bin/bash -u

fetch()
{
	date -R
	cd "${1}" || { echo "-- Failed to cd to ${1}" >&2 ; exit 1 ; }

	echo "-- Fetch https://github.com/raspberrypi/linux.git"
	git fetch --tags --force https://github.com/raspberrypi/linux.git refs/heads/*:refs/heads/*

	# shellcheck disable=SC2010
	while IFS= read -r ref ; do
		commit=$(cat "${ref}")
		if ! grep -q "${commit}" refs/tags/* ; then
			tag=${ref##*/}-$(date +'%Y-%m-%d')
			echo "-- Create tag ${tag}"
			git tag "${tag}" "${commit}"
		fi
	done < <(ls -1 refs/heads/rpi-* | grep -E '/rpi-[0-9]+\.[0-9]+\.y$')

	echo "-- Push to Launchpad"
	git push --all --force git+ssh://juergh@git.launchpad.net/~juergh/+git/linux-rpi
	git push --tags --force git+ssh://juergh@git.launchpad.net/~juergh/+git/linux-rpi
	date -R
}

cwd=$(dirname "${0}")
fetch "${cwd}"/linux-rpi.git 2>&1 | tee "${cwd}"/git-fetch-rpi.log
