#!/bin/bash -u
#
# Update and mirror Ubuntu buildinfo to Launchpad juergh/linux-buildinfo-ubuntu
#

if ! cd "${1}" ; then
    echo "-- Failed to cd to ${1}" >&2
    exit 1
fi

date -R

echo "-- Reset main branch"
git checkout --force main
git fetch
git reset --hard origin/main

echo "-- Update branch"
./update-all

echo "-- Push branch"
git push --force origin

echo "-- Push to Launchpad"
git push --force git+ssh://juergh@git.launchpad.net/~juergh/+git/linux-buildinfo-ubuntu refs/*:refs/*

echo "-- Done"
date -R
