#!/bin/sh
#
# Update git repo mirrors
#

fetch_repo()
{
	date -R
	echo "Fetching ${1}"

	git -C "${1}" fetch
	date -R > "${1}"/.fetched
}

fetch_all()
{
	# Fetch the main and stable linux repos first since the others use them as
	# references
	fetch_repo linux.git
	fetch_repo linux-stable.git

	# Fetch the remaining repos
	for git_dir in *.git ; do
		if [ -d "${git_dir}" ] ; then
			fetch_repo "${git_dir}"
		fi
	done

	# Create daily raspberrypi tags
	if [ -d linux-raspberrypi.git ] ; then
		echo "Creating daily tags"
		git -C linux-raspberrypi.git tag "rpi-5.4.y-$(date +'%Y-%m-%d')" \
			rpi-5.4.y
	fi

	# Update the fixes file
	echo "Finding fixes commits"
	./find-fixes linux.git linux.fixes
}

# Current working directory
cwd=$(dirname "$(readlink -e "${0}")")
cd "${cwd}"

fetch_all 2>&1 | tee git-fetch-daily.log
