#!/bin/bash -eu
#
# Cherry-pick (transplant) a merge
#

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-a] [-h] [-u] <merge-commit>

Cherry-pick (transplant) a git merge.

Optional arguments:
  -a, --amend  Ammend commit messages.
  -h, --help   Show this help text and exit.
EOF
}

ammend=0

while [ $# -ne 0 ] ; do
	case "${1}" in
		-a|--ammend)
			ammend=1
			;;
		-h|--help)
			usage
			exit
			;;
		-*)
			usage >&2
			exit 2
			;;
		*)
			break
			;;
	esac
	shift
done

if [ $# -ne 1 ] ; then
	usage >&2
	exit 2
fi

merge_commit=${1}

read -r p1 p2 < <(git show -s --format=%p "${merge_commit}")

if [ -z "${p2}" ] ; then
	echo "EE: Not a merge commit: ${merge_commit}" >&2
	exit 1
fi

branch=$(git symbolic-ref --short HEAD)

tmp_branch=tmp-$$
git checkout -b "${tmp_branch}"

while IFS= read -r line ; do
	echo "II: Cherry-pick ${line}"
	git cherry-pick "${line%% *}"
	if [ ${ammend} -eq 1 ] ; then
		git commit --amend
	fi
done < <(git log --reverse --oneline "${p1}".."${p2}")

git checkout "${branch}"

echo "II: Merge branch ${tmp_branch}"
git merge "${tmp_branch}" --no-ff -m "tbd"
git commit --amend -C "${merge_commit}"

git branch -d "${tmp_branch}"
