#!/bin/bash -u
#
# Update local git repos and mirrors
#

function update_repo()
{
	local repo=${1}

	(
		cd "${repo}" || exit 1

		echo
		echo "-- $(date -R)"
		echo "-- Update repo $(pwd)"

		git fetch
		remote_branch=$(git rev-parse --abbrev-ref '@{u}')
		git reset --hard "${remote_branch}"
	)
}

function update_mirror()
{
	local repo=${1}

	(
		cd "${repo}" || exit 1

		echo
		echo "-- $(date -R)"
		echo "-- Update mirror $(pwd)"

		git fetch --all --tags
	)
}

if [ ${#} -ne 2 ] ; then
	cat <<EOF
Usage: $(basename "${0}") hourly|daily GIT_DIR
EOF
	exit 2
fi

freq=${1}
dir=${2}

if ! cd "${dir}" ; then
	echo "-- Failed to cd to ${dir}" >&2
	exit 1
fi

while IFS= read -r repo ; do
	case "${repo}" in
		"#"*|"")
			continue
			;;
		*.git)
			update_mirror "${repo}"
			;;
		*)
			update_repo "${repo}"
			;;
	esac
done <"${freq}".list
