#!/bin/bash -u
#
# Update repo and push to origin
#

if ! cd "${1}" ; then
    echo "-- Failed to cd to ${1}" >&2
    exit 1
fi

date -R

echo "-- Reset main branch"
git checkout --force main
git fetch
git reset --hard origin/main

echo "-- Update branch"
./update-all

echo "-- Push to Launchpad"
git push --force origin

echo "-- Done"
date -R
