#!/bin/bash -u
#
# Update local git repos and mirrors
#

update_repo()
{
	local repo=${1}

	date -R
	echo "-- Update repo $(pwd)/${repo}"

	git -C "${repo}" fetch
	git -C "${repo}" reset --hard FETCH_HEAD
	date -R > "${repo}"/.update
}

update_mirror()
{
	local repo=${1}

	date -R
	echo "-- Update mirror $(pwd)/${repo}"

	git -C "${repo}" fetch --all --tags
	date -R > "${repo}"/.update
}

do_hourly()
{
	# Update repos
	for repo in * ; do
		if [ -d "${repo}"/.git ] ; then
			update_repo "${repo}"
		fi
	done
}

do_daily()
{
	if [ -d linux.git ] ; then
		# Update the main linux mirror first (since all the others use it as a
		# reference)
		update_mirror linux.git

		# Update the fixes file
		echo "-- Find fixes commits"
		find-fixes linux.git linux.fixes
	fi

	# Update the remaining mirrors
	for repo in *.git ; do
		if [ "${repo}" != "linux.git" ] ; then
			update_mirror "${repo}"
		fi
	done
}

if [ ${#} -ne 2 ] ; then
	cat <<EOF
Usage: $(basename "${0}") hourly|daily GIT_DIR
EOF
	exit 2
fi

cmd=${1}
dir=${2}

if ! cd "${dir}" ; then
	echo "-- Failed to cd to ${dir}" >&2
	exit 1
fi

do_"${cmd}"
