#!/bin/bash -u
#
# Mirror Github raspberrypi/linux to Launchpad juergh/linux-rpi
#

if ! cd "${1}" ; then
    echo "-- Failed to cd to ${1}" >&2
    exit 1
fi

today=$(date +'%Y-%m-%d')

date -R

# Save the current branch state
git for-each-ref refs/heads > .heads

echo "-- Update mirror $(pwd)"
git fetch

while IFS= read -r head ; do
	branch=${head#*refs/heads/}
	tag=${branch}_${today}

	prev_tag=${branch}_${today}@1
	prev_commit=$(grep -P "/${branch}$" .heads | awk '{ print $1 }')

	if ! git merge-base --is-ancestor "${prev_commit}" "${branch}" ; then
		# The branch was force-updated, so tag the previous and current
		# branch heads
		echo "-- Create tags ${prev_tag} ${tag}"
		git tag -a -m "Autotag: ${prev_tag}" "${prev_tag}" "${prev_commit}"
		git tag -a -m "Autotag: ${tag}" "${tag}" "${branch}"
	fi

	if ! git tag | grep -qP "^${branch}_\d{4}-\d{2}-\d{2}$" ; then
		# There is no branch tag at all, so create one
		echo "-- Create tag ${tag}"
		git tag -a -m "Autotag: ${tag}" "${tag}" "${branch}"
	fi

done < <(git for-each-ref refs/heads | grep -P '/rpi-[0-9]+\.[0-9]+\.y$')

echo "-- Push to Launchpad"
git push --mirror lp

echo "-- Done"
date -R
