#!/bin/bash -u
#
# Mirror Github raspberrypi/linux to Launchpad juergh/linux-rpi
#

if ! cd "${1}" ; then
    echo "-- Failed to cd to ${1}" >&2
    exit 1
fi

date -R
echo "-- Fetch https://github.com/raspberrypi/linux.git"

git fetch --force https://github.com/raspberrypi/linux.git +refs/heads/*:refs/heads/*
git fetch --tags --force https://github.com/raspberrypi/linux.git

# shellcheck disable=SC2010
while IFS= read -r ref ; do
	commit=$(cat "${ref}")
	if ! grep -q "${commit}" refs/tags/* ; then
		tag=${ref##*/}-$(date +'%Y-%m-%d')
		echo "-- Create tag ${tag}"
		git tag "${tag}" "${commit}"
	fi
done < <(ls -1 refs/heads/rpi-* | grep -E '/rpi-[0-9]+\.[0-9]+\.y$')

echo "-- Clean up"
if [ -e gc.log ] ; then
	rm -f gc.log
	git prune
else
	git gc
fi

echo "-- Push to Launchpad"
git push --all --force git+ssh://juergh@git.launchpad.net/~juergh/+git/linux-rpi
git push --tags --force git+ssh://juergh@git.launchpad.net/~juergh/+git/linux-rpi

echo "-- Done"
date -R
