#!/bin/bash -eu

function out()
{
	local rc=$?

	trap - EXIT INT TERM HUP

	if [ -n "${CONFIG}" ] ; then
		rm -f "${CONFIG}"
	fi

	if [ "${rc}" -ne 0 ] ; then
		echo "Script failed" >&2
	fi

	exit "${rc}"
}

function usage()
{
	cat <<EOF
Usage: gmail-move-mail [-d] [-h] [-q] USERNAME

Move mails using imapfilter.

Positional arguments:
  USERNAME       The gmail username

Optional arguments:
  -d, --dry-run  Dump the imapfilter config file but do not run it.
  -h, --help     Show this help text and exit.
  -q, --quiet    Run imapfilter in non-verbose mode.
EOF
}

username=
dry_run=0
quiet=0

while [ $# -gt 0 ] ; do
	case "${1}" in
		-d|--dry-run)
			dry_run=1
			;;
		-h|--help)
			usage
			exit
			;;
		-q|--quiet)
			quiet=1
			;;
		-*)
			echo "Invalid argument: ${1}" >&2
			exit 2
			;;
		*)
			if [ -n "${username}" ] ; then
				usage
				exit 2
			fi
			username=${1}
			;;
	esac
	shift
done

if [ -z "${username}" ] ; then
	usage
	exit 2
fi

CONFIG=
trap out EXIT INT TERM HUP

cwd=$(dirname "$(readlink -e "${0}")")
CONFIG=$(mktemp)

# Pull in the library
cat "${cwd}/config/imapfilter/lib.lua" > "${CONFIG}"

cat <<EOF >>"${CONFIG}"

options.timeout = 120
options.subscribe = true
options.create = true
-- options.namespace = false
options.info = false

gmail_account = IMAP {
   server = 'imap.gmail.com',
   username = '${username}',
   password = show_pass('google.com/${username}'),
   ssl = 'tls1.2',
}
EOF

if [ "${username%@canonical.com}" != "${username}" ] ; then
	cat <<EOF >>"${CONFIG}"

-- Move '[ACTIVITY]' mails
move_mail_contain_subject(gmail_account, 'Mailing List/Canonical/canonical-kernel-team', 'Canonical/Activity', '[ACTIVITY]')
move_mail_contain_subject(gmail_account, 'Mailing List/Canonical/core-canonical-kernel-team', 'Canonical/Activity', '[ACTIVITY]')

-- Move 'The Daily Bug Report for ...' mails
move_mail_contain_subject(gmail_account, 'Mailing List/Ubuntu/kernel-team', 'Canonical/Bugs', 'The Daily Bug Report for')

-- Move mails older than 60 days
move_mail_is_older_recursive(gmail_account, '', '__Archive', 60)
EOF
fi

if [ "${dry_run}" -eq 1 ] ; then
	cat "${CONFIG}"
	exit
fi

opts=()
if [ "${quiet}" -eq 0 ] ; then
	opts+=("-v")
fi

imapfilter "${opts[@]}" -c "${CONFIG}"
