#!/bin/bash -eu
#
# Create or extract an initrd
#

function usage()
{
	cat <<EOF
Usage $(basename "${0}") [-c] [-f] [-h] INFILE|INDIR [OUTDIR|OUTFILE]

Create or extract an initrd.

Positional parameters:
  INFILE|INDIR    Input initrd file or directory.
  OUTDIR|OUTFILE  Output initrd directory or file. If not provided, defaults
                  to <INFILE>.d or <INDIR>.img, respectively.

Optional arguments:
  -c, --compress METHOD  Compression method. If not provided, defaults to
                         'gzip'.
  -f, --force            Overwrite an existing output file/directory.
  -h, --help             Show this help text and exit
EOF
}

compress=
force=0
in=
out=

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-c|--compress)
			shift
			compress=${1}
			;;
		-f|--force)
			force=1
			;;
		-h|--help)
			usage
			exit
			;;
		*)
			if [ -z "${in}" ] ; then
				in=$(realpath -m "${1}")
			elif [ -z "${out}" ] ; then
				out=$(realpath -m "${1}")
			else
				echo "Invalid argument: ${1}" >&2
				exit 2
			fi
			;;
	esac
	shift
done

if [ -z "${in}" ] ; then
	usage
	exit 2
fi

if ! [ -e "${in}" ] ; then
	echo "No such input file/directory: ${in}" >&2
	exit 1
fi

if [ -z "${out}" ] ; then
	if [ -d "${in}" ] ; then
		out=${in}.img
	else
		out=${in}.d
	fi
fi

if [ ${force} -eq 1 ] ; then
	rm -rf "${out}"
fi

if [ -e "${out}" ] ; then
	echo "Output file/directory exists already: ${out}" >&2
	exit 1
fi

if [ -d "${in}" ] ; then
	# Compression method
	case "${compress,,}" in
		""|gzip)   cmd="gzip" ;;
		lz4)       cmd="lz4" ;;
		zstandard) cmd="zstd" ;;
		*)
			echo "Unsupported compression method: ${compress}" >&2
			exit 1
			;;
	esac

	# Create initrd
	( cd "${in}" && find . | cpio -H newc -o | "${cmd}" -c > "${out}" )
    echo "Created initrd: ${out}"

else
	# Compression method
	compress=$(file "${in}")
	compress=${compress%% compressed data*}
	compress=${compress##*: }
	case "${compress,,}" in
		gzip)      cmd="zcat" ;;
		lz4)       cmd="lz4cat" ;;
		zstandard) cmd="zstdcat" ;;
		*)
			echo "Unsupported compression method: ${compress}" >&2
			exit 1
			;;
	esac

	# Extract initrd
	mkdir -p "${out}"
	( cd "${out}" && "${cmd}" "${in}" | cpio --extract )
	echo "Extracted initrd: ${out}"
fi
