#!/bin/bash -eu
#
# Install Raspberry Pi kernel packages
#

dpkg -i "${@}"

release=
version=
for deb in "${@}" ; do
	deb=${deb##*/}
	case "${deb}" in
		linux-image-*)
			release=${deb#linux-image-}
			release=${release%%_*}
			version=${deb##*-1+}
			version=${version%%+*}
			break
			;;
	esac
done

if [ -z "${release}" ] || [ -z "${version}" ] ; then
	exit
fi

vmlinuz=/boot/vmlinuz-"${release}"
initrd=/boot/initrd.img-"${release}"

if [ -d /boot/firmware ] ; then
	boot_dir=/boot/firmware
else
	boot_dir=/boot
fi

if [ -e "${boot_dir}"/vmlinuz ] ; then
	echo "-- Copy kernel to ${boot_dir}/vmlinuz"
	cp "${vmlinuz}" "${boot_dir}"/vmlinuz

	echo "-- Copy initrd to ${boot_dir}/initrd.img"
	cp "${initrd}" "${boot_dir}"/initrd.img
else
	if [ "${version}" = "v6" ] ; then
		version=
	fi
	echo "-- Copy kernel to ${boot_dir}/kernel${version#v}.img"
	cp "${vmlinuz}" "${boot_dir}"/kernel"${version#v}".img
fi

if [ -d /lib/firmware/"${release}"/device-tree ] ; then
	dtb_dir=/lib/firmware/${release}/device-tree
elif [ -d /usr/lib/linux-image-"${release}" ] ; then
	dtb_dir=/usr/lib/linux-image-${release}
else
	echo "-- Failed to find DTB directory" >&2
	exit 1
fi

echo "-- Copy DTBs to ${boot_dir}/"
find "${dtb_dir}" -name '*.dtb' -print0 | \
	xargs -0 -I{} cp '{}' "${boot_dir}"/

echo "-- Copy DTB overlays to ${boot_dir}/overlays/"
find "${dtb_dir}" -name '*.dtbo' -print0 | \
	xargs -0 -I{} cp '{}' "${boot_dir}"/overlays/

if [ -e "${boot_dir}"/overlay_map.dtb ] ; then
	mv "${boot_dir}"/overlay_map.dtb "${boot_dir}"/overlays/
fi
