#!/bin/sh -u
#
# Download and install a Raspberry Pi image
#

echo "--- Running installer"

echo "--- Waiting for /dev/mmcblk0"
for i in $(seq 10) ; do
	[ -b /dev/mmcblk0 ] && break
    sleep .5
done

echo "--- Waiting for network device"
for i in $(seq 10) ; do
	[ -e /sys/class/net/eth0 ] && break
	[ -e /sys/class/net/wlan0 ] && break
	sleep .5
done

# Get an IP
dhclient

# The location of the images
images_url=192.168.99.11/images

while true ; do
	cat <<__EOF__

--- Select an image to install:
      1) Focal  - arm64
      2) Focal  - armhf
      3) Bionic - arm64
      4) Bionic - armhf

     10) Core20 - arm64
     11) Core20 - armhf
     12) Core18 - arm64
     13) Core18 - armhf

     20) Raspberry Pi OS (Buster) - arm64
     21) Raspberry Pi OS (Buster) - armhf
     22) Raspberry Pi OS (Buster) Lite - armhf
     23) Raspberry Pi OS (Buster) Full - armhf

     90) Run a shell
     91) Enter an image name manually
     92) Update the installer
     99) Reboot

__EOF__

	# shellcheck disable=SC2039
	echo -n "--- Choice: "
	read -r tmp

	case "${tmp}" in
		#
		# Ubuntu Server
		#
		1)
			image=focal-preinstalled-server-arm64+raspi+prep.img.gz
			;;
		2)
			image=focal-preinstalled-server-armhf+raspi+prep.img.gz
			;;
		3)
			image=bionic-preinstalled-server-arm64+raspi3+prep.img.gz
			;;
		4)
			image=bionic-preinstalled-server-armhf+raspi3+prep.img.gz
			;;

		#
		# Ubuntu Core
		#
		10)
			image=ubuntu-core-20-arm64+raspi+prep.img.gz
			;;
		11)
			image=ubuntu-core-20-armhf+raspi+prep.img.gz
			;;
		12)
			image=ubuntu-core-18-arm64+raspi+prep.img.gz
			;;
		13)
			image=ubuntu-core-18-armhf+raspi+prep.img.gz
			;;

		#
		# Raspberry Pi OS
		#
		20)
			image=raspios-buster-arm64+prep.img.gz
			;;
		21)
			image=raspios-buster-armhf+prep.img.gz
			;;
		22)
			image=raspios-buster-lite-armhf+prep.img.gz
			;;
		23)
			image=raspios-buster-full-armhf+prep.img.gz
			;;

		#
		# Misc options
		#
		90)
			/bin/sh
			continue
			;;
		91)
			# shellcheck disable=SC2039
			echo -n "--- Image name: "
			read -r image
			;;
		92)
			if mount /dev/mmcblk0p1 /boot ; then
				wget -O - "${images_url}"/rpi-installer.tgz | \
					( cd /boot && tar --no-same-owner -xzvf - )
				sync
				umount /boot
			fi
			continue
			;;
		99)
			sync
			reboot -f
			continue
			;;

		#
		# Default
		#
		*)
			continue
			;;
	esac

	echo "--- Installing ${image}"
	if wget -O - "${images_url}"/"${image}" | gunzip -c > /dev/mmcblk0 ; then
		sync
		reboot -f
	fi
done
