#!/usr/bin/env python3
#
# GTK VNC Widget
#
# Copyright (C) 2018  Juerg Haefliger <juergh@gmail.com>
# Copyright (C) 2006  Anthony Liguori <anthony@codemonkey.ws>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.0 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

import argparse
import os
import signal
import sys
import time

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('GtkVnc', '2.0')

from gi.repository import Gtk
from gi.repository import Gdk
from gi.repository import GLib
from gi.repository import GtkVnc

from lib.amt.power import AMTPower


class StatusIcon(Gtk.Image):
    def __init__(self):
        super(StatusIcon, self).__init__()

        self.pixbuf = {}
        for status in ("blue", "green", "red", "yellow"):
            tmp = Gtk.Image()
            tmp.set_from_file("icons/" + status + ".png")
            self.pixbuf[status] = tmp.get_pixbuf().scale_simple(20, 20, 2)

    def set_status(self, status):
        self.set_from_pixbuf(self.pixbuf[status])


class VNCViewer(object):
    def __init__(self, host, port, password="", auto_reconnect=False,
                 system=None):
        self.host = host
        self.port = port
        self.password = password
        self.auto_reconnect = auto_reconnect
        self.system = system

        self.manual_disconnect = False
        self.connected = False

        # Status icons
        self.connection_status = StatusIcon()
        self.connection_status.set_status("blue")

        # Menubar
        menubar = self._menubar(system)

        # VNC display
        self.vncdisplay = GtkVnc.Display()
        self.vncbox = Gtk.VBox()
        self.vncbox.set_size_request(720, 400)
        self.vncbox.add(self.vncdisplay)

        # Status bar
        statusbar = Gtk.HBox()
        statusbar.pack_start(Gtk.Label("Connection:"), False, False, 10)
        statusbar.pack_start(self.connection_status, False, False, 10)

        # Layout
        layout = Gtk.VBox()
        layout.pack_start(menubar, False, False, 0)
        layout.pack_start(self.vncbox, True, True, 0)
        layout.pack_end(statusbar, False, False, 0)

        # Window
        self.window = Gtk.Window(title="jvncviewer - %s" % host)
        self.window.add(layout)
        self.window.connect("destroy", self.quit)
        self.window.show_all()

    def _menubar(self, system):
        #
        # 'File' menu
        #
        file_quit = Gtk.MenuItem("Quit")
        file_quit.connect("activate", self.quit)

        menu_file = Gtk.Menu()
        menu_file.append(file_quit)

        menuitem_file = Gtk.MenuItem("File")
        menuitem_file.set_submenu(menu_file)

        #
        # 'Send Key' menu
        #
        sendkey_cad = Gtk.MenuItem("Control-Alt-Delete")
        sendkey_cad.connect("activate", self._send_cad)

        menu_sendkey = Gtk.Menu()
        menu_sendkey.append(sendkey_cad)

        menuitem_sendkey = Gtk.MenuItem("Send Key")
        menuitem_sendkey.set_submenu(menu_sendkey)

        #
        # 'System' menu
        #
        if system:
            system_pon = Gtk.MenuItem("Power On")
            system_pon.connect("activate", self._system_pon)
            system_poff = Gtk.MenuItem("Power Off")
            system_poff.connect("activate", self._system_poff)
            system_pcycle = Gtk.MenuItem("Power Cycle")
            system_pcycle.connect("activate", self._system_pcycle)
            system_reset = Gtk.MenuItem("Reset")
            system_reset.connect("activate", self._system_reset)

            menu_system = Gtk.Menu()
            menu_system.append(system_pon)
            menu_system.append(system_poff)
            menu_system.append(system_pcycle)
            menu_system.append(system_reset)

            menuitem_system = Gtk.MenuItem("System")
            menuitem_system.set_submenu(menu_system)

        #
        # Menubar
        #
        menubar = Gtk.MenuBar()
        menubar.append(menuitem_file)
        menubar.append(menuitem_sendkey)
        if system:
            menubar.append(menuitem_system)

        return menubar

    # -------------------------------------------------------------------------
    # VNC/GTK signal handlers

    def _auth_credential(self, _src, _credList):   # pylint: disable=no-self-use
        print("--- Server requires authentication")
        Gtk.main_quit()

    def _auth_failure(self, _src, msg):   # pylint: disable=no-self-use
        print("--- Authentication failure (%s)" % msg.strip())
        Gtk.main_quit()

    def _connected(self, _src):
        print("--- Connected to server")
        self.connected = True
        self.connection_status.set_status("green")

    def _disconnected(self, _src):
        print("--- Disconnected from server")
        self.connected = False
        self.connection_status.set_status("red")

        if self.manual_disconnect:
            pass
        elif self.auto_reconnect:
            time.sleep(0.5)
            self.connect()
        else:
            Gtk.main_quit()

    def _error(self, _src, msg):   # pylint: disable=no-self-use
        print("--- Error (%s)" % msg)

    def _initialized(self, _src):   # pylint: disable=no-self-use
        print("--- Connection initialized")

    def _size_allocate(self, _src, _rect):
        print("--- Size allocation")
        # HACK: Shrink the window so that is resizes automatically to the
        # size that the VNC display requests.
        self.window.resize(10, 10)

    # -------------------------------------------------------------------------
    # 'Send Key' menu signal handlers

    def _send_cad(self, _src):
        print("--- Send Control-Alt-Delete")
        self.vncdisplay.send_keys([Gdk.KEY_Control_L, Gdk.KEY_Alt_L,
                                   Gdk.KEY_Delete])

    # -------------------------------------------------------------------------
    # 'System' menu signal handlers

    def _system_pon(self, _src):
        print("--- Powering on system")
        self.system.set_power_state("on")

    def _system_poff(self, _src):
        print("--- Powering off system")
        self.disconnect()
        self.system.set_power_state("off")
        self.connect()

    def _system_pcycle(self, _src):
        print("--- Power cycling system")
        self.disconnect()
        self.system.set_power_state("cycle")
        self.connect()

    def _system_reset(self, _src):
        print("--- Resetting system")
        self.system.set_power_state("reset")

    # -------------------------------------------------------------------------
    # Public methods

    def connect(self):
        print("--- Connecting to %s:%s" % (self.host, self.port))
        self.manual_disconnect = False

        # Remove the previous VNC display from the window layout (in case of a
        # reconnect)
        self.vncbox.remove(self.vncdisplay)

        # Create the VNC display and add it to the window layout
        self.vncdisplay = GtkVnc.Display()
        self.vncbox.add(self.vncdisplay)
        self.vncdisplay.show()

        if self.password != "":
            self.vncdisplay.set_credential(GtkVnc.DisplayCredential.CLIENTNAME,
                                           "jvncviewer")
            self.vncdisplay.set_credential(GtkVnc.DisplayCredential.PASSWORD,
                                           self.password)

        self.vncdisplay.realize()

        self.vncdisplay.connect("size-allocate", self._size_allocate)
        self.vncdisplay.connect("vnc-auth-credential", self._auth_credential)
        self.vncdisplay.connect("vnc-auth-failure", self._auth_failure)
        self.vncdisplay.connect("vnc-connected", self._connected)
        self.vncdisplay.connect("vnc-disconnected", self._disconnected)
        self.vncdisplay.connect("vnc-error", self._error)
        self.vncdisplay.connect("vnc-initialized", self._initialized)

        self.vncdisplay.open_host(host, port)

    def disconnect(self):
        print("--- Disconnecting from %s:%s" % (self.host, self.port))
        self.manual_disconnect = True

        self.vncdisplay.close()

        # Wait for the connection to close
        while self.connected:
            while Gtk.events_pending():
                Gtk.main_iteration()

    def quit(self, _src=None):   # pylint: disable=no-self-use
        print("--- Quitting")
        Gtk.main_quit()

# -----------------------------------------------------------------------------
# Main entry point

if __name__ == "__main__":

    desc = """
jvncviewer is a simple GTK VNC viewer.

The hostname and password (if necessary) need to be supplied via the
commandline or, alternatively, with environment variables VNC_HOST and
VNC_PASSWORD.
"""
    parser = argparse.ArgumentParser(description=desc, formatter_class=
                                     argparse.RawDescriptionHelpFormatter)
    parser.add_argument("host", metavar="host[:port]", nargs='?',
                        default=os.getenv("VNC_HOST", ""),
                        help="VNC host and (optional) port number. If not "
                        "specified, port defaults to 5900.")
    parser.add_argument("password", nargs='?',
                        default=os.getenv("VNC_PASSWORD", ""),
                        help="VNC password.")
    args = parser.parse_args()

    if args.host == "":
        parser.print_help()
        sys.exit(2)

    comps = args.host.split(':')
    host = comps[0]
    if len(comps) > 1:
        port = comps[1]
    else:
        port = "5900"

    amt = AMTPower(host, "admin", args.password)
    vnc = VNCViewer(host, port, args.password, auto_reconnect=True, system=amt)

    vnc.connect()

    # Allow CTRL-C to quit the GTK main loop
    GLib.unix_signal_add(GLib.PRIORITY_DEFAULT, signal.SIGINT, vnc.quit)
    Gtk.main()
