#!/usr/bin/env python3
#
# Print a module dependency tree
#

import subprocess
import sys

MODULES = {}


def depends(mod):
    try:
        for line in subprocess.check_output(["modinfo", mod], text=True).split("\n"):
            if line.startswith("depends:"):
                depends = line[8:].strip()
                return depends.split(",") if depends else []
        return []
    except subprocess.CalledProcessError:
        return None


def list_depends(mod, level=0):
    deps = depends(mod)
    if deps is None:
        return

    yield mod, level

    if mod not in MODULES:
        MODULES[mod] = 1
        for dep in deps:
            yield from list_depends(dep, level=level+1)


module = sys.argv[1]

for mod, level in list_depends(module):
    print(f"{' ' * level * 2}{mod}")
