#!/bin/bash
#
# Custom filter for lesspipe and lessfile
# See 'man lesspipe' for more information
#
# Copy to ~/.lessfilter
#

CYAN="\o33[36m"
NC="\o33[0m"

case "${1}" in
	*.yaml)
		sed -E "s/(#.*)/${CYAN}\1${NC}/" "${1}"  # color comments
		exit 0
		;;

	# Handled by lesspipe/lessfilter
	*.a|\
	*.arj|\
	*.tar.bz2|\
	*.bz|\
	*.bz2|\
	*.deb|*.udeb|*.ddeb|\
	*.doc|\
	*.egg|\
	*.gif|*.jpeg|*.jpg|*.pcd|*.png|*.tga|*.tiff|*.tif|\
	*.iso|*.raw|*.bin|\
	*.lha|*.lzh|\
	*.tar.lz|*.tlz|\
	*.lz|\
	*.7z|\
	*.pdf|\
	*.rar|*.r[0-9][0-9]|\
	*.rpm|\
	*.tar.gz|*.tgz|*.tar.z|*.tar.dz|\
	*.gz|*.z|*.dz|\
	*.tar|\
	*.tar.xz|*.xz|\
	*.whl|\
	*.jar|*.war|*.xpi|*.zip|\
	*.zoo|\
	*.tar.zst|*.tzst|\
	*.zst)
		true
		;;

	*.mk|*Kbuild)
		# Derived from /usr/share/source-highlight/src-hilite-lesspipe.sh
		source-highlight --failsafe -f esc --lang-def=makefile.lang --style-file=esc.style -i "${1}"
		exit 0
		;;

	*.debdiff)
		# Derived from /usr/share/source-highlight/src-hilite-lesspipe.sh
		source-highlight --failsafe -f esc --lang-def=diff.lang --style-file=esc.style -i "${1}"
		exit 0
		;;

	# The rest is assumed to be source code
	*)
		if [ -x /usr/share/source-highlight/src-hilite-lesspipe.sh ] ; then
			/usr/share/source-highlight/src-hilite-lesspipe.sh "${1}"
			exit 0
		fi
		;;
esac

# Pass on to lesspipe/lessfilter
exit 1
