#!/bin/bash -eu
#
# Run linting tools on scripts
#

function usage()
{
	cat <<EOF
Usage: lint-any [-h] [-d ID] FILE [FILE...]

Run the relevant linting tools (shellcheck, flake8, pylint) on the provided
files.

Optional arguments:
  -d, --disable ID  Disable the checker with the given id. Can be a comma-
                    separated list.
  -h, --help        Show this help text.
EOF
}

shellcheck_exclude="--exclude=SC1117"
flake_ignore="--ignore=E501,E302,E305,E402,W504"
pylint_disable="--disable=C0301,W0311,E0401,C1801,R0912,C0326,R0903,C0330,W0621,C0103,C0114,C0115,C0116,C0209"

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-d|--disable)
			shift
			while IFS= read -r id ; do
				if [ "${id#SC}" != "${id}" ] ; then
					shellcheck_exclude="${shellcheck_exclude},${id}"
				elif [ "${#id}" -eq 4 ] ; then
					flake_ignore="${flake_ignore},${id}"
				else
					pylint_disable="${pylint_disable},${id}"
				fi
			done < <(echo "${1}" | tr ',' '\n')
			;;
		-h|--help)
			usage
			exit
			;;
		*)
			break
			;;
	esac
	shift
done

if [ ${#} -eq 0 ] ; then
   usage
   exit 1
fi

shell_scripts=()
python_scripts=()

# Determine the script types of the provided files
for f in "${@}" ; do
	if ! [ -e "${f}" ] ; then
		echo "No such file: ${1}" >&2
		exit 1
	fi
	if file "${f}" | grep -iq 'shell script' ; then
		shell_scripts+=("${f}")
	elif file "${f}" | grep -iq 'python script' ; then
		python_scripts+=("${f}")
	else
		echo "Unknown file type: ${f}" >&2
		exit 1
	fi
done

if [ ${#shell_scripts[@]} -gt 0 ] ; then
	echo "-- Running shellcheck"
	shellcheck --external-sources "${shellcheck_exclude}" "${shell_scripts[@]}" || true
fi

if [ ${#python_scripts[@]} -gt 0 ] ; then
	echo "-- Running flake8"
	flake8 "${flake_ignore}" "${python_scripts[@]}" || true

	echo "-- Running pylint"
	pylint "${pylint_disable}" "${python_scripts[@]}" || true
fi
