#!/bin/bash
#
# List unreleased commits on linux-firmware branches
#

git fetch origin

while IFS= read -r branch ; do
	echo "-- $branch"
	if ! git rev-parse "${branch}" &>/dev/null ; then
		echo "Branch does not exist"
		echo
		continue
	fi

	version=$(git show "${branch}":debian/changelog | \
	          dpkg-parsechangelog -l- -Sversion)
	if [ "${version%.0}" != "${version}" ] ; then
		# Dummy initial SRU release version, pull the next one
		version=$(git show "${branch}":debian/changelog | \
		          dpkg-parsechangelog -l- -Sversion -o1 -c1)
	fi
	tag=Ubuntu-${version}

	git --no-pager log --oneline "${tag}".."${branch}"
	git --no-pager log --oneline "${branch}"..origin/"${branch}"
	echo
done < <(
	{
		ubuntu-distro-info --supported-esm
		ubuntu-distro-info --supported
		ubuntu-distro-info --devel
	} | sort -u
)
