#!/bin/bash
#
# Search the given directory for modules that want to load firmware
#

FW_SYMBOLS=(
	firmware_request_builtin
	firmware_request_cache
	firmware_request_nowarn
	firmware_request_platform
	firmware_upload_register
	firmware_upload_unregister
	fw_fallback_config
	register_firmware_config_sysctl
	release_firmware
	request_firmware
	request_firmware_direct
	request_firmware_into_buf
	request_firmware_nowait
	request_partial_firmware_into_buf
	unregister_firmware_config_sysctl
)

function check_module()
{
	local mod=${1}
	local m symbols

	m=${mod##*/kernel/}
	m=${m%.ko*}.ko

	# Check if the module declares firmware
	modinfo -F firmware "${mod}" > "${TMPFILE}"
	if [ -s "${TMPFILE}" ] ; then
		echo "M: ${m}"
		if [ -n "${FWINFO}" ] ; then
			cat "${TMPFILE}" >> "${FWINFO}"
		fi
		return
	fi

	# Decompress the module
	case "${mod}" in
		*.ko.zst) zstd -d -q -f -o "${TMPFILE}" "${mod}" ;;
		*)        cat "${mod}" > "${TMPFILE}" ;;
	esac

	# Check if the module uses firmware load symbols
	symbols=$(nm -P "${TMPFILE}" | grep -oE "^(${re_symbol}) " | tr " " "," | tr -d "\n")
	if [ -n "${symbols}" ] ; then
		if [ "${VERBOSE}" -eq 1 ] ; then
			echo "S: ${m} (${symbols::-1})"
		else
			echo "S: ${m}"
		fi
	fi
}

function usage()
{
	cat <<EOF
Usage: find-modules-with-firmware [-f FWINFO] [-h] [-v] [DIR [DIR..] | MOD [MOD..]]

Search the provided directories for modules that want to load firmware or process the
provided module files.

Output prefix:
  M:  Module declares firmware (via modinfo).
  S:  Module uses firmware load symbols.

Optional arguments:
  -f, --fwinfo FWINFO  Write firmware info to the file FWINFO.
  -h, --help           Show this help message and exit.
EOF
}

FWINFO=
VERBOSE=0

while [ $# -gt 0 ] ; do
	case "${1}" in
		-f|--fwinfo)
			shift
			FWINFO=${1}
			;;
		-h|--help)
			usage
			exit
			;;
		-v|--verbose)
			VERBOSE=1
			;;
		*)
			if ! [ -e "${1}" ] ; then
				usage
				exit 2
			fi
			break
			;;
	esac
	shift
done

#readarray -t FW_SYMBOLS < <(git grep -h EXPORT_SYMBOL drivers/base/firmware_loader/ | \
#                            sed 's/.*(//;s/.)*//;s/,*//' | sort -u)

re_symbol=$(printf "|%s" "${FW_SYMBOLS[@]}")
re_symbol=${re_symbol:1}

TMPFILE=$(mktemp)

if [ -n "${FWINFO}" ] ; then
	true > "${FWINFO}"
fi

if [ $# -eq 0 ] || [ -d "${1}" ] ; then
	while IFS= read -r mod ; do
		check_module "${mod}"
	done < <(find "${@}" -name '*.ko*')
else
	for mod in "${@}" ; do
		check_module "${mod}"
	done
fi

if [ -n "${FWINFO}" ] ; then
	sort -u "${FWINFO}" > "${TMPFILE}"
	mv "${TMPFILE}" "${FWINFO}"
fi

rm -f "${TMPFILE}"
