#!/usr/bin/env python3
#
# LP bug management
#

import os
import re
import sys

import click
from launchpadlib.launchpad import Launchpad

RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
NC = "\033[00m"

STATUS_OPEN = ("New",
               "Incomplete",
               "Confirmed",
               "Triaged",
               "In Progress",
               "Fix Committed")


def show(item):
    print(item)
    print("attributes:  {}".format(sorted(item.lp_attributes)))
    print("collections: {}".format(sorted(item.lp_collections)))
    print("entries:     {}".format(sorted(item.lp_entries)))
    print("operations:  {}".format(sorted(item.lp_operations)))

    for a in item.lp_attributes:
        print(f"  {a} = {getattr(item, a)}")


def is_kernel_target(name):
    if name.startswith("linux"):
        return True
    return False


def bug_targets(lp_bug):
    """Return the list of targets"""
    targets = {}
    for task in lp_bug.bug_tasks:
        target = task.target.name
        if target not in targets:
            targets[target] = []
        targets[target].append(task)
    return list(targets.values())


def bug_task_details(lp_task):
    """Return relevant bug task details"""
    task_status = lp_task.status
    lp_target = lp_task.target
    target_name = lp_target.name
    try:
        target_series_name = lp_target.distroseries.name
    except AttributeError:
        target_series_name = "None"
    return target_name, target_series_name, task_status


def print_task(bug=None, target=None, series=None, status=None, title=None, color=NC):
    if bug:
        print(f"{color}LP: #{bug:<7} - {target:<22} -- {series.title():<8} -- {status:<13} - {title}{NC}")
    else:
        print(" " * 41 + f"{color}{series.title():<8} -- {status}{NC}")


def lp_login():
    return Launchpad.login_with("tools", "production", version="devel")


def mark_as_duplicate(master, bug, dry_run=False):
    pre_comment = \
        "Thank you for taking the time to report this bug and helping to make Ubuntu better. " + \
        f"This particular bug has already been reported and is a duplicate of bug {master}, " + \
        "so it is being marked as such. "
    post_comment = " Please continue to report any other bugs you may find."

    if master == 2068107:
        comment = \
            "The problem you're encountering is due to the presence of an unsupported DKMS " + \
            "module that causes the installation or upgrade of kernel packages to fail. You " + \
            "need to remove this unsupported DKMS module. Please look at the other bug " + \
            "report for instructions and additional information."
    else:
        comment = \
            "Please look at the other bug report to see if there is any missing information " + \
            "that you can provide, or to see if there is a workaround for the bug. " + \
            "Additionally, any further discussion regarding the bug should occur in the " + \
            "other report."

    lp = lp_login()
    lp_master = lp.bugs[master]
    lp_bug = lp.bugs[bug]

    comment = pre_comment + comment + post_comment

    print(f"LP: #{bug} -- {lp_bug.title}")
    print()
    print(comment)
    print()

    if dry_run:
        print("(dry-run) Exiting, not modifying bug")
        return

    # Copy release tags from duplicates to the master bug
    ubuntu = lp.distributions["ubuntu"]
    release_tags = []
    for series in ubuntu.series:
        if series.status not in ("Active Development", "Current Stable Release", "Supported"):
            continue
        release_tags.append(series.name)
    dupe_tags = set(lp_bug.tags)
    master_tags = lp_master.tags
    missing_tags = dupe_tags.difference(master_tags)
    for tag in missing_tags:
        if tag in release_tags:
            master_tags.append(tag)
    lp_master.lp_save()

    for task in lp_bug.bug_tasks:
        task.status = "Confirmed"
        task.lp_save()
    lp_bug.newMessage(content=comment)
    lp_bug.duplicate_of = lp_master
    lp_bug.lp_save()
    print("Modified bug")


def wontfix(reason, bug, series_or_kernel=None, dry_run=False):
    """Close a bug as \"Won't Fix\"."""
    if reason == "esm":
        comment = \
            "The release that is affected by this bug is now under ESM. The bug will " + \
            "not be fixed as it doesn't meet ESM fix criterias. Please file a new bug if you " + \
            "think this is incorrect."

    elif reason == "no-response":
        comment = \
            "We have not received any response from the bug reporter or there hasn't been " + \
            "any activity recently. This bug report will therefore be closed. Please file a " + \
            "new bug if this issue still exists in a supported release."

    else:
        print(f"Unsupported reason: {reason}", file=sys.stderr)
        sys.exit(1)

    lp = lp_login()
    lp_bug = lp.bugs[bug]

    wontfix_bug = False
    source = None
    for task in lp_bug.bug_tasks:
        status = task.status
        target = task.target
        target_name = target.name

        if target_name.startswith("linux") and status in ("New", "Incomplete", "Confirmed",
                                                          "Triaged", "In Progress", "Fix Committed"):
            wontfix_bug = True
            wontfix_task = True
            color = YELLOW
        else:
            wontfix_task = False
            color = NC

        if target_name != source:
            source = target_name
            print(f"{color}LP: #{bug:<7} - {target_name:<14} - {status:<13} - {lp_bug.title}{NC}")
        else:
            try:
                print(f"{color}               {target.distroseries.name.title():<14} - {status}{NC}")
            except AttributeError:
                pass

        if wontfix_task and not dry_run:
            try:
                task.status = "Won't Fix"
                task.lp_save()
            except Exception:
                print("Failed to set task status", file=sys.stderr)

    if wontfix_bug:
        print()
        print("Comment to be added:")
        print(comment)
        print()
        if dry_run:
            print("Bug was *NOT* modified (dry run)")
        else:
            lp_bug.newMessage(content=comment)
            lp_bug.lp_save()
            print("Bug was modified")
    else:
        print("Bug was *NOT* modified (nothing to do)")


def no_logs(bug, dry_run=False):
    lp = lp_login()
    lp_bug = lp.bugs[bug]

    print(f"LP: #{bug} -- {lp_bug.title}")

    if "apport-package" in lp_bug.tags:
        print("Bug contains 'apport-package tag")
        return

    comment = \
        "Thank you for reporting this and helping make Ubuntu better. This bug report is " + \
        "missing kernel log files. Please boot into the Ubuntu kernel and run the following " + \
        "command in a terminal, which will collect debugging information and attach it to " + \
        "this bug report:\n\n" + \
        f"$ sudo apport-collect {bug}"

    print()
    print(comment)
    print()

    if dry_run:
        print("(dry-run) Exiting, not modifying bug")
        return

    lp_bug.newMessage(content=comment)
    lp_bug.lp_save()
    print("Modified bug")



def test_proposed(bug, dry_run=False):
    lp = lp_login()
    lp_bug = lp.bugs[bug]

    print(f"LP: #{bug} -- {lp_bug.title}")

    comment = \
        "Can you please test the latest kernel [1] in combination with the latest linux-firmware [2] from -proposed [3]?\n" + \
        "Please let us know if you still encounter the problem using these updated packages and attach kernel logs.\n\n" + \
        "[1] https://launchpad.net/ubuntu/+source/linux\n" + \
        "[2] https://launchpad.net/ubuntu/+source/linux-firmware\n" + \
        "[3] https://wiki.ubuntu.com/Testing/EnableProposed"

    print()
    print(comment)
    print()

    if dry_run:
        print("(dry-run) Exiting, not modifying bug")
        return

    lp_bug.newMessage(content=comment)
    lp_bug.lp_save()
    print("Modified bug")


def _list_open_tasks(series, dry_run=False):
    lp = lp_login()
    lp_distro = lp.distributions["ubuntu"]
    lp_series = lp_distro.getSeries(name_or_version=series)
    for task in lp_series.searchTasks(status=STATUS_OPEN, omit_duplicates=True):
        if not is_kernel_target(task.target.name):
            continue
#        if task.bug.title.startswith("CVE-20"):
#            continue
        lp_bug = task.bug
        print(f"{task.web_link:<90} -- LP: #{lp_bug.id:<7} -- {lp_bug.title}")


def _wontfix_eol_tasks(series, bug, dry_run=False):
    """Close a task as \"Won't Fix\"."""
    lp = lp_login()
    lp_bug = lp.bugs[bug]

    lp_distro = lp.distributions["ubuntu"]
    lp_series = lp_distro.getSeries(name_or_version=series)

    comment = \
        f"Ubuntu {lp_series.version} ({lp_series.title.lstrip('The ')} has reached end " + \
        "of life and this bug will not be fixed for that specific release. Please file " + \
        "a new bug if this issue still exists in a supported release."

    modified = False

    for target in bug_targets(lp_bug):
        first = True
        for lp_task in target:
            target_name, target_series_name, status = bug_task_details(lp_task)

            color = NC
            if is_kernel_target(target_name) and target_series_name == series and status in STATUS_OPEN:
                modified = True
                color = YELLOW

            if first:
                first = False
                print_task(bug=bug, target=target_name, series=target_series_name, status=status, title=lp_bug.title, color=color)
            else:
                print_task(series=target_series_name, status=status, color=color)

            if color != NC and not dry_run:
                try:
                    lp_task.status = "Won't Fix"
                    lp_task.lp_save()
                except Exception:
                    print("Failed to set task status", file=sys.stderr)

    if modified:
        print()
        print("Comment to be added:")
        print(comment)
        print()
        if dry_run:
            print("Bug was *NOT* modified (dry run)")
        else:
            lp_bug.newMessage(content=comment)
            lp_bug.lp_save()
            print("Bug was modified")
    else:
        print("Bug was *NOT* modified (nothing to do)")


def _wontfix_eol_bug(bug, series=None, dry_run=False):
    """Close all open tasks of a bug as \"Won't Fix\"."""
    lp = lp_login()
    lp_bug = lp.bugs[bug]

    if series:
        lp_distro = lp.distributions["ubuntu"]
        lp_series = lp_distro.getSeries(name_or_version=series)
        ubuntu_release = f"Ubuntu {lp_series.version} ({lp_series.title.removeprefix('The ')}"
    else:
        ubuntu_release = "The Ubuntu release this bug has been reported for"

    comment = \
        f"{ubuntu_release} has reached end of life and this bug will not be fixed for that " + \
        "specific release. Please file a new bug if this issue still exists in a supported release."

    modified = False

    for target in bug_targets(lp_bug):
        first = True
        for lp_task in target:
            target_name, target_series_name, status = bug_task_details(lp_task)

            color = NC
            if status in STATUS_OPEN:
                modified = True
                color = YELLOW

            if first:
                first = False
                print_task(bug=bug, target=target_name, series=target_series_name, status=status, title=lp_bug.title, color=color)
            else:
                print_task(series=target_series_name, status=status, color=color)

            if color != NC and not dry_run:
                try:
                    lp_task.status = "Won't Fix"
                    lp_task.lp_save()
                except Exception:
                    print("Failed to set task status", file=sys.stderr)

    if modified:
        print()
        print("Comment to be added:")
        print(comment)
        print()
        if dry_run:
            print("Bug was *NOT* modified (dry run)")
        else:
            lp_bug.newMessage(content=comment)
            lp_bug.lp_save()
            print("Bug was modified")
    else:
        print("Bug was *NOT* modified (nothing to do)")


@click.group()
def main():
    pass


@main.command()
@click.argument("bug")
@click.option("--dry-run", is_flag=True)
def duplicate_dkms(bug, dry_run):
    """Mark a bug as a duplicate of LP: #2068107 (DKMS build failure)."""
    mark_as_duplicate(2068107, bug, dry_run=dry_run)


@main.command()
@click.argument("bug")
@click.option("--dry-run", is_flag=True)
def wontfix_esm(bug, dry_run):
    wontfix("esm", bug, dry_run=dry_run)


@main.command()
@click.argument("bug")
@click.option("--dry-run", is_flag=True)
def wontfix_no_response(bug, dry_run):
    wontfix("no-response", bug, dry_run=dry_run)


@main.command()
@click.argument("bug")
@click.option("--dry-run", is_flag=True)
def ask_for_logs(bug, dry_run):
    no_logs(bug, dry_run=dry_run)


@main.command()
@click.argument("bug")
@click.option("--dry-run", is_flag=True)
def ask_for_testing_proposed(bug, dry_run):
    test_proposed(bug, dry_run=dry_run)


@main.command()
@click.argument("series")
@click.option("--dry-run", is_flag=True)
def list_open_tasks(series, dry_run):
    _list_open_tasks(series, dry_run=dry_run)


@main.command()
@click.argument("series")
@click.argument("bug")
@click.option("--dry-run", is_flag=True)
def wontfix_eol_tasks(series, bug, dry_run):
    _wontfix_eol_tasks(series, bug, dry_run=dry_run)


@main.command()
@click.argument("bug")
@click.option("--series")
@click.option("--dry-run", is_flag=True)
def wontfix_eol_bug(bug, series, dry_run):
    """Close all open tasks of a bug as \"Won't Fix\"."""
    _wontfix_eol_bug(bug, series=series, dry_run=dry_run)


if __name__ == "__main__":
    main()
