#!/bin/bash
#
# Copy packages from one PPA to another
#

function usage()
{
        cat <<EOF
Usage: ${0##*/} [-b] [-f] [-h] [OPTS] SUITE PACKAGE FROM TO

Copy packages from one PPA to another.

Postional arguments:
  SUITE         Suite (noble, noble-proposed, ...)
  PACKAGE       Source package name
  FROM          Source PPA (ubuntu, user/ppa, juergh/ppa1, ...)
  TO            Destination PPA (user/ppa, juergh/ppa2, ...)

Optional arguments:
  -b, --binary  Copy binary packages.
  -f, --force   Do it.
  -h, --help    Show this help message and exit.
  --to-suite    Destination suite (noble, plucky, ...).

OPTS  Additional options passed to copy-package.


Examples:

  # Copy from PPA to PPA
  $ lp-copy-packages noble linux-raspi juergh/raspi dest/name

  # Copy from archive to PPA
  $ lp-copy-packages noble linux-raspi ubuntu dest/name
  $ lp-copy-packages noble-updates linux-raspi ubuntu dest/name
EOF
}

opts=()
force=0
suite=
package=
from=
to=

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-b|--binary)
			opts+=("-b")
			;;
		-f|--force)
			force=1
			;;
		-h|--help)
			usage
			exit
			;;
		-s|--suite)
			shift
			suite=${1}
			;;
		--to-suite)
			shift
			opts+=("--to-suite" "${1}")
			;;
		-*)
			opts+=("${1}")
			;;
		*)
			if [ -z "${suite}" ] ; then
				suite=${1}
			elif [ -z "${package}" ] ; then
				package=${1}
			elif [ -z "${from}" ] ; then
				from=${1}
			elif [ -z "${to}" ] ; then
				to=${1}
			else
				echo "Invalid argument: ${1}" >&2
				exit 2
			fi
	esac
	shift
done

if [ -z "${to}" ] ; then
	usage
	exit 2
fi

if [ ${force} -eq 1 ] ; then
	opts+=("--confirm-all")
else
	opts+=("--dry-run")
fi

case "${from}" in
	*/*)
		# PPA
		from=~${from%/*}/ubuntu/${from#*/}
		;;
esac

set -x
"${HOME}"/git/ubuntu/ubuntu-archive-tools/copy-package \
	--from="${from}" \
	--to="~${to%/*}/ubuntu/${to#*/}" \
	-s "${suite}" \
	"${opts[@]}" \
	"${package}"
