#!/usr/bin/env python3
#
# List open linux-firmware bugs for the given series
#

import argparse

from launchpadlib.launchpad import Launchpad

NC = "\033[00m"
GREEN = "\033[92m"
ORANGE = "\033[33m"

parser = argparse.ArgumentParser()
parser.add_argument("series", nargs="*", default=[])
args = parser.parse_args()

source = "linux-firmware"
status = [
    "New",
    "Incomplete",
    "Confirmed",
    "Triaged",
    "In Progress",
    "Fix Committed",
]

lp = Launchpad.login_with("tools", "production", version="devel")

lp_dist = lp.distributions["ubuntu"]
lp_source = lp_dist.getSourcePackage(name=source)

lp_tasks = lp_source.searchTasks(status=status, order_by="-datecreated")
for task in lp_tasks:
    bug = task.bug
    bug_status = None
    for bug_task in bug.bug_tasks:
        if bug_task.target.name != source:
            continue

        if not bug_status:
            bug_status = bug_task.status

            color = NC
            if bug_status == "Incomplete":
                last_activity = [a for a in bug.activity][-1]
                if last_activity.newvalue != "Incomplete":
                    color = ORANGE

            print()
            print(f"LP: #{bug.id:<7} - {color}{bug_status:<13}{NC} - {bug.title}")

        try:
            task_series_name = bug_task.target.distroseries.name
            if task_series_name in args.series or not args.series:
                print(f"    {task_series_name.title():<8} - {bug_task.status}")
        except AttributeError:
            pass
