#!/usr/bin/env python3
#
# Subscribe a person to an LP bug
#

import sys

from launchpadlib.launchpad import Launchpad

if len(sys.argv) != 3:
    print('Usage: lp-subscribe-bug <LP_ID> <LP_BUG>')
    sys.exit(2)
lp_id = sys.argv[1]
lp_bug = sys.argv[2]

lp = Launchpad.login_with('tools', 'production', version='devel')
person = lp.people[lp_id]
bug = lp.bugs[lp_bug]

bug.subscribe(person=person)
