#!/bin/bash -eu

# Colors
__CEE="\033[91m"
__CII="\033[96m"
__CNO="\033[0m"

# Print helpers
function prerror() { echo -e "${__CEE}EE: $*${__CNO}" >&2 ; }
function prinfo()  { echo -e "${__CII}II: $*${__CNO}" ; }

function lxc_image_exists()
{
	local name=${1}

	lxc image info "${name}" &>/dev/null
}

function flags_from_name()
{
	local name=${1}

	if [ "${name/--vm/}" != "${name}" ] ; then
		echo "--vm"
	fi
}

function lxc_remote_image()
{
	local name=${1}
	local series arch

	name=${name%--*}
	series=${name%-*}
	arch=${name#*-}

	if ubuntu-distro-info --all | grep -q "${series}" ; then
		echo "ubuntu-daily:${series}/${arch}"
		return
	fi

	if debian-distro-info --all | grep -q "${series}" ; then
		echo "images:debian/${series}"
		return
	fi

	prerror "Unsupported image name: ${name}"
	return 1
}

function lxc_image_copy()
{
	local name=${1}
	local image flags

	image=$(lxc_remote_image "${name}")

	prinfo "Copy image: ${image} -> ${name}"

	readarray -t flags < <(flags_from_name "${name}")
	lxc image copy "${image}" local: --alias "${name}" "${flags[@]}"
}

function lxc_exists()
{
	lxc info "${1}" &>/dev/null
}

function lxc_status()
{
	{
		lxc info "${1}" 2>/dev/null || echo "Status: NOTFOUND"
	} | sed -n 's/^Status: *//p'
}

function lxc_wait()
{
	local name=${1}

	prinfo "Wait for container"
	while true ; do
		case "$(lxc exec "${name}" -- systemctl is-system-running || true)" in
			running|degraded)
				return
				;;
		esac
		sleep 1
	done
}

function lxc_launch()
{
	local image_name=${1} name=${2}
	local gid uid flags

	prinfo "Launch container: ${name}"

	readarray -t flags < <(flags_from_name "${name}")
	lxc launch local:"${image_name}" "${name}" "${flags[@]}"
	lxc_wait "${name}"

	prinfo "Configure container"

	gname=$(id -gn)
	gid=$(id -g)
	uid=$(id -u)

	# Add group
	lxc_gid=$(lxc exec "${name}" -- id -g "${gname}" 2>/dev/null || true)
	if [ -z "${lxc_gid}" ] ; then
		lxc_gid=${gid}
		prinfo "Add group ${gname} (${lxc_gid})"
		lxc exec "${name}" -- groupadd --gid "${lxc_gid}" "${gname}"
	fi

	# Add user
	lxc_uid=$(lxc exec "${name}" -- id -u "${USER}" 2>/dev/null || true)
	if [ -z "${lxc_uid}" ] ; then
		lxc_uid=${uid}
		prinfo "Add user ${USER} (${lxc_uid})"
		lxc exec "${name}" -- useradd --gid "${lxc_gid}" --uid "${lxc_uid}" --home-dir /home/"${USER}" \
		    --no-create-home --shell /bin/bash "${USER}"
	fi

	# Stop the container (required for ID mapping to take effect)
	prinfo "Stop container"
	lxc stop "${name}"

	# Map group and user IDs
	cat <<EOF | lxc config set "${name}" raw.idmap -
gid ${gid} ${lxc_gid}
uid ${uid} ${lxc_uid}
EOF

	# Attach our home directory
	lxc config device add "${name}" home disk source="${HOME}" path=/home/"${USER}"

	# Start the container again
	prinfo "Start container"
	lxc start "${name}"
	lxc_wait "${name}"
}

function lxc_start()
{
	local name=${1}

	prinfo "Start container"
	lxc start "${name}"
	lxc_wait "${name}"
}

function usage()
{
	cat <<EOF
Usage: lxc-run [-h] [--root] [-v] [--vm] NAME [-- COMMAND [ARG]...]

Run the given command in an LXC container. Create the container first if it
doesn't exits.

Postional arguments:
  NAME              LXC container name. Must be in the form of SERIES or
                    SERIES-ARCH.
  COMMAND [ARG]...  Command to run. If not provided, defaults to 'bash'.

Optional argument:
  -h, --help        Show this help text and exit.
  --root            Run command as the root user.
  -v, --verbose     Enable verbose output.
  --vm              Run a VM instead of a container.
EOF
}

root=0
verbose=0
vm=0
name=
command=("bash")

while [ $# -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		--root)
			root=1
			;;
		-v|--verbose)
			verbose=1
			;;
		--vm)
			vm=1
			;;
		--)
			shift
			command=("${@}")
			break
			;;
		-*)
			prerror "Invalid argument: ${1}"
			exit 2
			;;
		*)
			if [ -n "${name}" ] ; then
				prerror "Invalid argument: ${1}"
				exit 2
			fi
			name=${1}
			;;
	esac
	shift
done

arch=
case "${name}" in
	"")
		usage >&2
		exit 2
		;;
	*-*)
		series=${name%-*}
		arch=${name#*-}
		;;
	*)
		series=${name}
		;;
esac
if [ -z "${arch}" ] ; then
	arch=$(dpkg-architecture -qDEB_HOST_ARCH)
fi

case "${series}" in
	unstable) series=sid ;;
esac

image_name=${series}-${arch}
name=${series}-${arch}

if [ ${vm} -eq 1 ] ; then
	image_name=${image_name}--vm
	name=${name}--vm
fi

if ! lxc_image_exists "${image_name}" ; then
	lxc_image_copy "${image_name}"
fi

status=$(lxc_status "${name}")
case "${status}" in
	NOTFOUND)
		lxc_launch "${image_name}" "${name}"
		;;
	STOPPED)
		lxc_start "${name}"
		;;
	RUNNING)
		;;
	*)
		prerror "Unexpected container status: ${status}"
		exit 1
		;;
esac

lxc_opts=(
	--cwd "$(pwd)"
	--env debian_chroot="lxc:${series}"
	--mode interactive
)

if [ ${root} -eq 0 ] ; then
	lxc_opts+=(
		--env HOME="${HOME}"
		--env USER="${USER}"
		--group "$(id -g)"
		--user "$(id -u)"
	)
fi

if [ ${verbose} -eq 1 ] ; then
	set -x
fi

lxc exec "${name}" "${lxc_opts[@]}" -- "${command[@]}"
