#!/bin/bash -eu

# Colors
__CEE="\033[91m"
__CII="\033[96m"
__CNO="\033[0m"

# Print helpers
function prerror() { echo -e "${__CEE}EE: $*${__CNO}" >&2 ; }
function prinfo()  { echo -e "${__CII}II: $*${__CNO}" ; }

function lxc_image_exists()
{
	local image=${1}

	lxc image info "${image}" &>/dev/null
}

function lxc_remote_image()
{
	local series=${1} arch=${2}

	if ubuntu-distro-info --all | grep -q "${series}" ; then
		echo "ubuntu-daily:${series}/${arch}"
		return
	fi

	if debian-distro-info --all | grep -q "${series}" ; then
		echo "images:debian/${series}"
		return
	fi

	prerror "Unsupported image series: ${series}"
	return 1
}

function lxc_image_copy()
{
	local image=${1} series=${2} arch=${3}
	local remote_image

	remote_image=$(lxc_remote_image "${series}" "${arch}")

	prinfo "Copy image: ${remote_image} -> ${image}"
	lxc image copy "${remote_image}" local: --alias "${image}"
}

function lxc_exists()
{
	lxc info "${1}" &>/dev/null
}

function lxc_status()
{
	{
		lxc info "${1}" 2>/dev/null || echo "Status: NOTFOUND"
	} | sed -n 's/^Status: *//p'
}

function lxc_wait()
{
	local name=${1}

	prinfo "Wait for container"
	while true ; do
		case "$(lxc exec "${name}" -- systemctl is-system-running || true)" in
			running|degraded)
				return
				;;
		esac
		sleep 1
	done
}

function lxc_launch()
{
	local name=${1} series=${2} arch=${3}
	local image gname gid uid lxc_gid lxc_uid

	image=${series}-${arch}
	if ! lxc_image_exists "${image}" ; then
		lxc_image_copy "${image}" "${series}" "${arch}"
	fi

	prinfo "Launch container: ${name}"

	lxc launch local:"${image}" "${name}"
	lxc_wait "${name}"

	prinfo "Configure container"

	gname=$(id -gn)
	gid=$(id -g)
	uid=$(id -u)

	# Add group
	lxc_gid=$(lxc exec "${name}" -- id -g "${gname}" 2>/dev/null || true)
	if [ -z "${lxc_gid}" ] ; then
		lxc_gid=${gid}
		prinfo "Add group ${gname} (${lxc_gid})"
		lxc exec "${name}" -- groupadd --gid "${lxc_gid}" "${gname}"
	fi

	# Add user
	lxc_uid=$(lxc exec "${name}" -- id -u "${USER}" 2>/dev/null || true)
	if [ -z "${lxc_uid}" ] ; then
		lxc_uid=${uid}
		prinfo "Add user ${USER} (${lxc_uid})"
		lxc exec "${name}" -- useradd --gid "${lxc_gid}" --uid "${lxc_uid}" --home-dir /home/"${USER}" \
		    --no-create-home --shell /bin/bash "${USER}"
	fi

	# Enable sudo
	prinfo "Enable sudo for user ${USER}"
	cat <<EOF | lxc exec "${name}" -- bash -
echo "${USER} ALL = NOPASSWD: ALL" > /etc/sudoers.d/"${USER}"
chmod 440 /etc/sudoers.d/"${USER}"
EOF

	# Stop the container (required for ID mapping to take effect)
	prinfo "Stop container"
	lxc stop "${name}"

	# Map group and user IDs
	cat <<EOF | lxc config set "${name}" raw.idmap -
gid ${gid} ${lxc_gid}
uid ${uid} ${lxc_uid}
EOF

	# Attach our home directory
	if [ ${ATTACH_HOME} -eq 1 ] ; then
		lxc config device add "${name}" home disk source="${HOME}" path=/home/"${USER}"
	fi

	# Start the container again
	prinfo "Start container"
	lxc start "${name}"
	lxc_wait "${name}"
}

function lxc_start()
{
	local name=${1}

	prinfo "Start container"
	lxc start "${name}"
	lxc_wait "${name}"
}

function usage()
{
	cat <<EOF
Usage: lxc-run [-h] [--root] [--series SERIES] [-v] [--vm] [NAME] [-- COMMAND [ARG]...]

Run the given command in an LXC container. Create the container first if it
doesn't exits.

Postional arguments:
  NAME              LXC container name (default: ${series}-${arch}).
  COMMAND [ARG]...  Command to run (default: /usr/bin/bash).

Optional argument:
  -h, --help        Show this help text and exit.
  --no-home         Don't attach the home directory to the container.
  --root            Run command as the root user.
  --series SERIES   OS series name (default: ${series}).
  -v, --verbose     Enable verbose output.
EOF
}

ATTACH_HOME=1

arch=$(dpkg-architecture -qDEB_HOST_ARCH)
root=0
series=$(lsb_release -s -c)
verbose=0

name=
command=("/usr/bin/bash")

while [ $# -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		--no-home)
			ATTACH_HOME=0
			;;
		--root)
			root=1
			;;
		--series)
			shift
			series=${1}
			;;
		-v|--verbose)
			verbose=1
			;;
		--)
			shift
			command=("${@}")
			break
			;;
		-*)
			prerror "Invalid argument: ${1}"
			exit 2
			;;
		*)
			if [ -n "${name}" ] ; then
				prerror "Invalid argument: ${1}"
				exit 2
			fi
			name=${1}
			;;
	esac
	shift
done

case "${series}" in
	unstable) series=sid ;;
esac

if [ -z "${name}" ] ; then
	name=${series}-${arch}
fi

status=$(lxc_status "${name}")
case "${status}" in
	NOTFOUND)
		lxc_launch "${name}" "${series}" "${arch}"
		;;
	STOPPED)
		lxc_start "${name}"
		;;
	RUNNING)
		;;
	*)
		prerror "Unexpected container status: ${status}"
		exit 1
		;;
esac

lxc_opts=(
	--cwd "$(pwd)"
	--env debian_chroot="lxc:${name}"
	--mode interactive
)

if [ ${root} -eq 0 ] ; then
	lxc_opts+=(
		--env HOME="${HOME}"
		--env USER="${USER}"
		--group "$(id -g)"
		--user "$(id -u)"
	)
fi

if [ ${verbose} -eq 1 ] ; then
	set -x
fi

lxc exec "${name}" "${lxc_opts[@]}" -- "${command[@]}"
