#!/bin/bash -eu

# Colors
__CEE="\033[91m"
__CII="\033[96m"
__CNO="\033[0m"

# Print helpers
function prerror() { echo -e "${__CEE}EE: $*${__CNO}" >&2 ; }
function prinfo()  { echo -e "${__CII}II: $*${__CNO}" ; }

function lxc_image_exists()
{
	lxc image info "${1}" &>/dev/null
}

function lxc_remote_image()
{
	local name=${1}
	local series arch

	series=${name%-*}
	arch=${name#*-}

	if ubuntu-distro-info --all | grep -q "${series}" ; then
		echo "ubuntu-daily:${series}/${arch}"
		return
	fi

	if debian-distro-info --all | grep -q "${series}" ; then
		echo "images:debian/${series}"
		return
	fi

	prerror "Unsupported image name: ${name}"
	return 1
}

function lxc_image_copy()
{
	local name=${1}
	local image

	image=$(lxc_remote_image "${name}")

	prinfo "Copy image: ${image} -> ${name}"

	lxc image copy --alias "${name}" "${image}" local:
}

function lxc_exists()
{
	lxc info "${1}" &>/dev/null
}

function lxc_status()
{
	{
		lxc info "${1}" 2>/dev/null || echo "Status: NOTFOUND"
	} | sed -n 's/^Status: *//p'
}

function lxc_wait()
{
	local name=${1}

	prinfo "Wait for container"
	while true ; do
		case "$(lxc exec "${name}" -- systemctl is-system-running || true)" in
			running|degraded)
				return
				;;
		esac
		sleep 1
	done
}

function lxc_launch()
{
	local image_name=${1} name=${2}
	local gid uid

	prinfo "Launch container: ${name}"
	lxc launch local:"${image_name}" "${name}"
	lxc_wait "${name}"

	prinfo "Configure container"

	gid=$(id -g)
	uid=$(id -u)

	# Attach our home directory
	lxc config device add "${name}" home disk source="${HOME}" path=/home/"${USER}"

	# Add ourselves as a new user
	lxc exec "${name}" -- groupadd --gid "${gid}" "$(id -gn)"
	lxc exec "${name}" -- useradd --gid "${gid}" --uid "${uid}" --home-dir /home/"${USER}" \
		--no-create-home --shell /bin/bash "${USER}"

	# Map user and group IDs
	if [ "${uid}" = "${gid}" ] ; then
		lxc config set "${name}" raw.idmap "both ${uid} ${uid}"
	else
		lxc config set "${name}" raw.idmap "gid ${gid} ${gid}"
		lxc config set "${name}" raw.idmap "uid ${uid} ${uid}"
	fi

	# Restart the container (required for the ID mapping to take effect)
	prinfo "Restart container"
	lxc restart "${name}"
	lxc_wait "${name}"
}

function lxc_start()
{
	local name=${1}

	prinfo "Start container"
	lxc start "${name}"
	lxc_wait "${name}"
}

function usage()
{
	cat <<EOF
Usage: lxc-run [-h] [--root] [-v] [NAME] [-- COMMAND [ARG]...]

Run the given command in an LXC container. Create the container first if it
doesn't exits.

Postional arguments:
  NAME              LXC container name. Must be in the form of SERIES or
                    SERIES-ARCH. If not provided, defaults to the running
                    release ($(lsb_release -s -c)).
  COMMAND [ARG]...  Command to run. If not provided, defaults to 'bash'.

Optional argument:
  -h, --help        Show this help text and exit.
  --root            Run command as the root user.
  -v, --verbose     Enable verbose output.
EOF
}

root=0
verbose=0
name=
command=("bash")

while [ $# -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		--root)
			root=1
			;;
		-v|--verbose)
			verbose=1
			;;
		--)
			shift
			command=("${@}")
			break
			;;
		-*)
			prerror "Invalid argument: ${1}"
			exit 2
			;;
		*)
			if [ -n "${name}" ] ; then
				prerror "Invalid argument: ${1}"
				exit 2
			fi
			name=${1}
			;;
	esac
	shift
done

arch=
case "${name}" in
	"")
		series=$(lsb_release -s -c)
		;;
	*-*)
		series=${name%-*}
		arch=${name#*-}
		;;
	*)
		series=${name}
		;;
esac
if [ -z "${arch}" ] ; then
	arch=$(dpkg-architecture -qDEB_HOST_ARCH)
fi

case "${series}" in
	unstable) series=sid ;;
esac

image_name=${series}-${arch}
name=${series}-${arch}

if ! lxc_image_exists "${image_name}" ; then
	lxc_image_copy "${image_name}"
fi

status=$(lxc_status "${name}")
case "${status}" in
	NOTFOUND)
		lxc_launch "${image_name}" "${name}"
		;;
	STOPPED)
		lxc_start "${name}"
		;;
	RUNNING)
		;;
	*)
		prerror "Unexpected container status: ${status}"
		exit 1
		;;
esac

lxc_opts=(
	--cwd "$(pwd)"
	--env debian_chroot="lxc:${name}"
	--mode interactive
)

if [ ${root} -eq 0 ] ; then
	lxc_opts+=(
		--env HOME="${HOME}"
		--env USER="${USER}"
		--group "$(id -g)"
		--user "$(id -u)"
	)
fi

if [ ${verbose} -eq 1 ] ; then
	set -x
fi

lxc exec "${name}" "${lxc_opts[@]}" -- "${command[@]}"
