#!/usr/bin/env python3

import glob
import os
import re

RE_DEF_IWL_API = re.compile(r"^#define\s+(IWL.*?_UCODE_API_.*?)\s+(\d+)")
RE_DEF_IWL_FW_PRE = re.compile(r'^#define\s+(IWL.*?)_FW_PRE\s+"(iwlwifi-.*?)"')
RE_DEF_IWL_MOD_FW = re.compile(r"^#define\s+(IWL.*?(_FW)?_MODULE_FIRMWARE)")
RE_MOD_FW_IWL = re_mf = re.compile(r"^MODULE_FIRMWARE\((IWL.*?)\((IWL.*?)\)\);")

def parse_iwlwifi_source(filename):
    iwl_api = {}
    iwl_pre = {}
    iwl_mfw = {}

    with open(filename, encoding="utf-8") as fh:
        for line in fh:
            m = RE_DEF_IWL_API.match(line)
            if m:
                name, val = m.groups()
                iwl_api[name] = int(val)
                continue
            m = RE_DEF_IWL_FW_PRE.match(line)
            if m:
                name, val = m.groups()
                iwl_pre[name] = val
                continue
            m = RE_DEF_IWL_MOD_FW.match(line)
            if m:
                name, _ = m.groups()
                key = name.removesuffix("_MODULE_FIRMWARE")
                key = key.removesuffix("_FW")
                iwl_mfw[name] = iwl_pre[key].rstrip("-") + "-XXX.ucode"
                continue
            m = RE_MOD_FW_IWL.match(line)
            if m:
                name, api = m.groups()
                api_max = iwl_api[api]
                api_min = iwl_api[api.replace("_MAX", "_MIN")]
                for api in range(api_min, api_max + 1):
                    print(iwl_mfw[name].replace("XXX", str(api)))


def show_iwlwifi_fw(iwlwifi_glob):
    for f in glob.glob(iwlwifi_glob):
        parse_iwlwifi_source(f)


show_iwlwifi_fw("drivers/net/wireless/intel/iwlwifi/cfg/*.c")
