#!/bin/bash -eu
#
# Unmount a partition of a disk image file
#


function usage()
{
	cat <<EOF
Usage: partumount [-h] [-s] MOUNTPOINT

Optional arguments:
  -h, --help     Show this help text and exit.
  -s, --silent   Disable output.
EOF
}

silent=0

while [ $# -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		-s|--silent)
			silent=1
			;;
		*)
			break;
			;;
	esac
	shift
done

if [ $# -ne 1 ] ; then
	usage
	exit 2
fi

MOUNTPOINT=${1}

if ! [ -d "${MOUNTPOINT}" ] ; then
	echo "${MOUNTPOINT} is not a directory" >&2
	exit 1
fi

# Read the config file
config="/tmp/.partmount-$(readlink -e "${MOUNTPOINT}" | md5sum | sed 's, .*,,')"
if ! [ -e "${config}" ] ; then
	echo "No config file found for mount point ${MOUNTPOINT}" >&2
	exit 1
fi
# shellcheck disable=SC1090
. "${config}"

if ! sudo umount "${MOUNTPOINT}" ; then
	echo "Failed to unmount partition from ${MOUNTPOINT}" >&2
	exit 1
fi

rm -f "${config}"
if [ "${silent}" -eq 0 ] ; then
	echo "Partition unmounted from ${MOUNTPOINT}"
fi

if [ "${DEL_MOUNTPOINT}" -eq 1 ] ; then
	rmdir "${MOUNTPOINT}"
fi

if [ -n "${NBD_DEVICE}" ] ; then
	sudo qemu-nbd -d "${NBD_DEVICE}"
fi
