#!/usr/bin/env python3
#
# Print messages of a local Mailing list archive
#

import argparse
import gzip
import json
import mailbox
import os
import re
import sys

from time import localtime, strftime

from dateutil import parser

COLS = int(os.popen("tput cols", "r").read().strip())

RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
NC = "\033[00m"


def yield_messages(f):
    """Yield messages from the provided mbox file"""
    for m in mailbox.mbox(f):
        if not m["message-id"]:
            continue

        # Create a stripped message dict
        msg = {}
        for key in ("from", "date", "subject", "message-id", "in-reply-to"):
            msg[key] = m[key]
        if msg[key]:
            # Remove trailing junk
            msg[key] = msg[key].split(">")[0] + ">"

        # Add timestamp (seconds since the epoch)
        msg["timestamp"] = parser.parse(re.sub(r" \(.*\)", "", msg["date"])).timestamp()

        yield Message(msg)


def load_messages(json_gz, dirname):
    """Load messages from the provided json.gz and add any updates"""
    messages = MessageCollection()

    if os.path.exists(json_gz):
        print(f"-- Load messages from {json_gz}", file=sys.stderr)
        messages.from_json_gz(json_gz)

    # Pull in any updates
    updated = False
    for f in sorted(os.listdir(dirname), reverse=True):
        if not f.endswith(".txt"):
            continue
        added = False
        for msg in yield_messages(os.path.join(dirname, f)):
            if not messages.message_exists(msg.id):
                messages.add_message(msg)
                added = True
                updated = True
        if not added:
            break

    # Write out updates
    if updated:
        print(f"-- Write updated messages to {json_gz}", file=sys.stderr)
        messages.to_json_gz(json_gz)

    messages.process_replies()
    return messages


class Message():
    def __init__(self, msg):
        self.msg = msg
        self.msg["subject"] = msg["subject"].replace("\n", "")
        self.msg["replied-by"] = []
        self.orig_msg = msg

    @property
    def id(self):
        return self.msg["message-id"]

    @property
    def subject(self):
        return self.msg["subject"]

    @property
    def sender(self):
        return self.msg["from"]

    @property
    def timestamp(self):
        return self.msg["timestamp"]

    @property
    def in_reply_to(self):
        return self.msg["in-reply-to"]

    def add_replied_by(self, id):
        self.msg["replied-by"].append(id)

    @property
    def replied_by(self):
        return self.msg["replied-by"]

    def print(self, indent=0):
        if "APPLIED" in self.subject or "Applied" in self.subject or "DUPLICATED" in self.subject:
            color = YELLOW
        elif "NACK" in self.subject or "NAK" in self.subject or "REJECTED" in self.subject:
            color = RED
        elif "ACK" in self.subject:
            color = GREEN
        else:
            color = NC

        text = " " * indent + self.subject
        width = COLS - 50
        if len(text) > width:
            text = text[:(width - 3)] + "..."
        else:
            text = text + " " * width
            text = text[:width]

        sender = self.sender.split("(", 1)[1].rsplit(")", 1)[0].replace(" at ", "@")
        sender = sender[:20]
        date = strftime("%Y/%m/%d %H:%M", localtime(self.timestamp))

        print(f"{color}{text}{NC}  {sender:<30}  {date}")


class MessageCollection:
    def __init__(self):
        self.msgs = {}

    def add_message(self, msg):
        if msg.id:
            self.msgs[msg.id] = msg

    def get_message(self, id):
        return self.msgs.get(id)

    def message_exists(self, id):
        return id in self.msgs

    def from_json_gz(self, json_gz):
        with gzip.open(json_gz, "r") as fh:
            for msg in json.loads(fh.read().decode("utf-8")):
                self.add_message(Message(msg))

    def to_json_gz(self, json_gz):
        with gzip.open(json_gz, "w") as fh:
            fh.write(json.dumps([m.orig_msg for m in self.msgs.values()]).encode("utf-8"))

    def process_replies(self):
        for msg in self.iter_messages():
            irt = self.get_message(msg.in_reply_to)
            if irt:
                irt.add_replied_by(msg.id)

    def iter_messages(self, reverse=True):
        for msg in sorted(self.msgs.values(), key=lambda x: x.timestamp, reverse=reverse):
            yield msg

    def get_thread(self, id, _msgs=None, _indent=0):
        if _msgs is None:
            _msgs = []

        msg = self.get_message(id)
        if msg:
            _msgs.append([msg, _indent])
            for msg_id in msg.replied_by:
                self.get_thread(msg_id, _msgs=_msgs, _indent=_indent + 2)
        return _msgs

aparser = argparse.ArgumentParser(description="Print email messages.")
aparser.add_argument("--force", action="store_true", help="Recreate the json.gz file")
aparser.add_argument("--filter", action="store_true", help="Filter non-patch emails")
aparser.add_argument("--filter-nack", action="store_true", help="Filter NACK'ed emails")
aparser.add_argument("--filter-applied", action="store_true", help="Filter APPLIED emails")
aparser.add_argument("--since", help="Print messages since the provided date")
aparser.add_argument("directory", help="Directory containing the Mailing list archive files")
args = aparser.parse_args()

if args.since:
    since_ts = parser.parse(args.since).timestamp()
else:
    since_ts = 0

json_gz = os.path.basename(args.directory.rstrip("/")) + ".json.gz"

if args.force and os.path.exists(json_gz):
    os.remove(json_gz)

messages = load_messages(json_gz, args.directory)

for msg in messages.iter_messages():
    if msg.in_reply_to:
        # Ignore replies
        continue

    if args.filter:
        if not msg.subject.startswith("["):
            continue
        if "PATCH" not in msg.subject and "PULL" not in msg.subject:
            continue

    thread = messages.get_thread(msg.id)

    if since_ts and thread[0][0].timestamp < since_ts:
        # Bail ouf it current message is too old
        break

    ignore = False
    for m, _ in thread:
        if args.filter_applied and ("APPLIED" in m.subject or "Applied" in m.subject or "DUPLICATED" in m.subject):
            ignore = True
            break
        if args.filter_nack and ("NACK" in m.subject or "NAK" in m.subject or "REJECTED" in m.subject):
            ignore = True
            break
    if ignore:
        continue

    for m, i in thread:
        m.print(indent=i)
