#!/bin/bash -u

if [ "$(id -u)" -eq 0 ] ; then
	echo "You must not be root!" >&2
	exit 1
fi

if [ $# -eq  0 ] ; then
	scp ./*+prep.img.gz rpi-master:rpi-images
else
	scp "$@" rpi-master:rpi-images
fi

ssh rpi-master 'sudo mv rpi-images/* /srv/images/preinstalled/'
