#!/bin/bash

env_dir=${HOME}/.cache/python-venv

if ! [ -d "${env_dir}" ] ; then
	python3 -m venv --system-site-packages "${env_dir}"
fi

export debian_chroot=pyvenv

# shellcheck disable=SC1091
. "${env_dir}"/bin/activate

if [ ${#} -eq 0 ] ; then
	/bin/bash
else
	"${@}"
fi

deactivate
