#!/usr/bin/env python3
#
# Read all GPIOs
#

import gpiod

# Mapping of header pins to gpio lines
header_gpio_map = {
     '3':  2,  '5':  3,  '7':  4,  '8': 14, '10': 15, '11': 17, '12': 18,
    '13': 27, '15': 22, '16': 23, '18': 24, '19': 10, '21':  9, '22': 25,
    '23': 11, '24':  8, '26':  7, '27':  0, '28':  1, '29':  5, '31':  6,
    '32': 12, '33': 13, '35': 19, '36': 16, '37': 26, '38': 20, '40': 21,
}

with gpiod.Chip('gpiochip0') as chip:
    for pin in sorted(header_gpio_map.keys(), key=int):
        line = chip.get_line(header_gpio_map[pin])
        try:
            line.request(consumer='read-rpi-gpios',
                         type=gpiod.LINE_REQ_DIR_AS_IS)
            print('{:2}: {}'.format(pin, line.get_value()))
        except OSError as e:
            print('{:2}: {}'.format(pin, e))
