#!/usr/bin/env python3

import PIL.Image
import os
import sys

img = sys.argv[1]
old = PIL.Image.open(img)
new = old.resize((400, 400), PIL.Image.ANTIALIAS)
new.save("%s.new" % img, "JPEG")
os.rename("%s.new" % img, img)
