#!/bin/bash -eu
#
# Review a debdiff file
#

COLS=$(tput cols)

function colorize()
{
    local line color

    while IFS= read -r line ; do
		case "${line}" in
			"-"*)             color="\e[31m" ;;
			"+"*)             color="\e[32m" ;;
			"!"*)             color="\e[33m" ;;
			"@@"*)            color="\e[36m" ;;
			"diff "*)         color="\e[1m\e[36m" ;;
			"Binary files "*) color="\e[33m" ;;
			"| "*)            color="\e[96m" ;;
			*)                color="" ;;
		esac

		if [ -n "${color}" ] ; then
			echo -e "${color}${line}\e[0m"
		else
			echo "${line}"
		fi
	done
}

function header()
{
	echo
	printf "| "; printf '%.0s-' $(seq 6 "${COLS}"); printf "\n"
	echo "| ${*}"
	printf "| "; printf '%.0s-' $(seq 6 "${COLS}"); printf "\n"
	echo
}

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-h] [-r] [DEBDIFF]

Review a debdiff file.

Optional arguments:
  -h, --help     Show this help text and exit.
  -r, --reduced  Review a reduced debdiff (.reduced.debdiff).
EOF
}

debdiff=
reduced=0

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		-r|--reduced)
			reduced=1
			;;
		*)
			if [ -n "${debdiff}" ] ; then
				echo "Invalid argument: ${1}" >&2
				exit 2
			fi
			debdiff=${1}
			;;
	esac
	shift
done

if [ -z "${debdiff}" ] ; then
	DEBIAN=debian
	if [ -e debian/debian.env ] ; then
		# shellcheck disable=SC1091
		. debian/debian.env
	fi
	name=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog -S Source)
	version=$(dpkg-parsechangelog -l "${DEBIAN}"/changelog -S Version)
	version=${version#*:}
	if [ ${reduced} -eq 1 ] ; then
		debdiff=../${name}_${version}.reduced.debdiff
	else
		debdiff=../${name}_${version}.debdiff
	fi
fi

if ! [ -e "${debdiff}" ] ; then
	echo "No such file: ${debdiff}" >&2
	exit 1
fi

changes=${debdiff%.debdiff}_source.changes

{
	# Header of debdiff
	header "header ${debdiff}"
	sed -n 's/^# HEADER //p' "${debdiff}"

	# lsdiff debdiff
	header "lsdiff -s ${debdiff}"
	sed '/^# HEADER /d' "${debdiff}" | lsdiff -s | uniq

	# filterdiff debdiff (non-binary files)
	header "filterdiff ${debdiff} (non-binary files)"
	sed '/^# HEADER /d' "${debdiff}" | filterdiff -x '*/abi/*' | grep -v '^Binary files '

	# filterdiff debdiff (binary files)
	header "filterdiff ${debdiff} (binary files)"
	sed '/^# HEADER /d' "${debdiff}" | filterdiff -x '*/abi/*' | grep '^Binary files '
} | awk '/^diff / { print "" } { print }' | cat -s | colorize

# Content of .changes
header "cat ${changes}" | colorize
if [ -e "${changes}" ] ; then
	cat "${changes}"
else
	echo "No such file: ${changes}"
fi
