#!/bin/bash -eu
#
# Review a debdiff file
#

function do_colordiff()
{
    local line

    while IFS= read -r line ; do
		case "${line}" in
			"-"*)
				echo -e "\e[31m${line}\e[0m"
				;;
			"+"*)
				echo -e "\e[32m${line}\e[0m"
				;;
			"!"*)
				echo -e "\e[33m${line}\e[0m"
				;;
			"@@"*)
				echo -e "\e[36m${line}\e[0m"
				;;
			"diff "*)
				echo -e "\e[1m\e[36m${line}\e[0m"
				;;
			*)
				echo "${line}"
				;;
		esac
	done
}

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-h] DEBDIFF

Review a debdiff file.

Optional arguments:
  -h, --help  Show this help text and exit.
EOF
}

debdiff=

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		*)
			if [ -n "${debdiff}" ] ; then
				echo "Invalid argument: ${1}" >&2
				exit 2
			fi
			debdiff=${1}
			;;
	esac
	shift
done

if [ -z "${debdiff}" ] ; then
	usage
	exit 2
fi

if ! [ -e "${debdiff}" ] ; then
	echo "No such file: ${debdiff}" >&2
	exit 1
fi

source=${debdiff%_*}
changes=${debdiff%.debdiff}_source.changes

# lsdiff .debdiff
echo
echo -e "\e[96m*** [1/3] lsdiff -s ${debdiff} ***\e[0m"
echo
lsdiff -s "${debdiff}" | do_colordiff

# filterdiff .debdiff
echo
echo -e "\e[96m*** [2/3] filterdiff ${debdiff} ***\e[0m"
echo
filterdiff -x '*/abi/*' "${debdiff}" | do_colordiff

# Content of .changes
echo
echo -e "\e[96m*** [3/3] cat ${changes} ***\e[0m"
echo
if [ -e "${changes}" ] ; then
	cat "${changes}"
else
	echo "No such file: ${changes}"
fi
