#!/bin/bash -eu
#
# Run a chroot session. Create it first, if it doesn't exist
#

function pr_info()
{
	echo -e "\033[33m${*}\033[0m"
}

function pr_error()
{
	echo -e "\033[31m${*}\033[0m" 1>&2
}

function session_exists()
{
	schroot -l --all | grep -q "^session:${1}$"
}

function chroot_exists()
{
	schroot -l --all | grep -q "^chroot:${1}$"
}

function hostarch()
{
	case "${1#*-}" in
		fedora*|centos*)
			dpkg-architecture -q DEB_HOST_GNU_CPU
			;;
		*)
			dpkg-architecture -q DEB_HOST_ARCH
			;;
	esac
}

function usage()
{
	cat <<EOF
Usage: run-chroot [-d] [-h] [-l] [-p] [-r] [-u USER] CHROOT [--]
       [COMMAND [ARGS]]

Run a chroot session. Create it first, if it doesn't exist.

Positional arguments:
  CHROOT                 Name of the existing session or the name of the base
                         chroot for new sessions.

Optional 
  -d, --destroy          Destroy a session.
  -h, --help             Show this help text and exit.
  -l, --list             List existing sessions.
  -p, --no-preserve-env  Don't preserve the user's environment inside the
                         chroot.
  -r, --recreate         Recreate an already existing session.
  -u, --user USER        Run the session as the user USER.
EOF
}

destroy=0
preserve_env=1
recreate=0
user=${USER}
chroot=

while [ $# -gt 0 ] ; do
	case "${1}" in
		-d|--destroy)
			destroy=1
			;;
		-h|--help)
			usage
			exit
			;;
		-l|--list)
			schroot -l --all | grep "^session:" | sed 's/^session://'
			exit
			;;
		-p|--no-preserve-env)
			preserve_env=0
			;;
		-r|--recreate)
			recreate=1
			;;
		-u|--user)
			shift
			user=${1}
			;;
		--)
			shift
			break
			;;
		-*)
			pr_error "Invalid argument: ${1}"
			exit 2
			;;
		*)
			if [ -z "${chroot}" ] ; then
				chroot=${1}
			else
				break
			fi
			;;
	esac
	shift
done

if [ -z "${chroot}" ] ; then
	usage
	exit 2
fi

# Generate the session name from the provided chroot name. The naming
# convention is <user>-<name>-<arch>
dashes="${chroot//[^-]}"
case "${#dashes}" in
	0)
		# Chroot name contains no dashes
		session=${USER}-${chroot}-$(hostarch "${chroot}")
		;;
	1)
		# Chroot name contains a single dash
		case "${chroot}" in
			*-amd64|*-i386|*-powerpc|*-s390x|*-x86_64|*-armhf|*-arm64)
				session=${USER}-${chroot}
				;;
			*)
				session=${chroot}-$(hostarch "${chroot}")
				;;
		esac
		;;
	*)
		# Chroot name contains two or more dashes
		session=${chroot}
		;;
esac

# Generate the base chroot name from the session name
chroot=${session#*-}

# Destroy an existing session if -d, --destroy is provided
if [ "${destroy}" -eq 1 ] ; then
	if ! session_exists "${session}" ; then
		pr_error "Not such session: ${session}"
		exit 1
	fi
	pr_info "Destroy existing session ${session}"
	schroot -e -c "${session}"
	exit
fi

# Destroy an existing session if -r, --recreate is provided
if [ "${recreate}" -eq 1 ] && session_exists "${session}" ; then
	pr_info "Destroy existing session ${session}"
	schroot -e -c "${session}"
fi

# Create the session if it doesn't exist
if ! session_exists "${session}" ; then
	if ! chroot_exists "${chroot}" ; then
		pr_error "Not such chroot: ${chroot}"
		exit 1
	fi
	pr_info "Create new session ${session}"
	schroot -b -n "${session}" -c "${chroot}"

	# Generate /etc/hosts
	schroot -u root -r -c "${session}" -- bash -c "cat << EOF > /etc/hosts
127.0.0.1  localhost
127.0.1.1  $(hostname)
EOF
"

	# Upgrade packages
	schroot -u root -r -c "${session}" -- apt-get update
	schroot -u root -r -c "${session}" -- apt-get -y dist-upgrade

	# Install additional packages
	schroot -u root -r -c "${session}" -- apt-get -y install \
			bc bison debhelper flex gawk git kernel-wedge less libssl-dev \
			openssl sudo
fi

# Assemble the PS1 prefix
debian_chroot=${chroot}
if [ "${user}" != "${USER}" ] ; then
	debian_chroot=${user}@${debian_chroot}
fi
export debian_chroot

# Assemble the optional schroot arguments
args=()
if [ "${preserve_env}" -eq 1 ] ; then
	args+=("-p")
fi

# Run the session
schroot -r -c "${session}" -u "${user}" "${args[@]}" -- "${@}"
