#!/bin/bash -eu

function pr_info()  { echo -e "\033[33mI: ${*}\033[0m" ; }

function chroot_make()
{
	local cmd

	cmd=("schroot" "-r" "-c" "cranky--${SERIES}-amd64" "--" "make" "O=${O}")
	cmd+=("${@}")

	pr_info "${cmd[*]}"
	"${cmd[@]}"
}

SERIES=$(dpkg-parsechangelog -ldebian.master/changelog -SDistribution)
if [ -z "${SERIES}" ] ; then
	echo "Failed to determine series" >&2
	exit 1
fi

O=buildd/${SERIES}

case "${1}" in
	init)
		chroot_make clean allmodconfig prepare
		exit
		;;
esac

if [ -f "${1}" ] ; then
#	chroot_make  allmodconfig
	chroot_make "${1%.*}".o
	exit
fi

if [ -d "${1}" ] ; then
#	chroot_make allmodconfig
	chroot_make -j"$(getconf _NPROCESSORS_ONLN)" M="${1%/}"
	exit
fi

chroot_make "${@}"
