#!/bin/bash
#
# Find the given commit in all remote branches
#

commit=${1}

while IFS= read -r line ; do
	h=${line%% *}
	s=${line#* }
	while IFS= read -r branch ; do
		printf "%-26s : %s (\"%s\")\n" "${branch:2}" "${h}" "${s}"
	done < <(git branch -r --contains "${h}")
done < <(git log --oneline --grep "$(git rev-parse "${commit}")" --all)
