#!/bin/bash -eu
#
# Find the given CVE in linux-ubuntu/<series>/linux
#

cve=${1}

while IFS= read -r branch ; do
	match=$(git log --oneline --grep "${cve}$" --max-count=1 "${branch}~1000..${branch}")
	if [ -n "${match}" ] ; then
		printf "%-27s -- %s -- %s\n" "${branch}" "${cve}" "${match}"
	fi
done < <(git branch -r | sed 's/^..//' | grep '^linux-ubuntu/.*/linux$')
