#!/usr/bin/env python3

import argparse
import json
import sys

from jira import JIRA

def show_issue(issue):
    print(issue)
    print(json.dumps(issue.raw["fields"], indent=4))

def get_next_transition(issue):
    transitions = (
        "already released",
        "patchset sent to mailinglist",
        "solution found",
        "ack and applied",
        "cycle assigned",
        "kernel released",
    )

    for t in jira.transitions(issue):
        t_name = t["name"].lower()
        t_id = t["id"]
        if t_name in transitions:
            return t_name, t_id

    return None, None

parser = argparse.ArgumentParser()
parser.add_argument("-n", "--dry-run", action="store_true")
parser.add_argument("cve")
parser.add_argument("series")
parser.add_argument("version")
parser.add_argument("comment", nargs="?")
args = parser.parse_args()

# Note: Python JIRA uses ~/.netrc for authentication
jira_server = "https://warthogs.atlassian.net"
jira = JIRA(server=jira_server)

summary = f"{args.cve.upper()} {args.series.capitalize()}"

issues = jira.search_issues(f"project = 'KERNSEC' and summary ~ '\"{summary}\"' and status not in (\"won't fix\", 'not affected', 'done')")
if not issues:
    print("No issues found")
    sys.exit(0)


for issue in issues:
    print(f"http://warthogs.atlassian.net/browse/{issue.key}")

    status = str(issue.fields.status).lower()
    print(f"Current status: {status}")

    add_comment = False
    while status != "done":
        add_comment = True

        transition_name, transition_id = get_next_transition(issue)
        if not transition_name:
            print("No transition found")
            sys.exit(1)

        print(f"Transition:     {transition_name}")
        if args.dry_run:
            break

        # Transition the issue to the next status
        jira.transition_issue(issue, transition_id)

        # Get the new status
        issue = jira.issue(issue.key)
        status = str(issue.fields.status).lower()
        print(f"New status:     {status}")

    if add_comment:
        comment = "CVE fixed in {{" + args.version + "}}"
        if args.comment:
            comment = comment + " - " + args.comment
        print(f"Add comment:    {comment}")
        if not args.dry_run:
            jira.add_comment(issue, comment)

    if args.dry_run:
        print("Dry-run, skipping...")
