#!/bin/bash -eu

function usage()
{
	cat <<EOF
Usage: sec-create-branch [-h] PREFIX SERIES [SERIES ...]

Create PREFIX/SERIES branches.

Optional arguments:
  -h, --help  Show this help message and exit.
EOF
}

prefix=

while [ $# -gt 0  ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		*)
			prefix=${1}
			shift
			break
			;;
	esac
	shift
done

if [ -z "${prefix}" ] || [ $# -eq 0 ] ; then
	usage
	exit 2
fi

git fetch linux-ubuntu

for series in "${@}" ; do
	git branch "${prefix}"/"${series}" linux-ubuntu/"${series}"/linux
done

#git checkout "${prefix}"/"${series}"
