#!/bin/bash -eu

function pr_info()  { echo -e "\033[33mI: ${*}\033[0m" ; }

function chroot_make()
{
	local cmd

	cmd=("schroot" "-r" "-c" "cranky--${SERIES}-amd64" "--" "make" "O=${O}")
	cmd+=("${@}")

	pr_info "${cmd[*]}"
	"${cmd[@]}"
}

SERIES=$(dpkg-parsechangelog -ldebian.master/changelog -SDistribution)
if [ -z "${SERIES}" ] ; then
	echo "Failed to determine series" >&2
	exit 1
fi

O=buildd/${SERIES}

if [ -f "${1}" ] ; then
	chroot_make  allmodconfig
	chroot_make "${1%.*}".o
else
	case "${1}" in
		clean)
			chroot_make clean
			;;
		prepare)
			if ! [ -e "${O}"/.config ] ; then
				chroot_make allmodconfig
			fi
			chroot_make prepare
			;;
		drivers/*)
			chroot_make allmodconfig
			chroot_make M="${1}"
			;;
	esac
fi
