#!/bin/bash

function print_version()
{
	local branch=${1}
	local v1 v2 v3 v4
		  
	git show linux-ubuntu/"${branch}":Makefile 2>&1 | head -10 > "${TMP_FILE}"

	v1=$(sed -n 's/^VERSION\s*=\s*//p' "${TMP_FILE}")
	v2=$(sed -n 's/^PATCHLEVEL\s*=\s*//p' "${TMP_FILE}")
	v3=$(sed -n 's/^SUBLEVEL\s*=\s*//p' "${TMP_FILE}")
	v4=$(sed -n 's/^EXTRAVERSION\s*=\s*//p' "${TMP_FILE}")

	if [ -z "${v1}" ] ; then
		echo "${branch}: Not found"
	else
		echo "${branch}: ${v1}.${v2}.${v3}${v4}"
	fi
}

TMP_FILE=$(mktemp)
trap 'rm -f "${TMP_FILE}"' EXIT

if [ $# -gt 0 ] ; then
	for branch in "${@}" ; do
		print_version "${branch}"
	done
	exit
fi

while read -r branch ; do
	print_version "${branch}"
done
