#!/bin/bash -eu

branch=${1}
num_releases=${2:-0}

# Get the series from the branch
series=$(git show "${branch}":debian.master/changelog | head -1 | sed -e 's/; .*//' -e 's/.* //')

declare -A CVES

num_versions=-1
version="master-next"

while IFS= read -r line ; do
	h=${line%% *}
	s=${line#* }

	case "${s}" in
		"UBUNTU: Ubuntu-"*)
			num_versions=$((num_versions + 1))
			if [ ${num_versions} -ge ${num_releases} ] ; then
				exit
			fi
			version=${s#UBUNTU: Ubuntu-}
			;;
		*)
			while IFS= read -r cve ; do
				key="${cve} ${series^} ${version}"
				if [ -z "${CVES[${key}]:-}" ] ; then
					CVES["${key}"]=1
					echo "${key} ${h} (\"${s}\")"
				fi
			done < <(git log --format=%b "${h}" -1 | grep -E '^CVE-20[0-9][0-9]-[0-9][0-9]*$')
			;;
	esac
done < <(git log --oneline --grep '^CVE-20[0-9][0-9]-[0-9][0-9]*$' --grep 'UBUNTU: Ubuntu-' "${branch}")
