#!/bin/bash -eu
#
# Split a git diff into individual hunks
#

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-h] [OUTDIR]

Read a git diff from standard input and split it into individual hunks.

Positional arguments:
  OUTDIR      Output directory for the individual hunks. If not provided,
              defaults to the current directory.

Postional arguments:
  -h, --help  Show this help text and exit.
EOF
}

outdir=

while [ ${#} -ne 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		*)
			if [ -n "${outdir}" ] ; then
				echo "Invalid argument: ${1}" >&2
				exit 2
			fi
			outdir=${1}
			;;
	esac
	shift
done

if [ -z "${outdir}" ] ; then
	outdir=.
fi
mkdir -p "${outdir}"

outfile=${outdir}/0000.diff
rm -f "${outfile}"

num=0
is_header=0
while IFS= read -r line ; do
	if [ "${line#diff --git }" != "${line}" ] ; then
		# First line of a header
		is_header=1
		header=()
	fi
	if [ "${line#@@ }" != "${line}" ] ; then
		# First line of a hunk
		is_header=0
		num=$((num + 1 ))
		outfile=$(printf "%s/%04d.diff" "${outdir}" "${num}")
		printf "%s\n" "${header[@]}" > "${outfile}"
	fi
	if [ ${is_header} -eq 1 ] ; then
		header+=("${line}")
	else
		echo "${line}" >> "${outfile}"
	fi
done

echo "Wrote ${num} diff hunks to ${outdir}"
