#!/bin/bash -eu

GREEN="\033[92m"
YELLOW="\033[93m"
NC="\033[00m"

owner=${USER}

prev_cycle=

while IFS= read -r line ; do

	# Filter out 'Complete' tasks
	case "${line}" in
		*" Complete "*) continue ;;
	esac

	cycle=$(echo "${line}" | awk '{print $5}')
	if [ "${cycle}" != "${prev_cycle}" ] ; then
		if [ -n "${prev_cycle}" ] ; then
			echo
		fi
		echo "${cycle}"
	fi

	# Print the data
	case "${line}" in
		*"Debs ready to be cranked"*) color=${GREEN} ;;
		*"Not ready to be cranked"*)  color=${YELLOW} ;;
		*)                            color=${NC} ;;
	esac
	echo -e "  ${color}${line}${NC}"

	prev_cycle=${cycle}
done < <("${KTEAM_TOOLS}"/stable/swm-ls --limit-owner "${owner}")
