#!/bin/bash -eu
#
# Sync .password-store from gollum
#

if [ "$(hostname -s)" = "gollum" ] ; then
	echo "Sync to gollum is not allowed" >&2
	exit 1
fi

set -x
rsync -av --delete --filter='P protonmail-credentials/*' \
	  gollum:~/.password-store/ ~/.password-store
