#!/bin/bash

HOST=${0#*/sync-from-}

USER_FILES=(
	${HOME}/.bash_aliases
	${HOME}/.bashrc
	${HOME}/.caffrc
	${HOME}/.canonistack/
	${HOME}/.claws-mail/
	${HOME}/.config/gtk-3.0/gtk.css
	${HOME}/.config/hexchat/servlist.conf
	${HOME}/.emacs
	${HOME}/.emacs.d/
	${HOME}/.emacs.el/
	${HOME}/.fritz
	${HOME}/.gnupg/
	${HOME}/.gitconfig
	${HOME}/.keepass/
	${HOME}/.password-store/
	${HOME}/.sesame/
	${HOME}/.ssh/
)

ROOT_FILES=(
	/etc/NetworkManager/conf.d/localdns.conf
	/etc/NetworkManager/dnsmasq.d/libvirt.conf
	/etc/auto.jabba
	/etc/auto.fritz
	# /etc/auto.master
	/etc/security/limits.d/custom.conf
	/etc/sudoers.d/${USER}
)

USER=0
ROOT=0
while [ $# -gt 0 ] ; do
	case "${1}" in
		-u|--user)
			USER=1
			;;
		-r|--root)
			ROOT=1
			;;
		*)
			echo "Invalid argument: ${1}"
			exit 2
			;;
	esac
	shift
done

if [ ${USER} -eq 0 ] && [ ${ROOT} -eq 0 ] ; then
	USER=1
	ROOT=1
fi

if [ ${USER} -eq 1 ] ; then
	echo "Syncing user files..."
	# shellcheck disable=SC2029
	ssh "${HOST}" "tar cpf - ${USER_FILES[*]}" | ( cd / && tar xpvf - )

	# Fix host specific files
	sed -i -e "s,@${HOST}/,@$(hostname)/," ${HOME}/.config/hexchat/servlist.conf
fi

if [ ${ROOT} -eq 1 ] ; then
	echo "Syncing root files..."
	# shellcheck disable=SC2029
	ssh "${HOST}" "sudo tar cpf - ${ROOT_FILES[*]}" | ( cd / && sudo tar xpvf - )
fi
