#!/bin/bash -eu
#
# Sync .password-store to other hosts
#

if [ $# -ne 1 ] ; then
	echo "Usage: $(basename "${0}") TO_HOSTNAME" >&2
	exit 2
fi

if [ "${1}" = "gollum" ] ; then
	echo "Sync to gollum is not allowed" >&2
	exit 1
fi

set -x
rsync -av --delete ~/.password-store/ "${1}":~/.password-store
