#!/bin/bash

user_files=(
	"${HOME}"/.bash_aliases
	"${HOME}"/.bottle-pi.aliases
	"${HOME}"/.bashrc
	"${HOME}"/.caffrc
	"${HOME}"/.canonistack/
	"${HOME}"/.claws-mail/
	"${HOME}"/.config/gtk-3.0/gtk.css
	"${HOME}"/.config/hexchat/servlist.conf
	"${HOME}"/.cranky
	"${HOME}"/.emacs
	"${HOME}"/.emacs.d/
	"${HOME}"/.emacs.el/
	"${HOME}"/.gnupg/
	"${HOME}"/.gitconfig
	"${HOME}"/.imapfilter/
	"${HOME}"/.password-store/
	"${HOME}"/.sesame/
	"${HOME}"/.ssh/
	"${HOME}"/Mail/
)

root_files=(
	/etc/NetworkManager/conf.d/localdns.conf
	/etc/NetworkManager/dnsmasq.d/libvirt.conf
	/etc/auto.jabba
	/etc/auto.fritz
	# /etc/auto.master
	/etc/security/limits.d/custom.conf
	/etc/sudoers.d/"${USER}"
)

function usage()
{
	cat <<EOF
Usage: sync-from-gollum [-h] [-r] [-u]

Optional arguments:
  -h, --help  Show this help text.
  -r, --root  Sync root files.
  -u, --user  Sync user files.
EOF
}

if [ "$(hostname -s)" = "gollum" ] ; then
	echo "Sync to gollum is not allowed" >&2
	exit 1
fi

user=0
root=0

while [ $# -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			exit
			;;
		-u|--user)
			user=1
			;;
		-r|--root)
			root=1
			;;
		*)
			echo "Invalid argument: ${1}" >&2
			exit 2
			;;
	esac
	shift
done

if [ ${user} -eq 0 ] && [ ${root} -eq 0 ] ; then
	usage
	exit 1
fi

if [ ${user} -eq 1 ] ; then
	echo "Syncing user files..."
	# shellcheck disable=SC2029
	ssh gollum "tar cpf - ${user_files[*]}" | ( cd / && tar xpvf - )

	# Fix host specific files
	sed -i -e "s,@gollum/,@$(hostname -s)/," \
		"${HOME}"/.config/hexchat/servlist.conf
fi

if [ ${root} -eq 1 ] ; then
	echo "Syncing root files..."
	# shellcheck disable=SC2029
	ssh gollum "sudo tar cpf - ${root_files[*]}" | ( cd / && sudo tar xpvf - )
fi
