#!/bin/bash -eu
#
# Sync misc files between machines via a common directory
#

USER_FILES=(
    ${HOME}/.bash_aliases
    ${HOME}/.bashrc
    ${HOME}/.caffrc
    ${HOME}/.canonistack/
    ${HOME}/.config/gtk-3.0/gtk.css
    ${HOME}/.config/hexchat/servlist.conf
    ${HOME}/.emacs
    ${HOME}/.emacs.d/
    ${HOME}/.fritz
    ${HOME}/.gnupg/
    ${HOME}/.gitconfig
    ${HOME}/.keepass/
    ${HOME}/.sesame/
    ${HOME}/.ssh/
)

ROOT_FILES=(
#    /etc/auto.jabba
#    /etc/auto.fritz
#    /etc/auto.master
    /etc/security/limits.d/custom.conf
    /etc/sudoers.d/${USER}
)

USER_KEY=F9F8B48C

SYNC_DIR="/mnt/fritz/${USER}/"

function sync_to()
{
    sudo tar --exclude '*~' -cJpv "${USER_FILES[@]}" | \
        gpg --yes -e -r "${USER_KEY}" -o "${SYNC_DIR}/user.txz.gpg"
    sudo tar --exclude '*~' -cJpv "${ROOT_FILES[@]}" | \
		sudo tee "${SYNC_DIR}/root.txz" 2>/dev/null
}

function sync_from()
{
    cd / && gpg -d "${SYNC_DIR}/user.txz.gpg" | tar -xJpv
    cd / && sudo tar -xJpvf "${SYNC_DIR}/root.txz"
}

case "${1:-}" in
    to|from)
        "sync_${1}"
        ;;
    *)
        echo "Usage: $(basename "${0}") to|from"
        exit 2
        ;;
esac
