#!/bin/bash

function usage()
{
	cat <<EOF
Usage: $(basename "${0}") [-d] [HOST]

Sync various files from and Android device.

Optional arguments:
  -d, --dry-run
  -h, --help     Show this help text.
EOF
}

host=moto-miami
opts=()

while [ $# -gt 0 ] ; do
	case "${1}" in
		-d|--dry-run)
			echo "-- Dry-run"
			opts+=("--dry-run")
			;;
		-h|--help)
			usage
			exit
			;;
		-*)
			usage
			exit 2
			;;
		*)
			host="${1}"
			break
			;;
	esac
	shift
done

opts+=(
	"--verbose"
	"--archive"
	"--exclude" "Android/data"
	"--exclude" "Android/obb"
	"--exclude" "**/.thumbnails"
)

case "$(basename "${0}")" in
	*-from-*)
		echo "-- Sync from ${host}"
		rsync "${opts[@]}" \
			  -e ssh "${host}":/storage/emulated/0/ "${HOME}"/Sync/"${host}"/
		;;
	*-to-*)
		echo "-- Sync to ${host}"
		rsync "${opts[@]}" \
			  -e ssh "${HOME}"/Sync/"${host}"/ "${host}":/storage/emulated/0/ 
		;;
	*)
		echo "Invalid sync mode" >&2
		exit 1
		;;
esac
