#!/bin/bash -eu
#
# Tag a Debian/Ubuntu source package release commit
#

function usage()
{
	cat <<EOF
Usage: tag-release-commit [-f] [-h]

Tag a Debian/Ubuntu source package release.

Optional arguments:
  -f, --force  Overwrite an already existing tag.
  -h, --help   Show this help text and exit.
EOF
}

force=0

while [ ${#} -gt 0 ] ; do
	case "${1}" in
		-f|--force)
			force=1
			;;
		-h|--help)
			usage
			exit
			;;
		*)
			echo "Invalid argument: ${1}" 2>/dev/null
			exit 2
			;;
	esac
	shift
done

# HEAD commit needs to modify debian/changelog
if ! git show --format= --name-only | grep -qFx "debian/changelog" ; then
	echo "Current HEAD does not modify debian/changelog" >&1
	exit 1
fi

# Get the version from the changelog
version=$(dpkg-parsechangelog -SVersion)

head_subject=$(git log --format='%s' -1 | tr -d '\n')
case "${head_subject}" in
	"UBUNTU: Ubuntu-${version}"|\
	"UBUNTU: Ubuntu-"*"-${version}")
		ubuntu=1
		;;
	"UBUNTU: Ubuntu-"*)
		echo "Ubuntu version mismatch between changelog and HEAD commit subject" >&2
		exit 1
		;;
	*)
		ubuntu=0
		;;
esac

if [ ${ubuntu} -eq 1 ] ; then
	tag=${head_subject#UBUNTU: }
	msg=${head_subject}
else
	tag=${version}
	msg="Release: ${version}"
fi

tag=${tag//\~/_}

if [ ${force} -eq 0 ] && git rev-parse "${tag}" >/dev/null 2>&1 ; then
    echo "Tag exists already: ${tag}" >&2
    exit 1
fi

set -x
git tag -f -s -m  "${msg}" "${tag}"
