#!/usr/bin/env python3

import sys
import time

import pyotp
from subprocess import check_output


def get_password(pass_name):
    """Return a password from the password store"""
    return check_output(["pass", "show", pass_name]).decode().split("\n", 1)[0]

pass_name = sys.argv[1]
print(f"Read seed from: {pass_name}")
seed = get_password(pass_name)
totp = pyotp.TOTP(seed)

try:
    while True:
        expires = int(30 - (time.time() % 30))
        sys.stdout.write(f"\rCurrent Code: {totp.now()} (Expires in: {expires:2d}s)")
        sys.stdout.flush()
        time.sleep(1)
except KeyboardInterrupt:
    pass
