#!/usr/bin/env python3
#
# Show Ubuntu kernel tag information
#

import json
import logging as log
import re

import click
import git

RE_TAG = re.compile(r"^Ubuntu(-unstable)?-\d+\.\d+\.\d+-\d+\.\d+$")

# Hard-coded previous tags
PREVIOUS_TAGS = {
    "Ubuntu-4.11.0-0.1": "Ubuntu-4.10.0-14.16",
    "Ubuntu-2.6.30-1.1": "Ubuntu-2.6.28-9.31",
    "Ubuntu-2.6.26-1.5": "Ubuntu-2.6.26-1.4",
    "Ubuntu-2.6.26-1.4": "Ubuntu-2.6.26-1.3",
    "Ubuntu-2.6.26-1.3": "Ubuntu-2.6.26-1.2",
    "Ubuntu-2.6.26-1.2": "Ubuntu-2.6.26-1.1",
    "Ubuntu-2.6.26-1.1": "Ubuntu-2.6.24-19.33",
    "Ubuntu-2.6.22-1.3": "Ubuntu-2.6.22-1.2",
    "Ubuntu-2.6.22-1.2": "Ubuntu-2.6.22-1.1",
    "Ubuntu-2.6.22-1.1": "Ubuntu-2.6.20-15.27",
    "Ubuntu-2.6.19-1.1": "Ubuntu-2.6.17-10.25",
}


def release_from_line(line):
    """Return source/version/series release string from a debian/changelog release line"""
    source, version, series = line.translate({ord(i): None for i in "();"}).split(" ")[
        0:3
    ]
    series = series.split("-")[0]  # Fix series like jaunty-security
    return f"{source}/{version}/{series}"


def tagname_from_release(release):
    """Return the tagname from a source/version/series release string"""
    source, version, _ = release.split("/")
    if source.startswith("linux-source-2.6"):
        prefix = ""
    else:
        prefix = source.removeprefix("linux")
    return f"Ubuntu{prefix}-{version}"


def releases_from_tag(tag, cache=None):
    """Return the list of release strings from debian/changelog of the provided tag"""
    # Check the tag name
    if not RE_TAG.match(tag.name):
        log.info(f"Invalid tag name: {tag.name}")
        return None

    # Check the cache first
    if cache:
        cached = cache.get(tag.name)
        if cached:
            return cached

    # Get the changelog directory
    try:
        debian = tag.repo.git.show(f"{tag}:debian/debian.env").splitlines()[0]
        debian = debian.split("=")[1]
    except git.exc.GitCommandError:
        debian = "debian"

    # Get the changelog content
    try:
        changelog = tag.repo.git.show(f"{tag}:{debian}/changelog").splitlines()
    except git.exc.GitCommandError:
        changelog = None
    if not changelog:
        log.info("Debian changelog not found")
        return None

    # Get the release info from the changelog
    release = release_from_line(changelog[0])

    # Check the source name
    source, _, _ = release.split("/")
    if not (
        source in ("linux", "linux-unstable") or source.startswith("linux-source-2.6")
    ):
        log.info(f"Invalid source name: {source}")
        return None

    # Check the tag name
    tag_name = tagname_from_release(release)
    if tag.name != tag_name:
        log.error(f"Tag name mismatch: {tag.name} != {tag_name}")
        return None

    # Pull the releases from the changelog
    releases = []
    for line in changelog:
        if line.startswith("linux"):
            releases.append(release_from_line(line))

    return releases


class TagError(Exception):
    pass


class TagCache:
    def __init__(self):
        self.tags = {}

    def add(self, tag, exclusive=False):
        if exclusive and tag.name in self.tags:
            raise TagError(f"Tag exists already in the cache: {tag}")
        self.tags[tag.name] = tag
        self.tags[tag.release] = tag
        log.info(f"Cache add:  {tag.name} -- {tag.release}")

    def get(self, tag_name_or_release):
        tag = self.tags.get(tag_name_or_release)
        if tag:
            log.info(f"Cache hit:  {tag_name_or_release}")
            return tag
        log.info(f"Cache miss: {tag_name_or_release}")
        return None


class UbuntuTag:
    def __init__(self, tag, releases, cache=None):
        self.tag = tag
        self.releases = releases
        self.cache = cache

        self.name = tag.name
        self.committed_date = tag.commit.committed_date
        self.release = releases[0]
        self.prev_release = self.previous_release()

    def previous_release(self):
        # Check if the previous tag is hard-coded
        prev_tag_name = PREVIOUS_TAGS.get(self.name)
        if prev_tag_name:
            return releases_from_tag(self.tag.repo.tags[prev_tag_name])[0]

        # Walk the changelog releases
        for release in self.releases[1:]:
            # Try the cache first
            if self.cache and self.cache.get(release):
                return release

            # Try to find it in the repo
            tag_name = tagname_from_release(release)
            try:
                return releases_from_tag(self.tag.repo.tags[tag_name])[0]
            except (IndexError, TypeError):
                pass

        return "None/None/None"

    @classmethod
    def from_tag(cls, tag, cache=None):
        releases = releases_from_tag(tag, cache=cache)
        if not releases:
            return None
        return cls(tag, releases, cache=cache)

    def _to_dict(self):
        return {
            "name": self.name,
            "committed-date": self.committed_date,
            "release": self.release,
            "prev-release": self.prev_release,
            "releases": self.releases,
        }

    def print(self, format=None):
        if format == "oneline":
            d = self._to_dict()
            del d["releases"]
            print(json.dumps(d))
            return

        if format == "full":
            print(json.dumps(self._to_dict(), indent=4))
            return

        print(self.name)


@click.group()
@click.option("--debug", help="Enable debug messages.", is_flag=True)
@click.option("--verbose", help="Enable verbose messages.", is_flag=True)
def cli(debug, verbose):
    if debug:
        log_level = log.DEBUG
    elif verbose:
        log_level = log.INFO
    else:
        log_level = log.WARNING
    log.basicConfig(format="%(levelname)s: %(message)s", level=log_level)


@cli.command(name="list")
@click.option("--format", type=click.Choice(["oneline", "full"]))
def _list(format):
    """List Ubuntu main kernel tags."""
    cache = TagCache()
    repo = git.Repo(".")
    for repo_tag in repo.tags:
        ubuntu_tag = UbuntuTag.from_tag(repo_tag, cache=cache)
        if ubuntu_tag:
            cache.add(ubuntu_tag, exclusive=True)
            ubuntu_tag.print(format=format)


@cli.command()
@click.option("--format", type=click.Choice(["oneline", "full"]))
@click.argument("tag")
def show(format, tag):
    """Show Ubuntu main kernel tag."""
    repo = git.Repo(".")
    ubuntu_tag = UbuntuTag.from_tag(repo.tags[tag])
    ubuntu_tag.print(format=format)


def walk_tag(tag, format=None):
    """Walk backwards from tag"""
    tag.print(format=format)
    if tag.prev_release == "None/None/None":
        return

    prev_tagname = tagname_from_release(tag.prev_release)
    prev_tag = UbuntuTag.from_tag(tag.tag.repo.tags[prev_tagname])
    walk_tag(prev_tag, format=format)


@cli.command()
@click.option("--format", type=click.Choice(["oneline", "full"]))
@click.argument("tag")
def walk(format, tag):
    """Walk backwards from an Ubuntu main kernel tag."""
    repo = git.Repo(".")
    ubuntu_tag = UbuntuTag.from_tag(repo.tags[tag])
    walk_tag(ubuntu_tag, format=format)


if __name__ == "__main__":
    cli()
