#!/usr/bin/env python3
#
# Patch class
#

import argparse
import email
import logging
import os
import re
import sys
import yaml

from launchpadlib.launchpad import Launchpad


RE_TAG_TYPE = re.compile(r"^(PATCH|PULL)\s*(v\d+)?\s*(\d+/\d+)?$")
RE_TAG_TARGET = re.compile(r"^([a-zA-Z0-9-.]+/?)+$")
RE_TAG_FROM_COMMIT = re.compile(r"^\((cherry picked|backported) from commit ([0-9a-f]{40})\s*(.*)?\)$")

# Check results
SKIP = "skip"
PASS = "pass"
FAIL = "fail"
WARN = "warn"

# Global ugliness...
KS = {}
LP = None


def get_kernel_series_yaml(ksfile):
    """
    Read kernel-series.yaml and return supported series/sources
    """
    if KS:
        return KS

    LOG.debug("Read %s", ksfile)

    with open(os.path.expanduser(ksfile), encoding="utf=8") as fh:
        ks = yaml.safe_load(fh)

    for _, series_data in ks.items():
        sources = series_data.get("sources")
        if not sources:
            continue

        supported = series_data.get("supported", False)
        development = series_data.get("development", False)
        if not supported and not development:
            continue

        for source, source_data in sources.items():
            source_supported = source_data.get("supported", True)
            if supported and not source_supported:
                continue

            codename = series_data["codename"]
            if codename not in KS:
                KS[codename] = {}
            KS[codename][source] = 1

    return KS


def get_launchpad():
    """
    Log into Launchpad
    """
    global LP

    if not LP:
        LP = Launchpad.login_anonymously("ubuntu-checkpatch", "production",
                                         version="devel")
    return LP


def log_result(result, text, reason=""):
    if result in ("fail"):
        log_res = LOG.error
        col = "31"  # red
    elif result in ("pass"):
        log_res = LOG.info
        col = "32"  # green
    elif result == "warn":
        log_res = LOG.warning
        col = "33"  # yellow
    else:
        log_res = LOG.info
        col = "34"  # blue

    col_result = "\033[{}m[{}]\033[0m".format(col, result)
#    col_reason = "\033[{}m[reason: {}]\033[0m".format(col, reason)
    col_reason = "\033[{}m[{}]\033[0m".format(col, reason)

    log_res("    %-15s  %s%s%s", col_result, text, "  " if text and reason
            else "", col_reason if reason else "")


class Check():
    """
    Base check class
    """
    def __init__(self, patch_or_series):
        self.patch = patch_or_series
        self.series = patch_or_series
        self.name = None
        self.results = []

    def result(self, result, comment):
        self.results.append([result, comment])

    def log(self, num=1):
        for i, (result, comment) in enumerate(self.results):
            if len(self.results) == 1:
                checknum = num
            else:
                checknum = "{}.{}".format(num, i + 1)

            if result == FAIL:
                log = LOG.error
                col = "31"  # red
            elif result == PASS:
                log = LOG.info
                col = "32"  # green
            elif result == WARN:
                log = LOG.warning
                col = "33"  # yellow
            else:
                log = LOG.info
                col = "34"  # blue

            result = "\033[{}m[{}]\033[0m".format(col, result)

            log("  Check #%-3s  %-19s  %s  %s", checknum, self.name, result,
                comment)

#    def run(self):
#        pass


class CheckPatchTarget(Check):
    """
    Check the target tags (series/source) and verify that all combinations
    are valid by looking them up in the provided kernel-series.yaml
    """
    def __init__(self, patch, ks):
        super().__init__(patch)
        self.ks = ks

    def run(self):
        self.name = "patch_target"

        if not self.patch.target_tags:
            self.result(FAIL, "missing series/source target tag")
            return 1

        rc = 0

        for target in self.patch.target_tags:
            series = []
            source = []
            for val in target.split("/"):
                val = val.lower()

                # Single letter series name, find the full series name
                if len(val) == 1:
                    full_name = None
                    for name in self.ks:
                        if name.startswith(val):
                            full_name = name
                            break
                    if not full_name:
                        self.result(FAIL, "invalid series letter: " + val)
                        rc += 1
                    else:
                        series.append(full_name)
                    continue

                # Full series name
                if val in self.ks:
                    series.append(val)
                    continue

                # Must be a source name then
                if not val.startswith("linux"):
                    val = "linux-" + val
                source.append(val)

            # No source specified, so default to "linux"
            if not source:
                source = ["linux"]

            LOG.debug("Series: %s", series)
            LOG.debug("Source: %s", source)

            # Verify that all series/source combinations are valid
            for ser in series:
                for src in source:
                    ser_src = "{}/{}".format(ser, src)
                    if src in self.ks[ser]:
                        self.result(PASS, "valid series/source target: " +
                                    ser_src)
                    else:
                        self.result(FAIL, "invalid series/source target: " +
                                    ser_src)
                        rc += 1

        return rc


class CheckPatchVersion(Check):
    """
    Check patch version
    """
    def run(self):
        self.name = "patch_version"

        if self.patch.version is None:
            self.result(SKIP, "no version specified")
            return 0

        ver = self.patch.version

        if ver < 1:
            self.result(FAIL, "invalid version: " + str(ver))
            return 1

        if ver == 1:
            self.result(WARN, "unnecessary version: " + str(ver))
            return 1 << 8

        self.result(PASS, "valid version: " + str(ver))
        return 0


class CheckPatchCountTotal(Check):
    """
    Check patch count and total number
    """
    def run(self):
        self.name = "patch_count_total"

        if self.patch.count is None:
            self.result(SKIP, "no count/total specified")
            return 0

        cnt_tot = "{}/{}".format(self.patch.count, self.patch.total)

        if ((self.patch.count < 0 or self.patch.total < 1 or
             self.patch.count > self.patch.total)):
            self.result(FAIL, "invalid count and/or total: " + cnt_tot)
            return 1

        if ((self.patch.scount == 1 and self.patch.count == 1 and
             self.patch.total == 1)):
            self.result(WARN, "unnecessary count/total: " + cnt_tot)
            return 1 << 8

        self.result(PASS, "valid count/total: " + cnt_tot)
        return 0


class CheckBugLinkCVE(Check):
    """
    Check BugLinks and/or CVEs
    """
    def __init__(self, patch, lp):
        super().__init__(patch)
        self.lp = lp

    def run(self):
        self.name = "buglink_cve"

        if not self.patch.buglinks and not self.patch.cves:
            self.result(FAIL, "missing BugLink/CVE tag")
            return 1

        for cve in self.patch.cves:
            # TODO: Check CVE tag format
            self.result(PASS, "valid CVE tag: " + cve)

        rc = 0

        for link in self.patch.buglinks:
            if len(link) > 1:
                # BugLink with trailing title
                if re.match(r"\((LP|SF)#: \d+\).$", link[1]):
                    self.result(PASS, "valid BugLink: " + " ".join(link))
                else:
                    self.result(FAIL, "incorrect or missing LP/SF bug " +
                                "reference: " + " ".join(link))
                    rc += 1
            else:
                try:
                    # Query Launchpad
                    bugnum = link[0].split("/")[-1]
                    title = self.lp.bugs[bugnum].title
                    self.result(PASS, "valid BugLink: {} ({})".format(
                        link[0], title))
                except BaseException:
                    self.result(FAIL, "invalid BugLink: " + link[0])
                    rc += 1

        return rc


class CheckCherrypickBackport(Check):
    """
    Check cherrypick and backport tags
    """
    def run(self):
        self.name = "cherrypick_backport"

        if not self.patch.cherrypick and not self.patch.backport:
            if self.patch.subject.startswith("UBUNTU: "):
                self.result(PASS, "missing cherrypick/backport tag but " +
                            "patch is an UBUNTU patch")
                return 0
            self.result(FAIL, "missing cherrypick/backport tag")
            return 1

        if self.patch.cherrypick and self.patch.backport:
            self.result(FAIL, "cherrypick and backport tags present")
            return 1

        if self.patch.cherrypick:
            commit = self.patch.cherrypick
            self.result(PASS, "valid cherrypick from commit: " + commit)

        if self.patch.backport:
            commit = self.patch.backport
            self.result(PASS, "valid backport from commit: " + commit)

        # TODO: Check provenance and upstream commit existence
        return 0


class CheckSignerComment(Check):
    """
    Check signer comment
    """
    def run(self):
        self.name = "signer_comment"

        if self.patch.comments:
            self.result(PASS, "valid comment: " +
                        " ".join(self.patch.comments))
            return 0

        if self.patch.backport:
            self.result(FAIL, "missing backport modification comment")
            return 1

        self.result(PASS, "no comment necessary")
        return 0


class CheckSOB(Check):
    """
    Check SOB tag
    """
    def run(self):
        self.name = "sob"

        if not self.patch.sob:
            self.result(FAIL, "missing Signed-off-by tag")
            return 1

        # TODO: Check SOB format
        self.result(PASS, "valid Signed-off-by tag: " + self.patch.sob)
        return 0


class CheckSeriesType(Check):
    """
    Check series type
    """
    def run(self):
        self.name = "series_type"

        stype = self.series.patches[0].type

        if stype not in ("PATCH", "PULL"):
            self.result(FAIL, "invalid series type: " + stype)
            return 1

        if stype == "PULL" and len(self.series.patches) > 1:
            self.result(FAIL, "pull-request consists of more than one file")
            return 1

        self.result(PASS, "valid series type: " + stype)
        return 0


class CheckSeriesSOB(Check):
    """
    Check identical SOB tags
    """
    def run(self):
        self.name = "series_sob"

        rc = 0
        first = True
        sob = None
        for patch in self.series.patches:
            if patch.cover_letter:
                continue
            if first:
                first = False
                sob = patch.sob
                continue
            if sob and sob != patch.sob:
                rc += 1
        if not sob:
            rc = 1

        if rc:
            self.result(FAIL, "inconsistent Signed-off-by tags")
            return rc

        self.result(PASS, "consistent Signed-off-by tag: " + sob)
        return 0


class CheckSeriesBugLink(Check):
    """
    Check identical buglinks
    """
    def run(self):
        self.name = "series_buglink"

        cc = 0
        buglink = {}
        for patch in self.series.patches:
            if patch.cover_letter:
                cc = 1
                continue
            for link in patch.buglinks:
                buglink[link[0]] = buglink.get(link[0], 0) + 1

        rc = 1
        for key, val in buglink.items():
            if val == len(self.series.patches) - cc:
                self.result(PASS, "consistent BugLink: " + key)
                rc = 0

        if rc:
            self.result(FAIL, "inconsistent BugLinks")
            return rc

        return 0


class Patch():
    """
    Patch class
    """
    def __init__(self, infile):
        self.file = infile         # Patch file name

        # Patch series data
        self.scount = None         # Patch series count
        self.cover_letter = False  # Is this a cover letter patch

        # Message header data
        self.msg_from = None       # Mail message sender/author
        self.msg_subject = None    # Mail message subject
        self.msg_body = None       # Mail message body

        # Message subject data
        self.tags = []             # All tags
        self.deprecated_tags = []  # Deprecated tags
        self.invalid_tags = []     # Invalid tags
        self.target_tags = []      # Target series/source tags
        self.subject = None        # Patch subject
        self.type = None           # Patch type (PATCH or PULL)
        self.version = None        # Patch submission version
        self.count = None          # Patch count
        self.total = None          # Total number of patches in series

        # Message body data
        self.buglinks = []         # Buglinks
        self.cves = []             # CVE tags
        self.sob = None            # Last signed-off-by signer
        self.pr_url = None         # Pull request URL (and branch/tag)
        self.pr_from = None        # Pull request from commit hash
        self.pr_to = None          # Pull request to commit hash
        self.cherrypick = None     # Cherry picked commit hash
        self.backport = None       # Backported commit hash
        self.comments = []         # Modification comment
        self.provenance = None     # Original commit provenance

    def _parse_msg_subject(self):
        """
        Parse the mail subject line
        """
        LOG.debug("Parse mail subject: %s", self.msg_subject)

        # Extract the leading tags from the subject line
        # This could be as simple as
        #   tags = subject.split("] ")[0][1:].split("][")
        # but we make it a little more robust to allow for spaces between tags
        is_tag = False
        tag = ""
        for i, c in enumerate(self.msg_subject):
            if c == "[":
                is_tag = True
            elif c == "]":
                is_tag = False
                self.tags.append(tag)
                tag = ""
            elif is_tag:
                tag = tag + c
            elif c != " ":
                # Non-whitespace character outside of a tag so end the tag
                # parsing
                self.subject = self.msg_subject[i:]
                break

        # Parse the tags
        for tag in self.tags:
            # Deprecated tag
            if tag == "SRU":
                self.deprecated_tags.append(tag)
                continue

            # Check if this is a PATCH/PULL tag
            m = RE_TAG_TYPE.match(tag)
            if m:
                self.type = m.group(1)      # PATCH|PULL
                if m.group(2) is not None:  # vN
                    self.version = int(m.group(2)[1:])
                if m.group(3) is not None:  # x/y
                    x, y = m.group(3).split("/")
                    self.count = int(x)
                    self.total = int(y)
                    if self.count == 0:
                        self.cover_letter = True
                continue

            # Check if this is a series/source target tag
            m = RE_TAG_TARGET.match(tag)
            if m:
                self.target_tags.append(tag)
                continue

            # Invalid tag
            self.invalid_tags.append(tag)

    def _parse_msg_body(self):
        """
        Parse the mail body
        """
        LOG.debug("Parse mail body")

        body = self.msg_body.split("\n")

        # Parse the commit message
        sob = 0
        for i, line in enumerate(body):
            if line.startswith("diff --git "):
                break
            if line.startswith("BugLink: http"):
                self.buglinks.append(line.split(" ", 2)[1:])
            elif line.startswith("CVE-"):
                self.cves.append(line.split(" ")[0])
            elif line.startswith("Signed-off-by:"):
                self.sob = line.split(" ", 1)[1]
                sob = i
            elif line.startswith("The following changes since commit "):
                self.pr_from = line.split(" ")[5][:-1]
            elif line.startswith("for you to fetch changes up to "):
                self.pr_to = line.split(" ")[7][:-1]
                self.pr_url = body[i - 2].strip()
                break

        if sob:
            # Walk backwards from the last SOB and parse the "trailer"
            is_comment = False
            for line in list(reversed(body[:sob])):
                # Modification comment
                if line.startswith("[") or line.endswith("]") or is_comment:
                    self.comments.insert(0, line)
                    is_comment = not line.startswith("[")
                    continue

                # cherry picked or backported from (with provenance) tag
                m = RE_TAG_FROM_COMMIT.match(line)
                if m:
                    if m.group(1) == "cherry picked":
                        self.cherrypick = m.group(2)
                    elif m.group(1) == "backported":
                        self.backport = m.group(2)
                    self.provenance = m.group(3)
                    continue

                # End of mail "trailer"
                break

    def parse(self):
        """
        Parse a patch (or pull-request) file
        """
        if not os.path.exists(self.file):
            LOG.error("File not found: %s", self.file)
            sys.exit(1)

        LOG.debug("Parse patch file: %s", self.file)

        with open(self.file, encoding="utf-8") as fh:
            msg = email.message_from_file(fh)

        # Parse the message header
        self.msg_from = msg["From"]
        if msg["Subject"]:
            self.msg_subject = msg["Subject"].replace("\n", "")
        self.msg_body = msg.get_payload()

        if not (self.msg_from and self.msg_subject and self.msg_body):
            LOG.error("Unable to parse patch file: %s", self.file)
            sys.exit(1)

        # Parse the message subject and body
        self._parse_msg_subject()
        self._parse_msg_body()

        # Print message header data
        LOG.debug("                Patch file: %s", self.file)
        LOG.debug("              Message from: %s", self.msg_from)
        LOG.debug("           Message subject: %s", self.msg_subject)

        # Print patch series data
        LOG.debug("        Patch series count: %s", self.scount)
        LOG.debug("              Cover letter: %s", self.cover_letter)

        # Print message subject data
        LOG.debug("              Subject tags: %s", self.tags)
        LOG.debug("           Deprecated tags: %s", self.deprecated_tags)
        LOG.debug("              Invalid tags: %s", self.invalid_tags)
        LOG.debug(" Series/source target tags: %s", self.target_tags)
        LOG.debug("             Patch subject: %s", self.subject)
        LOG.debug("                Patch type: %s", self.type)
        LOG.debug("             Patch version: %s", self.version)
        LOG.debug("               Patch count: %s", self.count)
        LOG.debug("               Patch total: %s", self.total)

        # Print message body data
        LOG.debug("                  Buglinks: %s", self.buglinks)
        LOG.debug("                      CVEs: %s", self.cves)
        LOG.debug("             Signed-off-by: %s", self.sob)
        LOG.debug("   PR URL (and branch/tag): %s", self.pr_url)
        LOG.debug("            PR from commit: %s", self.pr_from)
        LOG.debug("           PR up to commit: %s", self.pr_to)
        LOG.debug("         Cherrypicked from: %s", self.cherrypick)
        LOG.debug("           Backported from: %s", self.backport)
        LOG.debug("           Changes comment: %s", self.comments)
        LOG.debug("Original commit provenance: %s", self.provenance)

    def check(self, ksfile=None):
        """
        Check patch
        """
        LOG.info("File check: %s", self.file)

        checks = [
            CheckPatchTarget(self, ks=get_kernel_series_yaml(ksfile)),
            CheckPatchVersion(self),
            CheckPatchCountTotal(self),
        ]

        if not self.cover_letter:
            checks += [
                CheckBugLinkCVE(self, lp=get_launchpad()),
                CheckCherrypickBackport(self),
                CheckSignerComment(self),
                CheckSOB(self),
            ]

        rc = 0
        for i, check in enumerate(checks):
            rc += check.run()
            check.log(i + 1)

        return rc


class PatchSeries():
    """
    Patch series class
    """
    def __init__(self):
        self.patches = []

    def append(self, infile):
        """
        Append a patch to the series
        """
        self.patches.append(Patch(infile))

    def parse(self):
        """
        Parse the patch series
        """
        for patch in self.patches:
            patch.scount = len(self.patches)
            patch.parse()

    def check(self, ksfile=None):
        """
        Check the patch series
        """
        # Check the series type
        LOG.info("Base Check")
        check = CheckSeriesType(self)
        rc = check.run()
        check.log()
        if rc:
            return rc

        # Check the individual patches
        for patch in self.patches:
            LOG.info("")
            rc += patch.check(ksfile=ksfile)

        # Check consistency across all patches
        LOG.info("")
        LOG.info("Consistency check")

        checks = [
            CheckSeriesSOB(self),
            CheckSeriesBugLink(self),
        ]

        for i, check in enumerate(checks):
            rc += check.run()
            check.log(i + 1)

        # TODO: check monotonic increase of patch number
        return rc


def main(args):
    # Create the patch series
    ps = PatchSeries()
    for infile in sorted(args.infile):
        ps.append(infile)

    # Parse and check the patch series
    ps.parse()
    rc = ps.check(ksfile="~/.cache/kernel-series.yaml")

    return rc


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose", action="store_true", default=False)
    parser.add_argument("infile", metavar="INFILE", nargs="+")
    args = parser.parse_args()

    # Set up the logger
    LOG = logging.getLogger("ubuntu-checkpatch")
    handler = logging.StreamHandler()
    if args.verbose:
        LOG.setLevel(logging.DEBUG)
        handler.setFormatter(logging.Formatter("%(levelname)7s -- %(message)s"))
    else:
        LOG.setLevel(logging.INFO)
        handler.setFormatter(logging.Formatter("%(message)s"))
    LOG.addHandler(handler)

    rc = 1
    try:
        rc = main(args)
    except BaseException as ex:
        if args.verbose:
            raise ex
        LOG.error("")
        LOG.error("Error: %s", ex)

    err = rc & 0xff
    warn = (rc >> 8) & 0xff

    # Print final results
    LOG.info("")
    LOG.info("Found %s warning%s", warn, "" if warn == 1 else "s")
    LOG.info("Found %s error%s", err, "" if err == 1 else "s")

    sys.exit(rc)
