#!/bin/bash -eu

if [ "$(id -u)" != "0" ] ; then
	echo "This script must be run as root" >&1
	exit 1
fi

readarray -t vpns < <(nmcli con | sed -n 's/ *vpn *-- *//p')

num=1
for vpn in "${vpns[@]}" ; do
	printf "%2d. %s\n" "${num}" "${vpn}"
	num=$((num + 1))
done

echo
echo -n "Choice: "
read -r c
echo

vpn=${vpns[$((c - 1))]}

echo "-- Bring up"
echo "$vpn"
nmcli con up "${vpn##* }"
