#!/bin/bash -u

function pr_note() { echo -e "\033[93m${*}\033[0m"; }

while IFS= read -r line ; do
	echo
	pr_note "${line}"
	git --no-pager diff --color=always "${2}" -- "${line}"
done < <(cat "$1")
