#!/bin/bash
#
# Hourly cron job
#
# 0 * * * * ( cd "${HOME}"/git/cron && ./tools/cron/hourly > cron-hourly.log 2>&1 )
#

if [ "$(id -u)" -eq 0 ] ; then
    exec sudo -u juergh "$0"
fi

for sock in /run/user/"$(id -u)"/{gcr,keyring}/ssh ; do
	if [ -S "${sock}" ] ; then
		export SSH_AUTH_SOCK=${sock}
		break
	fi
done

while IFS= read -r repo ; do
	if [ -d "${repo}" ] ; then
		(
			cd "${repo}" || exit

			echo "-- $(date)"
			echo "-- Update repo $(pwd)"

			git fetch
			remote_branch=$(git rev-parse --abbrev-ref '@{u}')
			git reset --hard "${remote_branch}"

			echo "-- Done"
			echo
		)
	fi
done < hourly.list
