#!/bin/bash
#
# /etc/grub.d/15_create-cloud-lv
#

for c in /boot/grub/grub-*.cfg ; do
	series=${c#*/grub-}
	series=${series%%-*}
	arch=${c%.cfg}
	arch=${arch##*-}

	cat <<EOF
menuentry 'Ubuntu ${series^} ${arch}' --class gnu-linux --class gnu --class os {
    configfile ${c#/boot}
}
EOF
done
