#!/bin/bash -eu

function out()
{
	local rc=${?}

	trap - EXIT INT TERM HUP

	if [ -n "${USER_DATA}" ] ; then
		rm -f "${USER_DATA}"
	fi

	if [ -n "${SERVER_NAME}" ] && [ "${KEEP}" -eq 0 ] ; then
		echo "-- Delete server ${SERVER_NAME}"
		openstack server delete "${SERVER_NAME}"
	fi

	if [ ${rc} -ne 0 ] ; then
		echo "-- Error: Script failed (rc=${rc})" >&2
	fi

	exit "${rc}"
}

function wait_for_status()
{
	local timeout=${1} type=${2} name=${3} status=${4}
	local abs_timeout cur_status

	abs_timeout=$(($(date +%s) + timeout))
	while [ "$(date +%s)" -lt "${abs_timeout}" ] ; do
		cur_status=$(openstack "${type}" show "${name}" | \
						 awk '$2 == "status" { print $4 }')
		echo "-- ${type^} status: ${cur_status}"
		if [ "${cur_status}" = "${status}" ] ; then
			return 0
		fi
		sleep 10
	done

	echo "-- Error: Timeout" >&2
	return 1
}

release=jammy
arch=arm64

image=juergh/adt-jammy-arm64-20221003.img

flavor=autopkgtest
key_name=${USER}
network=net_kernel-automated-tests
security_group=allow-ping-and-ssh

MIRROR="apt_mirror: http://ftpmaster.internal/ubuntu/"
EXTRA_ENV=

AUTOPKGTEST=~/git/autopkgtest
AUTOPKGTEST_CLOUD=~/git/autopkgtest-cloud

setup_commands=(
	"${AUTOPKGTEST}"/setup-commands/setup-testbed
	"${AUTOPKGTEST_CLOUD}"/autopkgtest-cloud/worker-config-production/setup-canonical.sh
	"${AUTOPKGTEST_CLOUD}"/autopkgtest-cloud/worker-config-production/qemu-efi-noacpi.sh
)

# Globals
USER_DATA=
SERVER_NAME=
trap out EXIT INT TERM HUP

# Create cloud-init userdata
USER_DATA=$(mktemp)
cat << EOF > "${USER_DATA}"
#cloud-config

hostname: autopkgtest
manage_etc_hosts: true
apt_update: true
apt_upgrade: false
${MIRROR}

runcmd:
 - echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/90nolanguages
 - echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/autopkgtest
 - printf '${EXTRA_ENV}\n' >> /etc/environment
 - sed -i -r '/^127.0.1.1/ s/autopkgtest-[^ ]+\\./autopkgtest\\./' /etc/hosts
EOF

# Create a server
SERVER_NAME=juergh/adt-${release}-${arch}-$(date +%Y%m%d-%H%M%S)
echo "-- Server name: ${SERVER_NAME}"
server_id=$(openstack server create \
					  --flavor "${flavor}" \
					  --image "${image}" \
					  --user-data "${USER_DATA}" \
					  --key-name "${key_name}" \
					  --network "${network}" \
					  --security-group "${security_group}" \
					  "${SERVER_NAME}" | \
				tee /dev/stderr | awk '$2 == "id" { print $4 }')
echo "-- Server ID: ${server_id}"
wait_for_status 300 server "${server_id}" ACTIVE

# Get the server's IP address
ip_addr=$(openstack server show "${server_id}" | \
			  awk '$2 == "addresses" { print $4 }')
ip_addr=${ip_addr#*=}
echo "-- Server IP address: ${ip_addr}"

ssh_cmd=(
	"ssh"
	"-o" "UserKnownHostsFile=/dev/null"
	"-o" "StrictHostKeyChecking=no"
	"-o" "ConnectTimeout=10"
	"-o" "LogLevel=ERROR"
	"ubuntu@${ip_addr}"
)

echo "-- Wait for SSH"
timeout 300 sh -c "while ! ${ssh_cmd[*]} true ; do sleep 5 ; done"

echo "-- Wait until cloud-init is done"
timeout 25m "${ssh_cmd[@]}" "while [ ! -e /var/lib/cloud/instance/boot-finished ] ; do sleep 1 ; done"

echo "-- Run setup command"
for setup_command in "${setup_commands[@]}" ; do
	# shellcheck disable=SC2002
	cat "${setup_command}" | "${ssh_cmd[@]}" "sudo sh -"
done

echo "-- Created server: ${SERVER_NAME}"
SERVER_NAME=

