#!/bin/bash
#
# Init script for create-vm which is run at first boot
#

function fix_grub()
{
	if ! [ -e /etc/default/grub ] ; then
		return
	fi

	# Configure grub
	test -d /etc/default/grub.d || mkdir /etc/default/grub.d
	cat <<__EOF__ > /etc/default/grub.d/99-create-vm.cfg
unset GRUB_HIDDEN_TIMEOUT GRUB_TIMEOUT_STYLE GRUB_FORCE_PARTUUID
GRUB_TIMEOUT=2
GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0"
__EOF__

	# Reinstall and update grub
	grub-install /dev/vda
	update-grub
}

function setup_esm_repo()
{
	if ! [ -e /etc/cloud/cidata/esm-ppa.list ] ; then
		return
	fi

	# Copy the ESM PPA list file
	cp /etc/cloud/cidata/esm-ppa.list /etc/apt/sources.list.d/

	# Download the PPA public keys
	while IFS= read -r keyid ; do
		apt-key adv --keyserver keyserver.ubuntu.com --recv-key "${keyid}"
	done < <(awk '/PPA public key/ { print $NF }' \
				 /etc/apt/sources.list.d/*.list)

	# Update the package index files
	apt-get --yes update
}

function do_init()
{
	# Timestamp
	date -R

	fix_grub
	setup_esm_repo

	# Timestamp
	date -R
}

# -----------------------------------------------------------------------------
# Main entry point

# Wait until cloud-init is finished
while ! [ -e /var/lib/cloud/instance/boot-finished ] ; do
	sleep 1
done

# Do the initialization
do_init 2>&1 | tee /etc/cloud/create-vm.log
date -R > /etc/cloud/create-vm.done

# Reboot
# shellcheck disable=SC2170,SC2050
if [ __REBOOT__ -eq 1 ] ; then
	reboot
fi
