#!/bin/bash
#
# Setup script for create-vm which is run at first boot
#

function purge_packages()
{
	local pkgs pkg

	echo "-- Purging packages"

	pkgs=("unattended-upgrades")
	if [ "${TYPE}" = "adt" ] ; then
		pkgs+=("lxd" "lxd-client" "snapd")
	fi

	for pkg in "${pkgs[@]}" ; do
		apt-get purge --yes --auto-remove "${pkg}"
	done
}

function fix_grub()
{
	local serial

	if ! [ -e /etc/default/grub ] ; then
		return
	fi

	echo "-- Fixing grub"

	# Figure out the serial console
	for serial in hvc0 ttyAMA0 ttyS0 ; do
		if [ -e "/dev/${serial}" ] ; then
			break
		fi
	done

	# Configure grub
	test -d /etc/default/grub.d || mkdir /etc/default/grub.d
	cat <<__EOF__ > /etc/default/grub.d/99-create-vm.cfg
unset GRUB_HIDDEN_TIMEOUT GRUB_TIMEOUT_STYLE GRUB_FORCE_PARTUUID
GRUB_TIMEOUT=2
GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=${serial}"
__EOF__

	# Reinstall and update grub
	grub-install /dev/vda
	update-grub
}

function add_esm_repo()
{
	local keyid

	if ! [ -e "${HERE}"/esm-ppa.list ] ; then
		return
	fi

	echo "-- Adding ESM repo"

	# Copy the ESM PPA list file
	cp "${HERE}"/esm-ppa.list /etc/apt/sources.list.d/

	# Download the PPA public keys
	while IFS= read -r keyid ; do
		apt-key adv --keyserver keyserver.ubuntu.com --recv-key "${keyid}"
	done < <(awk '/PPA public key/ { print $NF }' \
				 /etc/apt/sources.list.d/*.list)

	APT_UPDATE=1
}

function setup_type()
{
	if [ "${TYPE}" = "adt" ] ; then
		echo "-- Adding source repos"
		grep -h '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/*.list | \
			sed 's/^deb /deb-src /' >> /etc/apt/sources.list.d/deb-src.list
		APT_UPDATE=1
	fi
}

function main()
{
	# Globals
	APT_UPDATE=0
	HERE=$(dirname "$(readlink -f "${0}")")

	echo "-- Waiting for cloud-init to finish"
	while ! [ -e /var/lib/cloud/instance/boot-finished ] ; do
		sleep 1
	done

	echo "-- Sourcing setup-vm.config"
	# shellcheck disable=SC1090
	. "${HERE}"/setup-vm.config

	purge_packages
	fix_grub
	add_esm_repo
	setup_type

	if [ "${APT_UPDATE}" -eq 1 ] ; then
		apt-get update --yes
	fi

	if [ "${SHUTDOWN}" -eq 1 ] ; then
		echo "-- Shutting down"
		poweroff
	elif [ "${REBOOT}" -eq 1 ] ; then
		echo "-- Rebooting"
		reboot
	fi
}

# -----------------------------------------------------------------------------
# Main entry point

main 2>&1 | \
	awk '{ print strftime("%Y-%m-%d %H:%M:%S -"), $0 }' | \
	tee -a /var/log/setup-vm.log
