#!/bin/bash
#
# Setup script for create-vm which is run at first boot
#

function fix_grub()
{
	local serial

	if ! [ -e /etc/default/grub ] ; then
		return
	fi

	# Figure out the serial console
	for serial in hvc0 ttyAMA0 ttyS0 ; do
		if [ -e "/dev/${serial}" ] ; then
			break
		fi
	done

	# Configure grub
	test -d /etc/default/grub.d || mkdir /etc/default/grub.d
	cat <<__EOF__ > /etc/default/grub.d/99-create-vm.cfg
unset GRUB_HIDDEN_TIMEOUT GRUB_TIMEOUT_STYLE GRUB_FORCE_PARTUUID
GRUB_TIMEOUT=2
GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=${serial}"
__EOF__

	# Reinstall and update grub
	grub-install /dev/vda
	update-grub
}

function setup_esm_repo()
{
	if ! [ -e /etc/cloud/cidata/esm-ppa.list ] ; then
		return
	fi

	# Copy the ESM PPA list file
	cp /etc/cloud/cidata/esm-ppa.list /etc/apt/sources.list.d/

	# Download the PPA public keys
	while IFS= read -r keyid ; do
		apt-key adv --keyserver keyserver.ubuntu.com --recv-key "${keyid}"
	done < <(awk '/PPA public key/ { print $NF }' \
				 /etc/apt/sources.list.d/*.list)

	# Update the package index files
	apt-get --yes update
}

function do_init()
{
	echo "-- Waiting for cloud-init to finish"
	while ! [ -e /var/lib/cloud/instance/boot-finished ] ; do
		sleep 1
	done

	echo "-- Purging packages"
	apt-get --yes purge unattended-upgrades

	echo "-- Fixing grub"
	fix_grub

	echo "-- Setting up ESM repo"
	setup_esm_repo

	# shellcheck disable=SC2170,SC2050
	if [ __REBOOT__ -eq 1 ] ; then
		echo "-- Rebooting"
		reboot
	fi
}

# -----------------------------------------------------------------------------
# Main entry point

do_init 2>&1 | \
	awk '{ print strftime("%Y-%m-%d %H:%M:%S -"), $0 }' | \
	tee -a /var/log/setup-vm.log
